module ast

// 语句节点类型
pub const node_stmt_echo = 'Stmt_Echo'
pub const node_stmt_expression = 'Stmt_Expression'
pub const node_stmt_if = 'Stmt_If'
pub const node_stmt_elseif = 'Stmt_ElseIf'
pub const node_stmt_else = 'Stmt_Else'
pub const node_stmt_function = 'Stmt_Function'
pub const node_stmt_return = 'Stmt_Return'
pub const node_expr_funccall = 'Expr_FuncCall'
pub const node_stmt_foreach = 'Stmt_Foreach'
pub const node_stmt_while = 'Stmt_While'
pub const node_stmt_for = 'Stmt_For'
pub const node_stmt_break = 'Stmt_Break'
pub const node_stmt_continue = 'Stmt_Continue'
pub const node_stmt_class = 'Stmt_Class'
pub const node_stmt_class_method = 'Stmt_ClassMethod'
pub const node_stmt_property = 'Stmt_Property'
pub const node_stmt_property_property = 'Stmt_PropertyProperty'
pub const node_expr_new = 'Expr_New'
pub const node_expr_method_call = 'Expr_MethodCall'
pub const node_expr_property_fetch = 'Expr_PropertyFetch'
pub const node_expr_eval = 'Expr_Eval'
pub const node_expr_closure = 'Expr_Closure'
pub const node_expr_arrow_function = 'Expr_ArrowFunction'
pub const node_expr_include = 'Expr_Include'

// 表达式节点类型
pub const node_expr_assign = 'Expr_Assign'
pub const node_expr_variable = 'Expr_Variable'
pub const node_expr_const = 'Expr_ConstFetch'
pub const node_expr_array = 'Expr_Array'
pub const node_expr_array_item = 'ArrayItem'
pub const node_expr_array_dim_fetch = 'Expr_ArrayDimFetch'
pub const node_expr_static_call = 'Expr_StaticCall'
pub const node_expr_boolean_not = 'Expr_BooleanNot'
pub const node_expr_ternary = 'Expr_Ternary'

// 二元运算节点类型
pub const node_bin_plus = 'Expr_BinaryOp_Plus'
pub const node_bin_minus = 'Expr_BinaryOp_Minus'
pub const node_bin_mul = 'Expr_BinaryOp_Mul'
pub const node_bin_div = 'Expr_BinaryOp_Div'
pub const node_bin_mod = 'Expr_BinaryOp_Mod'
pub const node_bin_concat = 'Expr_BinaryOp_Concat'
pub const node_bin_greater = 'Expr_BinaryOp_Greater'
pub const node_bin_smaller = 'Expr_BinaryOp_Smaller'
pub const node_bin_greater_equal = 'Expr_BinaryOp_GreaterOrEqual'
pub const node_bin_smaller_equal = 'Expr_BinaryOp_SmallerOrEqual'
pub const node_bin_equal = 'Expr_BinaryOp_Equal'
pub const node_bin_identical = 'Expr_BinaryOp_Identical'
pub const node_bin_bool_and = 'Expr_BinaryOp_BooleanAnd'
pub const node_bin_bool_or = 'Expr_BinaryOp_BooleanOr'
pub const node_bin_logical_and = 'Expr_BinaryOp_LogicalAnd'
pub const node_bin_logical_or = 'Expr_BinaryOp_LogicalOr'
pub const node_bin_coalesce = 'Expr_BinaryOp_Coalesce'

// 标量节点类型
pub const node_scalar_int = 'Scalar_Int'
pub const node_scalar_float = 'Scalar_Float'
pub const node_scalar_string = 'Scalar_String'
pub const node_scalar_magic_const_dir = 'Scalar_MagicConst_Dir'
pub const node_scalar_magic_const_file = 'Scalar_MagicConst_File'
pub const node_scalar_magic_const_line = 'Scalar_MagicConst_Line'
pub const node_stmt_const = 'Stmt_Const'
pub const node_stmt_try_catch = 'Stmt_TryCatch'
pub const node_stmt_catch = 'Stmt_Catch'
pub const node_expr_throw = 'Expr_Throw'
pub const node_expr_isset = 'Expr_Isset'
pub const node_stmt_unset = 'Stmt_Unset'
pub const node_expr_empty = 'Expr_Empty'
pub const node_scalar_encapsed = 'Scalar_Encapsed'
pub const node_stmt_namespace = 'Stmt_Namespace'
pub const node_stmt_use = 'Stmt_Use'
pub const node_stmt_use_use = 'Stmt_UseUse'
pub const node_scalar_interpolated_string = 'Scalar_InterpolatedString'
pub const node_scalar_encapsed_string_part = 'Scalar_EncapsedStringPart'
pub const node_scalar_interpolated_string_part = 'InterpolatedStringPart'
