import rt

struct Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Enums_CouponStatus {
	rt.PhpObjectBase
}

fn init_static_automattic_woocommerce_internal_api_autogenerated_graphqltypes_enums_couponstatus() {
	rt.init_static_prop('Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Enums_CouponStatus',
		'instance', rt.new_null())
}

fn Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Enums_CouponStatus.get() rt.PhpVal {
	if rt.is_true(rt.identical(rt.new_null(), rt.get_static_prop('Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Enums_CouponStatus',
		'instance')))
	{
		rt.set_static_prop('Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Enums_CouponStatus',
			'instance', rt.new_object('Automattic_WooCommerce_Internal_Api_Schema_EnumType',
			[]string{}, create_automattic_woocommerce_internal_api_schema_enumtype(rt.create_array([
			rt.ArrayItem{ key: 'name', val: 'CouponStatus' },
			rt.ArrayItem{ key: 'description', val: rt.call_function('__', [
				rt.new_string('The publication status of a coupon.'),
				rt.new_string('woocommerce'),
			]) },
			rt.ArrayItem{ key: 'values', val: rt.create_array([
				rt.ArrayItem{ key: 'PUBLISHED', val: rt.create_array([
					rt.ArrayItem{
						key: 'value'
						val: Class_Automattic_WooCommerce_Api_Enums_Coupons_CouponStatus.published()
					},
					rt.ArrayItem{ key: 'description', val: rt.call_function('__', [
						rt.new_string('The coupon is published and active.'),
						rt.new_string('woocommerce'),
					]) },
				]) },
				rt.ArrayItem{ key: 'DRAFT', val: rt.create_array([
					rt.ArrayItem{
						key: 'value'
						val: Class_Automattic_WooCommerce_Api_Enums_Coupons_CouponStatus.draft()
					},
					rt.ArrayItem{ key: 'description', val: rt.call_function('__', [
						rt.new_string('The coupon is a draft.'),
						rt.new_string('woocommerce'),
					]) },
				]) },
				rt.ArrayItem{ key: 'PENDING', val: rt.create_array([
					rt.ArrayItem{
						key: 'value'
						val: Class_Automattic_WooCommerce_Api_Enums_Coupons_CouponStatus.pending()
					},
					rt.ArrayItem{ key: 'description', val: rt.call_function('__', [
						rt.new_string('The coupon is pending review.'),
						rt.new_string('woocommerce'),
					]) },
				]) },
				rt.ArrayItem{ key: 'PRIVATE', val: rt.create_array([
					rt.ArrayItem{
						key: 'value'
						val: Class_Automattic_WooCommerce_Api_Enums_Coupons_CouponStatus.private()
					},
					rt.ArrayItem{ key: 'description', val: rt.call_function('__', [
						rt.new_string('The coupon is privately published.'),
						rt.new_string('woocommerce'),
					]) },
				]) },
				rt.ArrayItem{ key: 'FUTURE', val: rt.create_array([
					rt.ArrayItem{
						key: 'value'
						val: Class_Automattic_WooCommerce_Api_Enums_Coupons_CouponStatus.future()
					},
					rt.ArrayItem{ key: 'description', val: rt.call_function('__', [
						rt.new_string('The coupon is scheduled to be published in the future.'),
						rt.new_string('woocommerce'),
					]) },
				]) },
				rt.ArrayItem{ key: 'TRASH', val: rt.create_array([
					rt.ArrayItem{
						key: 'value'
						val: Class_Automattic_WooCommerce_Api_Enums_Coupons_CouponStatus.trash()
					},
					rt.ArrayItem{ key: 'description', val: rt.call_function('__', [
						rt.new_string('The coupon is in the trash.'),
						rt.new_string('woocommerce'),
					]) },
				]) },
				rt.ArrayItem{ key: 'OTHER', val: rt.create_array([
					rt.ArrayItem{
						key: 'value'
						val: Class_Automattic_WooCommerce_Api_Enums_Coupons_CouponStatus.other()
					},
					rt.ArrayItem{ key: 'description', val: rt.call_function('__', [
						rt.new_string('The coupon status is not one of the standard WordPress values (e.g. added by a plugin). Inspect raw_status for the underlying value.'),
						rt.new_string('woocommerce'),
					]) },
				]) },
			]) },
		]))))
	}
	return rt.get_static_prop('Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Enums_CouponStatus',
		'instance')
}

struct Class_Automattic_WooCommerce_Internal_Api_Schema_EnumType {
	rt.PhpObjectBase
}

fn create_automattic_woocommerce_internal_api_autogenerated_graphqltypes_enums_couponstatus(_args ...rt.PhpVal) &Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Enums_CouponStatus {
	mut obj := &Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Enums_CouponStatus{
		PhpObjectBase: rt.PhpObjectBase{}
	}
	return obj
}

fn create_automattic_woocommerce_internal_api_schema_enumtype(_args ...rt.PhpVal) &Class_Automattic_WooCommerce_Internal_Api_Schema_EnumType {
	mut obj := &Class_Automattic_WooCommerce_Internal_Api_Schema_EnumType{
		PhpObjectBase: rt.PhpObjectBase{}
	}
	return obj
}

fn (mut this Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Enums_CouponStatus) dispatch_method(method_name string, args []rt.PhpVal) ?rt.PhpVal {
	match method_name {
		'get' {
			return Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Enums_CouponStatus.get()
		}
		else {
			return none
		}
	}
}

fn (this &Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Enums_CouponStatus) dispatch_get_prop(prop_name string) ?rt.PhpVal {
	return this.PhpObjectBase.dispatch_get_prop(prop_name)
}

fn (mut this Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Enums_CouponStatus) dispatch_set_prop(prop_name string, val rt.PhpVal) bool {
	return this.PhpObjectBase.dispatch_set_prop(prop_name, val)
}

fn (mut this Class_Automattic_WooCommerce_Internal_Api_Schema_EnumType) dispatch_method(method_name string, args []rt.PhpVal) ?rt.PhpVal {
	return none
}

fn (this &Class_Automattic_WooCommerce_Internal_Api_Schema_EnumType) dispatch_get_prop(prop_name string) ?rt.PhpVal {
	return this.PhpObjectBase.dispatch_get_prop(prop_name)
}

fn (mut this Class_Automattic_WooCommerce_Internal_Api_Schema_EnumType) dispatch_set_prop(prop_name string, val rt.PhpVal) bool {
	return this.PhpObjectBase.dispatch_set_prop(prop_name, val)
}

fn main() {
	defer {
		rt.shutdown()
	}
}
