import rt

struct Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Enums_ProductType {
	rt.PhpObjectBase
}

fn init_static_automattic_woocommerce_internal_api_autogenerated_graphqltypes_enums_producttype() {
	rt.init_static_prop('Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Enums_ProductType',
		'instance', rt.new_null())
}

fn Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Enums_ProductType.get() rt.PhpVal {
	if rt.is_true(rt.identical(rt.new_null(), rt.get_static_prop('Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Enums_ProductType',
		'instance')))
	{
		rt.set_static_prop('Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Enums_ProductType',
			'instance', rt.new_object('Automattic_WooCommerce_Internal_Api_Schema_EnumType',
			[]string{}, create_automattic_woocommerce_internal_api_schema_enumtype(rt.create_array([
			rt.ArrayItem{ key: 'name', val: 'ProductType' },
			rt.ArrayItem{ key: 'description', val: rt.call_function('__', [
				rt.new_string('The type of a WooCommerce product.'),
				rt.new_string('woocommerce'),
			]) },
			rt.ArrayItem{ key: 'values', val: rt.create_array([
				rt.ArrayItem{ key: 'SIMPLE', val: rt.create_array([
					rt.ArrayItem{
						key: 'value'
						val: Class_Automattic_WooCommerce_Api_Enums_Products_ProductType.simple()
					},
					rt.ArrayItem{ key: 'description', val: rt.call_function('__', [
						rt.new_string('A simple product.'),
						rt.new_string('woocommerce'),
					]) },
				]) },
				rt.ArrayItem{ key: 'GROUPED', val: rt.create_array([
					rt.ArrayItem{
						key: 'value'
						val: Class_Automattic_WooCommerce_Api_Enums_Products_ProductType.grouped()
					},
					rt.ArrayItem{ key: 'description', val: rt.call_function('__', [
						rt.new_string('A grouped product.'),
						rt.new_string('woocommerce'),
					]) },
				]) },
				rt.ArrayItem{ key: 'EXTERNAL', val: rt.create_array([
					rt.ArrayItem{
						key: 'value'
						val: Class_Automattic_WooCommerce_Api_Enums_Products_ProductType.external()
					},
					rt.ArrayItem{ key: 'description', val: rt.call_function('__', [
						rt.new_string('An external/affiliate product.'),
						rt.new_string('woocommerce'),
					]) },
				]) },
				rt.ArrayItem{ key: 'VARIABLE', val: rt.create_array([
					rt.ArrayItem{
						key: 'value'
						val: Class_Automattic_WooCommerce_Api_Enums_Products_ProductType.variable()
					},
					rt.ArrayItem{ key: 'description', val: rt.call_function('__', [
						rt.new_string('A variable product with variations.'),
						rt.new_string('woocommerce'),
					]) },
				]) },
				rt.ArrayItem{ key: 'VARIATION', val: rt.create_array([
					rt.ArrayItem{
						key: 'value'
						val: Class_Automattic_WooCommerce_Api_Enums_Products_ProductType.variation()
					},
					rt.ArrayItem{ key: 'description', val: rt.call_function('__', [
						rt.new_string('A product variation.'),
						rt.new_string('woocommerce'),
					]) },
				]) },
				rt.ArrayItem{ key: 'OTHER', val: rt.create_array([
					rt.ArrayItem{
						key: 'value'
						val: Class_Automattic_WooCommerce_Api_Enums_Products_ProductType.other()
					},
					rt.ArrayItem{ key: 'description', val: rt.call_function('__', [
						rt.new_string('The product type is not one of the standard WooCommerce values (e.g. added by a plugin). Inspect raw_product_type for the underlying value.'),
						rt.new_string('woocommerce'),
					]) },
				]) },
			]) },
		]))))
	}
	return rt.get_static_prop('Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Enums_ProductType',
		'instance')
}

struct Class_Automattic_WooCommerce_Internal_Api_Schema_EnumType {
	rt.PhpObjectBase
}

fn create_automattic_woocommerce_internal_api_autogenerated_graphqltypes_enums_producttype(_args ...rt.PhpVal) &Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Enums_ProductType {
	mut obj := &Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Enums_ProductType{
		PhpObjectBase: rt.PhpObjectBase{}
	}
	return obj
}

fn create_automattic_woocommerce_internal_api_schema_enumtype(_args ...rt.PhpVal) &Class_Automattic_WooCommerce_Internal_Api_Schema_EnumType {
	mut obj := &Class_Automattic_WooCommerce_Internal_Api_Schema_EnumType{
		PhpObjectBase: rt.PhpObjectBase{}
	}
	return obj
}

fn (mut this Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Enums_ProductType) dispatch_method(method_name string, args []rt.PhpVal) ?rt.PhpVal {
	match method_name {
		'get' {
			return Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Enums_ProductType.get()
		}
		else {
			return none
		}
	}
}

fn (this &Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Enums_ProductType) dispatch_get_prop(prop_name string) ?rt.PhpVal {
	return this.PhpObjectBase.dispatch_get_prop(prop_name)
}

fn (mut this Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Enums_ProductType) dispatch_set_prop(prop_name string, val rt.PhpVal) bool {
	return this.PhpObjectBase.dispatch_set_prop(prop_name, val)
}

fn (mut this Class_Automattic_WooCommerce_Internal_Api_Schema_EnumType) dispatch_method(method_name string, args []rt.PhpVal) ?rt.PhpVal {
	return none
}

fn (this &Class_Automattic_WooCommerce_Internal_Api_Schema_EnumType) dispatch_get_prop(prop_name string) ?rt.PhpVal {
	return this.PhpObjectBase.dispatch_get_prop(prop_name)
}

fn (mut this Class_Automattic_WooCommerce_Internal_Api_Schema_EnumType) dispatch_set_prop(prop_name string, val rt.PhpVal) bool {
	return this.PhpObjectBase.dispatch_set_prop(prop_name, val)
}

fn main() {
	defer {
		rt.shutdown()
	}
}
