import rt

struct Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Enums_StockStatus {
	rt.PhpObjectBase
}

fn init_static_automattic_woocommerce_internal_api_autogenerated_graphqltypes_enums_stockstatus() {
	rt.init_static_prop('Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Enums_StockStatus',
		'instance', rt.new_null())
}

fn Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Enums_StockStatus.get() rt.PhpVal {
	if rt.is_true(rt.identical(rt.new_null(), rt.get_static_prop('Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Enums_StockStatus',
		'instance')))
	{
		rt.set_static_prop('Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Enums_StockStatus',
			'instance', rt.new_object('Automattic_WooCommerce_Internal_Api_Schema_EnumType',
			[]string{}, create_automattic_woocommerce_internal_api_schema_enumtype(rt.create_array([
			rt.ArrayItem{ key: 'name', val: 'StockStatus' },
			rt.ArrayItem{ key: 'description', val: rt.call_function('__', [
				rt.new_string('The stock status of a product.'),
				rt.new_string('woocommerce'),
			]) },
			rt.ArrayItem{ key: 'values', val: rt.create_array([
				rt.ArrayItem{ key: 'IN_STOCK', val: rt.create_array([
					rt.ArrayItem{
						key: 'value'
						val: Class_Automattic_WooCommerce_Api_Enums_Products_StockStatus.instock()
					},
					rt.ArrayItem{ key: 'description', val: rt.call_function('__', [
						rt.new_string('The product is in stock.'),
						rt.new_string('woocommerce'),
					]) },
				]) },
				rt.ArrayItem{ key: 'OUT_OF_STOCK', val: rt.create_array([
					rt.ArrayItem{
						key: 'value'
						val: Class_Automattic_WooCommerce_Api_Enums_Products_StockStatus.outofstock()
					},
					rt.ArrayItem{ key: 'description', val: rt.call_function('__', [
						rt.new_string('The product is out of stock.'),
						rt.new_string('woocommerce'),
					]) },
				]) },
				rt.ArrayItem{ key: 'ON_BACKORDER', val: rt.create_array([
					rt.ArrayItem{
						key: 'value'
						val: Class_Automattic_WooCommerce_Api_Enums_Products_StockStatus.onbackorder()
					},
					rt.ArrayItem{ key: 'description', val: rt.call_function('__', [
						rt.new_string('The product is on backorder.'),
						rt.new_string('woocommerce'),
					]) },
				]) },
				rt.ArrayItem{ key: 'OTHER', val: rt.create_array([
					rt.ArrayItem{
						key: 'value'
						val: Class_Automattic_WooCommerce_Api_Enums_Products_StockStatus.other()
					},
					rt.ArrayItem{ key: 'description', val: rt.call_function('__', [
						rt.new_string('The stock status is not one of the standard WooCommerce values (e.g. added by a plugin). Inspect raw_stock_status for the underlying value.'),
						rt.new_string('woocommerce'),
					]) },
				]) },
			]) },
		]))))
	}
	return rt.get_static_prop('Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Enums_StockStatus',
		'instance')
}

struct Class_Automattic_WooCommerce_Internal_Api_Schema_EnumType {
	rt.PhpObjectBase
}

fn create_automattic_woocommerce_internal_api_autogenerated_graphqltypes_enums_stockstatus(_args ...rt.PhpVal) &Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Enums_StockStatus {
	mut obj := &Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Enums_StockStatus{
		PhpObjectBase: rt.PhpObjectBase{}
	}
	return obj
}

fn create_automattic_woocommerce_internal_api_schema_enumtype(_args ...rt.PhpVal) &Class_Automattic_WooCommerce_Internal_Api_Schema_EnumType {
	mut obj := &Class_Automattic_WooCommerce_Internal_Api_Schema_EnumType{
		PhpObjectBase: rt.PhpObjectBase{}
	}
	return obj
}

fn (mut this Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Enums_StockStatus) dispatch_method(method_name string, args []rt.PhpVal) ?rt.PhpVal {
	match method_name {
		'get' {
			return Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Enums_StockStatus.get()
		}
		else {
			return none
		}
	}
}

fn (this &Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Enums_StockStatus) dispatch_get_prop(prop_name string) ?rt.PhpVal {
	return this.PhpObjectBase.dispatch_get_prop(prop_name)
}

fn (mut this Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Enums_StockStatus) dispatch_set_prop(prop_name string, val rt.PhpVal) bool {
	return this.PhpObjectBase.dispatch_set_prop(prop_name, val)
}

fn (mut this Class_Automattic_WooCommerce_Internal_Api_Schema_EnumType) dispatch_method(method_name string, args []rt.PhpVal) ?rt.PhpVal {
	return none
}

fn (this &Class_Automattic_WooCommerce_Internal_Api_Schema_EnumType) dispatch_get_prop(prop_name string) ?rt.PhpVal {
	return this.PhpObjectBase.dispatch_get_prop(prop_name)
}

fn (mut this Class_Automattic_WooCommerce_Internal_Api_Schema_EnumType) dispatch_set_prop(prop_name string, val rt.PhpVal) bool {
	return this.PhpObjectBase.dispatch_set_prop(prop_name, val)
}

fn main() {
	defer {
		rt.shutdown()
	}
}
