import rt

struct Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Output_Coupon {
	rt.PhpObjectBase
}

fn init_static_automattic_woocommerce_internal_api_autogenerated_graphqltypes_output_coupon() {
	rt.init_static_prop('Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Output_Coupon',
		'instance', rt.new_null())
}

fn Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Output_Coupon.get() rt.PhpVal {
	if rt.is_true(rt.identical(rt.new_null(), rt.get_static_prop('Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Output_Coupon',
		'instance')))
	{
		closure_2_fn := fn (this_ptr rt.PhpVal, args []rt.PhpVal) rt.PhpVal {
			mut iife_temp_1 :=
				Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Interfaces_ObjectWithId{}
			mut iife_result_1 := iife_temp_1.get()
			return rt.create_array([rt.ArrayItem{ key: none, val: iife_result_1 }])
		}
		closure_63_fn := fn (this_ptr rt.PhpVal, args []rt.PhpVal) rt.PhpVal {
			mut iife_temp_3 := Class_Automattic_WooCommerce_Internal_Api_Schema_Type{}
			mut iife_result_3 := iife_temp_3.string()
			mut iife_temp_4 := Class_Automattic_WooCommerce_Internal_Api_Schema_Type{}
			mut iife_result_4 := iife_temp_4.nonnull(iife_result_3)
			mut iife_temp_5 := Class_Automattic_WooCommerce_Internal_Api_Schema_Type{}
			mut iife_result_5 := iife_temp_5.string()
			mut iife_temp_6 := Class_Automattic_WooCommerce_Internal_Api_Schema_Type{}
			mut iife_result_6 := iife_temp_6.nonnull(iife_result_5)
			mut iife_temp_7 :=
				Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Enums_DiscountType{}
			mut iife_result_7 := iife_temp_7.get()
			mut iife_temp_8 := Class_Automattic_WooCommerce_Internal_Api_Schema_Type{}
			mut iife_result_8 := iife_temp_8.nonnull(iife_result_7)
			mut iife_temp_9 := Class_Automattic_WooCommerce_Internal_Api_Schema_Type{}
			mut iife_result_9 := iife_temp_9.string()
			mut iife_temp_10 := Class_Automattic_WooCommerce_Internal_Api_Schema_Type{}
			mut iife_result_10 := iife_temp_10.nonnull(iife_result_9)
			mut iife_temp_11 := Class_Automattic_WooCommerce_Internal_Api_Schema_Type{}
			mut iife_result_11 := iife_temp_11.float()
			mut iife_temp_12 := Class_Automattic_WooCommerce_Internal_Api_Schema_Type{}
			mut iife_result_12 := iife_temp_12.nonnull(iife_result_11)
			mut iife_temp_13 :=
				Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Enums_CouponStatus{}
			mut iife_result_13 := iife_temp_13.get()
			mut iife_temp_14 := Class_Automattic_WooCommerce_Internal_Api_Schema_Type{}
			mut iife_result_14 := iife_temp_14.nonnull(iife_result_13)
			mut iife_temp_15 := Class_Automattic_WooCommerce_Internal_Api_Schema_Type{}
			mut iife_result_15 := iife_temp_15.string()
			mut iife_temp_16 := Class_Automattic_WooCommerce_Internal_Api_Schema_Type{}
			mut iife_result_16 := iife_temp_16.nonnull(iife_result_15)
			mut iife_temp_17 :=
				Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Scalars_DateTime{}
			mut iife_result_17 := iife_temp_17.get()
			mut iife_temp_18 :=
				Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Scalars_DateTime{}
			mut iife_result_18 := iife_temp_18.get()
			mut iife_temp_19 :=
				Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Scalars_DateTime{}
			mut iife_result_19 := iife_temp_19.get()
			mut iife_temp_20 := Class_Automattic_WooCommerce_Internal_Api_Schema_Type{}
			mut iife_result_20 := iife_temp_20.int()
			mut iife_temp_21 := Class_Automattic_WooCommerce_Internal_Api_Schema_Type{}
			mut iife_result_21 := iife_temp_21.nonnull(iife_result_20)
			mut iife_temp_22 := Class_Automattic_WooCommerce_Internal_Api_Schema_Type{}
			mut iife_result_22 := iife_temp_22.boolean()
			mut iife_temp_23 := Class_Automattic_WooCommerce_Internal_Api_Schema_Type{}
			mut iife_result_23 := iife_temp_23.nonnull(iife_result_22)
			mut iife_temp_24 := Class_Automattic_WooCommerce_Internal_Api_Schema_Type{}
			mut iife_result_24 := iife_temp_24.int()
			mut iife_temp_25 := Class_Automattic_WooCommerce_Internal_Api_Schema_Type{}
			mut iife_result_25 := iife_temp_25.nonnull(iife_result_24)
			mut iife_temp_26 := Class_Automattic_WooCommerce_Internal_Api_Schema_Type{}
			mut iife_result_26 := iife_temp_26.listof(iife_result_25)
			mut iife_temp_27 := Class_Automattic_WooCommerce_Internal_Api_Schema_Type{}
			mut iife_result_27 := iife_temp_27.nonnull(iife_result_26)
			mut iife_temp_28 := Class_Automattic_WooCommerce_Internal_Api_Schema_Type{}
			mut iife_result_28 := iife_temp_28.int()
			mut iife_temp_29 := Class_Automattic_WooCommerce_Internal_Api_Schema_Type{}
			mut iife_result_29 := iife_temp_29.nonnull(iife_result_28)
			mut iife_temp_30 := Class_Automattic_WooCommerce_Internal_Api_Schema_Type{}
			mut iife_result_30 := iife_temp_30.listof(iife_result_29)
			mut iife_temp_31 := Class_Automattic_WooCommerce_Internal_Api_Schema_Type{}
			mut iife_result_31 := iife_temp_31.nonnull(iife_result_30)
			mut iife_temp_32 := Class_Automattic_WooCommerce_Internal_Api_Schema_Type{}
			mut iife_result_32 := iife_temp_32.int()
			mut iife_temp_33 := Class_Automattic_WooCommerce_Internal_Api_Schema_Type{}
			mut iife_result_33 := iife_temp_33.nonnull(iife_result_32)
			mut iife_temp_34 := Class_Automattic_WooCommerce_Internal_Api_Schema_Type{}
			mut iife_result_34 := iife_temp_34.int()
			mut iife_temp_35 := Class_Automattic_WooCommerce_Internal_Api_Schema_Type{}
			mut iife_result_35 := iife_temp_35.nonnull(iife_result_34)
			mut iife_temp_36 := Class_Automattic_WooCommerce_Internal_Api_Schema_Type{}
			mut iife_result_36 := iife_temp_36.int()
			mut iife_temp_37 := Class_Automattic_WooCommerce_Internal_Api_Schema_Type{}
			mut iife_result_37 := iife_temp_37.boolean()
			mut iife_temp_38 := Class_Automattic_WooCommerce_Internal_Api_Schema_Type{}
			mut iife_result_38 := iife_temp_38.nonnull(iife_result_37)
			mut iife_temp_39 := Class_Automattic_WooCommerce_Internal_Api_Schema_Type{}
			mut iife_result_39 := iife_temp_39.int()
			mut iife_temp_40 := Class_Automattic_WooCommerce_Internal_Api_Schema_Type{}
			mut iife_result_40 := iife_temp_40.nonnull(iife_result_39)
			mut iife_temp_41 := Class_Automattic_WooCommerce_Internal_Api_Schema_Type{}
			mut iife_result_41 := iife_temp_41.listof(iife_result_40)
			mut iife_temp_42 := Class_Automattic_WooCommerce_Internal_Api_Schema_Type{}
			mut iife_result_42 := iife_temp_42.nonnull(iife_result_41)
			mut iife_temp_43 := Class_Automattic_WooCommerce_Internal_Api_Schema_Type{}
			mut iife_result_43 := iife_temp_43.int()
			mut iife_temp_44 := Class_Automattic_WooCommerce_Internal_Api_Schema_Type{}
			mut iife_result_44 := iife_temp_44.nonnull(iife_result_43)
			mut iife_temp_45 := Class_Automattic_WooCommerce_Internal_Api_Schema_Type{}
			mut iife_result_45 := iife_temp_45.listof(iife_result_44)
			mut iife_temp_46 := Class_Automattic_WooCommerce_Internal_Api_Schema_Type{}
			mut iife_result_46 := iife_temp_46.nonnull(iife_result_45)
			mut iife_temp_47 := Class_Automattic_WooCommerce_Internal_Api_Schema_Type{}
			mut iife_result_47 := iife_temp_47.boolean()
			mut iife_temp_48 := Class_Automattic_WooCommerce_Internal_Api_Schema_Type{}
			mut iife_result_48 := iife_temp_48.nonnull(iife_result_47)
			mut iife_temp_49 := Class_Automattic_WooCommerce_Internal_Api_Schema_Type{}
			mut iife_result_49 := iife_temp_49.float()
			mut iife_temp_50 := Class_Automattic_WooCommerce_Internal_Api_Schema_Type{}
			mut iife_result_50 := iife_temp_50.nonnull(iife_result_49)
			mut iife_temp_51 := Class_Automattic_WooCommerce_Internal_Api_Schema_Type{}
			mut iife_result_51 := iife_temp_51.float()
			mut iife_temp_52 := Class_Automattic_WooCommerce_Internal_Api_Schema_Type{}
			mut iife_result_52 := iife_temp_52.nonnull(iife_result_51)
			mut iife_temp_53 := Class_Automattic_WooCommerce_Internal_Api_Schema_Type{}
			mut iife_result_53 := iife_temp_53.string()
			mut iife_temp_54 := Class_Automattic_WooCommerce_Internal_Api_Schema_Type{}
			mut iife_result_54 := iife_temp_54.nonnull(iife_result_53)
			mut iife_temp_55 := Class_Automattic_WooCommerce_Internal_Api_Schema_Type{}
			mut iife_result_55 := iife_temp_55.listof(iife_result_54)
			mut iife_temp_56 := Class_Automattic_WooCommerce_Internal_Api_Schema_Type{}
			mut iife_result_56 := iife_temp_56.nonnull(iife_result_55)
			mut iife_temp_57 := Class_Automattic_WooCommerce_Internal_Api_Schema_Type{}
			mut iife_result_57 := iife_temp_57.string()
			mut iife_temp_58 := Class_Automattic_WooCommerce_Internal_Api_Schema_Type{}
			mut iife_result_58 := iife_temp_58.nonnull(iife_result_57)
			mut iife_temp_59 := Class_Automattic_WooCommerce_Internal_Api_Schema_Type{}
			mut iife_result_59 := iife_temp_59.listof(iife_result_58)
			mut iife_temp_60 := Class_Automattic_WooCommerce_Internal_Api_Schema_Type{}
			mut iife_result_60 := iife_temp_60.nonnull(iife_result_59)
			mut iife_temp_61 := Class_Automattic_WooCommerce_Internal_Api_Schema_Type{}
			mut iife_result_61 := iife_temp_61.int()
			mut iife_temp_62 := Class_Automattic_WooCommerce_Internal_Api_Schema_Type{}
			mut iife_result_62 := iife_temp_62.nonnull(iife_result_61)
			return rt.create_array([
				rt.ArrayItem{ key: 'code', val: rt.create_array([
					rt.ArrayItem{ key: 'type', val: iife_result_4 },
					rt.ArrayItem{ key: 'description', val: rt.call_function('__', [
						rt.new_string('The coupon code.'),
						rt.new_string('woocommerce'),
					]) },
				]) },
				rt.ArrayItem{ key: 'description', val: rt.create_array([
					rt.ArrayItem{ key: 'type', val: iife_result_6 },
					rt.ArrayItem{ key: 'description', val: rt.call_function('__', [
						rt.new_string('The coupon description.'),
						rt.new_string('woocommerce'),
					]) },
				]) },
				rt.ArrayItem{ key: 'discount_type', val: rt.create_array([
					rt.ArrayItem{ key: 'type', val: iife_result_8 },
					rt.ArrayItem{ key: 'description', val: rt.call_function('__', [
						rt.new_string('The type of discount.'),
						rt.new_string('woocommerce'),
					]) },
				]) },
				rt.ArrayItem{ key: 'raw_discount_type', val: rt.create_array([
					rt.ArrayItem{ key: 'type', val: iife_result_10 },
					rt.ArrayItem{ key: 'description', val: rt.call_function('__', [
						rt.new_string('The raw discount type as stored in WooCommerce. Useful when discount_type is OTHER (e.g. plugin-added types like recurring_percent or sign_up_fee).'),
						rt.new_string('woocommerce'),
					]) },
				]) },
				rt.ArrayItem{ key: 'amount', val: rt.create_array([
					rt.ArrayItem{ key: 'type', val: iife_result_12 },
					rt.ArrayItem{ key: 'description', val: rt.call_function('__', [
						rt.new_string('The discount amount.'),
						rt.new_string('woocommerce'),
					]) },
				]) },
				rt.ArrayItem{ key: 'status', val: rt.create_array([
					rt.ArrayItem{ key: 'type', val: iife_result_14 },
					rt.ArrayItem{ key: 'description', val: rt.call_function('__', [
						rt.new_string('The coupon status.'),
						rt.new_string('woocommerce'),
					]) },
				]) },
				rt.ArrayItem{ key: 'raw_status', val: rt.create_array([
					rt.ArrayItem{ key: 'type', val: iife_result_16 },
					rt.ArrayItem{ key: 'description', val: rt.call_function('__', [
						rt.new_string('The raw status as stored in WordPress. Useful when status is OTHER (e.g. plugin-added post statuses).'),
						rt.new_string('woocommerce'),
					]) },
				]) },
				rt.ArrayItem{ key: 'date_created', val: rt.create_array([
					rt.ArrayItem{ key: 'type', val: iife_result_17 },
					rt.ArrayItem{ key: 'description', val: rt.call_function('__', [
						rt.new_string('The date the coupon was created.'),
						rt.new_string('woocommerce'),
					]) },
				]) },
				rt.ArrayItem{ key: 'date_modified', val: rt.create_array([
					rt.ArrayItem{ key: 'type', val: iife_result_18 },
					rt.ArrayItem{ key: 'description', val: rt.call_function('__', [
						rt.new_string('The date the coupon was last modified.'),
						rt.new_string('woocommerce'),
					]) },
				]) },
				rt.ArrayItem{ key: 'date_expires', val: rt.create_array([
					rt.ArrayItem{ key: 'type', val: iife_result_19 },
					rt.ArrayItem{ key: 'description', val: rt.call_function('__', [
						rt.new_string('The date the coupon expires.'),
						rt.new_string('woocommerce'),
					]) },
				]) },
				rt.ArrayItem{ key: 'usage_count', val: rt.create_array([
					rt.ArrayItem{ key: 'type', val: iife_result_21 },
					rt.ArrayItem{ key: 'description', val: rt.call_function('__', [
						rt.new_string('The number of times the coupon has been used.'),
						rt.new_string('woocommerce'),
					]) },
				]) },
				rt.ArrayItem{ key: 'individual_use', val: rt.create_array([
					rt.ArrayItem{ key: 'type', val: iife_result_23 },
					rt.ArrayItem{ key: 'description', val: rt.call_function('__', [
						rt.new_string('Whether the coupon can only be used alone.'),
						rt.new_string('woocommerce'),
					]) },
				]) },
				rt.ArrayItem{ key: 'product_ids', val: rt.create_array([
					rt.ArrayItem{ key: 'type', val: iife_result_27 },
					rt.ArrayItem{ key: 'description', val: rt.call_function('__', [
						rt.new_string('Product IDs the coupon can be applied to.'),
						rt.new_string('woocommerce'),
					]) },
				]) },
				rt.ArrayItem{ key: 'excluded_product_ids', val: rt.create_array([
					rt.ArrayItem{ key: 'type', val: iife_result_31 },
					rt.ArrayItem{ key: 'description', val: rt.call_function('__', [
						rt.new_string('Product IDs excluded from the coupon.'),
						rt.new_string('woocommerce'),
					]) },
				]) },
				rt.ArrayItem{ key: 'usage_limit', val: rt.create_array([
					rt.ArrayItem{ key: 'type', val: iife_result_33 },
					rt.ArrayItem{ key: 'description', val: rt.call_function('__', [
						rt.new_string('Maximum number of times the coupon can be used in total.'),
						rt.new_string('woocommerce'),
					]) },
				]) },
				rt.ArrayItem{ key: 'usage_limit_per_user', val: rt.create_array([
					rt.ArrayItem{ key: 'type', val: iife_result_35 },
					rt.ArrayItem{ key: 'description', val: rt.call_function('__', [
						rt.new_string('Maximum number of times the coupon can be used per customer.'),
						rt.new_string('woocommerce'),
					]) },
				]) },
				rt.ArrayItem{ key: 'limit_usage_to_x_items', val: rt.create_array([
					rt.ArrayItem{ key: 'type', val: iife_result_36 },
					rt.ArrayItem{ key: 'description', val: rt.call_function('__', [
						rt.new_string('Maximum number of items the coupon can be applied to.'),
						rt.new_string('woocommerce'),
					]) },
				]) },
				rt.ArrayItem{ key: 'free_shipping', val: rt.create_array([
					rt.ArrayItem{ key: 'type', val: iife_result_38 },
					rt.ArrayItem{ key: 'description', val: rt.call_function('__', [
						rt.new_string('Whether the coupon grants free shipping.'),
						rt.new_string('woocommerce'),
					]) },
				]) },
				rt.ArrayItem{ key: 'product_categories', val: rt.create_array([
					rt.ArrayItem{ key: 'type', val: iife_result_42 },
					rt.ArrayItem{ key: 'description', val: rt.call_function('__', [
						rt.new_string('Product category IDs the coupon applies to.'),
						rt.new_string('woocommerce'),
					]) },
				]) },
				rt.ArrayItem{ key: 'excluded_product_categories', val: rt.create_array([
					rt.ArrayItem{ key: 'type', val: iife_result_46 },
					rt.ArrayItem{ key: 'description', val: rt.call_function('__', [
						rt.new_string('Product category IDs excluded from the coupon.'),
						rt.new_string('woocommerce'),
					]) },
				]) },
				rt.ArrayItem{ key: 'exclude_sale_items', val: rt.create_array([
					rt.ArrayItem{ key: 'type', val: iife_result_48 },
					rt.ArrayItem{ key: 'description', val: rt.call_function('__', [
						rt.new_string('Whether the coupon excludes items on sale.'),
						rt.new_string('woocommerce'),
					]) },
				]) },
				rt.ArrayItem{ key: 'minimum_amount', val: rt.create_array([
					rt.ArrayItem{ key: 'type', val: iife_result_50 },
					rt.ArrayItem{ key: 'description', val: rt.call_function('__', [
						rt.new_string('Minimum order amount required to use the coupon.'),
						rt.new_string('woocommerce'),
					]) },
				]) },
				rt.ArrayItem{ key: 'maximum_amount', val: rt.create_array([
					rt.ArrayItem{ key: 'type', val: iife_result_52 },
					rt.ArrayItem{ key: 'description', val: rt.call_function('__', [
						rt.new_string('Maximum order amount allowed to use the coupon.'),
						rt.new_string('woocommerce'),
					]) },
				]) },
				rt.ArrayItem{ key: 'email_restrictions', val: rt.create_array([
					rt.ArrayItem{ key: 'type', val: iife_result_56 },
					rt.ArrayItem{ key: 'description', val: rt.call_function('__', [
						rt.new_string('Email addresses that can use this coupon.'),
						rt.new_string('woocommerce'),
					]) },
				]) },
				rt.ArrayItem{ key: 'used_by', val: rt.create_array([
					rt.ArrayItem{ key: 'type', val: iife_result_60 },
					rt.ArrayItem{ key: 'description', val: rt.call_function('__', [
						rt.new_string('Email addresses of customers who have used this coupon.'),
						rt.new_string('woocommerce'),
					]) },
				]) },
				rt.ArrayItem{ key: 'id', val: rt.create_array([
					rt.ArrayItem{ key: 'type', val: iife_result_62 },
					rt.ArrayItem{ key: 'description', val: rt.call_function('__', [
						rt.new_string('The unique numeric identifier.'),
						rt.new_string('woocommerce'),
					]) },
				]) },
			])
		}
		rt.set_static_prop('Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Output_Coupon',
			'instance', rt.new_object('Automattic_WooCommerce_Internal_Api_Schema_ObjectType',
			[]string{}, create_automattic_woocommerce_internal_api_schema_objecttype(rt.create_array([
			rt.ArrayItem{ key: 'name', val: 'Coupon' },
			rt.ArrayItem{ key: 'description', val: rt.call_function('__', [
				rt.new_string('Represents a WooCommerce discount coupon.'),
				rt.new_string('woocommerce'),
			]) },
			rt.ArrayItem{ key: 'interfaces', val: rt.new_closure(closure_2_fn) },
			rt.ArrayItem{ key: 'fields', val: rt.new_closure(closure_63_fn) },
		]))))
	}
	return rt.get_static_prop('Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Output_Coupon',
		'instance')
}

struct Class_Automattic_WooCommerce_Internal_Api_Schema_ObjectType {
	rt.PhpObjectBase
}

struct Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Interfaces_ObjectWithId {
	rt.PhpObjectBase
}

struct Class_Automattic_WooCommerce_Internal_Api_Schema_Type {
	rt.PhpObjectBase
}

struct Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Enums_DiscountType {
	rt.PhpObjectBase
}

struct Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Enums_CouponStatus {
	rt.PhpObjectBase
}

struct Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Scalars_DateTime {
	rt.PhpObjectBase
}

fn create_automattic_woocommerce_internal_api_autogenerated_graphqltypes_output_coupon(_args ...rt.PhpVal) &Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Output_Coupon {
	mut obj := &Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Output_Coupon{
		PhpObjectBase: rt.PhpObjectBase{}
	}
	return obj
}

fn create_automattic_woocommerce_internal_api_schema_objecttype(_args ...rt.PhpVal) &Class_Automattic_WooCommerce_Internal_Api_Schema_ObjectType {
	mut obj := &Class_Automattic_WooCommerce_Internal_Api_Schema_ObjectType{
		PhpObjectBase: rt.PhpObjectBase{}
	}
	return obj
}

fn create_automattic_woocommerce_internal_api_autogenerated_graphqltypes_interfaces_objectwithid(_args ...rt.PhpVal) &Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Interfaces_ObjectWithId {
	mut obj := &Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Interfaces_ObjectWithId{
		PhpObjectBase: rt.PhpObjectBase{}
	}
	return obj
}

fn create_automattic_woocommerce_internal_api_schema_type(_args ...rt.PhpVal) &Class_Automattic_WooCommerce_Internal_Api_Schema_Type {
	mut obj := &Class_Automattic_WooCommerce_Internal_Api_Schema_Type{
		PhpObjectBase: rt.PhpObjectBase{}
	}
	return obj
}

fn create_automattic_woocommerce_internal_api_autogenerated_graphqltypes_enums_discounttype(_args ...rt.PhpVal) &Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Enums_DiscountType {
	mut obj := &Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Enums_DiscountType{
		PhpObjectBase: rt.PhpObjectBase{}
	}
	return obj
}

fn create_automattic_woocommerce_internal_api_autogenerated_graphqltypes_enums_couponstatus(_args ...rt.PhpVal) &Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Enums_CouponStatus {
	mut obj := &Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Enums_CouponStatus{
		PhpObjectBase: rt.PhpObjectBase{}
	}
	return obj
}

fn create_automattic_woocommerce_internal_api_autogenerated_graphqltypes_scalars_datetime(_args ...rt.PhpVal) &Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Scalars_DateTime {
	mut obj := &Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Scalars_DateTime{
		PhpObjectBase: rt.PhpObjectBase{}
	}
	return obj
}

fn (mut this Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Output_Coupon) dispatch_method(method_name string, args []rt.PhpVal) ?rt.PhpVal {
	match method_name {
		'get' {
			return Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Output_Coupon.get()
		}
		else {
			return none
		}
	}
}

fn (this &Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Output_Coupon) dispatch_get_prop(prop_name string) ?rt.PhpVal {
	return this.PhpObjectBase.dispatch_get_prop(prop_name)
}

fn (mut this Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Output_Coupon) dispatch_set_prop(prop_name string, val rt.PhpVal) bool {
	return this.PhpObjectBase.dispatch_set_prop(prop_name, val)
}

fn (mut this Class_Automattic_WooCommerce_Internal_Api_Schema_ObjectType) dispatch_method(method_name string, args []rt.PhpVal) ?rt.PhpVal {
	return none
}

fn (this &Class_Automattic_WooCommerce_Internal_Api_Schema_ObjectType) dispatch_get_prop(prop_name string) ?rt.PhpVal {
	return this.PhpObjectBase.dispatch_get_prop(prop_name)
}

fn (mut this Class_Automattic_WooCommerce_Internal_Api_Schema_ObjectType) dispatch_set_prop(prop_name string, val rt.PhpVal) bool {
	return this.PhpObjectBase.dispatch_set_prop(prop_name, val)
}

fn (mut this Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Interfaces_ObjectWithId) dispatch_method(method_name string, args []rt.PhpVal) ?rt.PhpVal {
	return none
}

fn (this &Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Interfaces_ObjectWithId) dispatch_get_prop(prop_name string) ?rt.PhpVal {
	return this.PhpObjectBase.dispatch_get_prop(prop_name)
}

fn (mut this Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Interfaces_ObjectWithId) dispatch_set_prop(prop_name string, val rt.PhpVal) bool {
	return this.PhpObjectBase.dispatch_set_prop(prop_name, val)
}

fn (mut this Class_Automattic_WooCommerce_Internal_Api_Schema_Type) dispatch_method(method_name string, args []rt.PhpVal) ?rt.PhpVal {
	return none
}

fn (this &Class_Automattic_WooCommerce_Internal_Api_Schema_Type) dispatch_get_prop(prop_name string) ?rt.PhpVal {
	return this.PhpObjectBase.dispatch_get_prop(prop_name)
}

fn (mut this Class_Automattic_WooCommerce_Internal_Api_Schema_Type) dispatch_set_prop(prop_name string, val rt.PhpVal) bool {
	return this.PhpObjectBase.dispatch_set_prop(prop_name, val)
}

fn (mut this Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Enums_DiscountType) dispatch_method(method_name string, args []rt.PhpVal) ?rt.PhpVal {
	return none
}

fn (this &Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Enums_DiscountType) dispatch_get_prop(prop_name string) ?rt.PhpVal {
	return this.PhpObjectBase.dispatch_get_prop(prop_name)
}

fn (mut this Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Enums_DiscountType) dispatch_set_prop(prop_name string, val rt.PhpVal) bool {
	return this.PhpObjectBase.dispatch_set_prop(prop_name, val)
}

fn (mut this Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Enums_CouponStatus) dispatch_method(method_name string, args []rt.PhpVal) ?rt.PhpVal {
	return none
}

fn (this &Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Enums_CouponStatus) dispatch_get_prop(prop_name string) ?rt.PhpVal {
	return this.PhpObjectBase.dispatch_get_prop(prop_name)
}

fn (mut this Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Enums_CouponStatus) dispatch_set_prop(prop_name string, val rt.PhpVal) bool {
	return this.PhpObjectBase.dispatch_set_prop(prop_name, val)
}

fn (mut this Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Scalars_DateTime) dispatch_method(method_name string, args []rt.PhpVal) ?rt.PhpVal {
	return none
}

fn (this &Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Scalars_DateTime) dispatch_get_prop(prop_name string) ?rt.PhpVal {
	return this.PhpObjectBase.dispatch_get_prop(prop_name)
}

fn (mut this Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Scalars_DateTime) dispatch_set_prop(prop_name string, val rt.PhpVal) bool {
	return this.PhpObjectBase.dispatch_set_prop(prop_name, val)
}

fn main() {
	defer {
		rt.shutdown()
	}
}
