import rt

struct Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Output_DeleteCouponResult {
	rt.PhpObjectBase
}

fn init_static_automattic_woocommerce_internal_api_autogenerated_graphqltypes_output_deletecouponresult() {
	rt.init_static_prop('Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Output_DeleteCouponResult',
		'instance', rt.new_null())
}

fn Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Output_DeleteCouponResult.get() rt.PhpVal {
	if rt.is_true(rt.identical(rt.new_null(), rt.get_static_prop('Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Output_DeleteCouponResult',
		'instance')))
	{
		closure_5_fn := fn (this_ptr rt.PhpVal, args []rt.PhpVal) rt.PhpVal {
			mut iife_temp_1 := Class_Automattic_WooCommerce_Internal_Api_Schema_Type{}
			mut iife_result_1 := iife_temp_1.int()
			mut iife_temp_2 := Class_Automattic_WooCommerce_Internal_Api_Schema_Type{}
			mut iife_result_2 := iife_temp_2.nonnull(iife_result_1)
			mut iife_temp_3 := Class_Automattic_WooCommerce_Internal_Api_Schema_Type{}
			mut iife_result_3 := iife_temp_3.boolean()
			mut iife_temp_4 := Class_Automattic_WooCommerce_Internal_Api_Schema_Type{}
			mut iife_result_4 := iife_temp_4.nonnull(iife_result_3)
			return rt.create_array([
				rt.ArrayItem{ key: 'id', val: rt.create_array([
					rt.ArrayItem{ key: 'type', val: iife_result_2 },
					rt.ArrayItem{ key: 'description', val: rt.call_function('__', [
						rt.new_string('The ID of the deleted coupon.'),
						rt.new_string('woocommerce'),
					]) },
				]) },
				rt.ArrayItem{ key: 'deleted', val: rt.create_array([
					rt.ArrayItem{ key: 'type', val: iife_result_4 },
					rt.ArrayItem{ key: 'description', val: rt.call_function('__', [
						rt.new_string('Whether the coupon was permanently deleted.'),
						rt.new_string('woocommerce'),
					]) },
				]) },
			])
		}
		rt.set_static_prop('Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Output_DeleteCouponResult',
			'instance', rt.new_object('Automattic_WooCommerce_Internal_Api_Schema_ObjectType',
			[]string{}, create_automattic_woocommerce_internal_api_schema_objecttype(rt.create_array([
			rt.ArrayItem{ key: 'name', val: 'DeleteCouponResult' },
			rt.ArrayItem{ key: 'description', val: rt.call_function('__', [
				rt.new_string('The result of deleting a coupon.'),
				rt.new_string('woocommerce'),
			]) },
			rt.ArrayItem{ key: 'fields', val: rt.new_closure(closure_5_fn) },
		]))))
	}
	return rt.get_static_prop('Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Output_DeleteCouponResult',
		'instance')
}

struct Class_Automattic_WooCommerce_Internal_Api_Schema_ObjectType {
	rt.PhpObjectBase
}

struct Class_Automattic_WooCommerce_Internal_Api_Schema_Type {
	rt.PhpObjectBase
}

fn create_automattic_woocommerce_internal_api_autogenerated_graphqltypes_output_deletecouponresult(_args ...rt.PhpVal) &Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Output_DeleteCouponResult {
	mut obj := &Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Output_DeleteCouponResult{
		PhpObjectBase: rt.PhpObjectBase{}
	}
	return obj
}

fn create_automattic_woocommerce_internal_api_schema_objecttype(_args ...rt.PhpVal) &Class_Automattic_WooCommerce_Internal_Api_Schema_ObjectType {
	mut obj := &Class_Automattic_WooCommerce_Internal_Api_Schema_ObjectType{
		PhpObjectBase: rt.PhpObjectBase{}
	}
	return obj
}

fn create_automattic_woocommerce_internal_api_schema_type(_args ...rt.PhpVal) &Class_Automattic_WooCommerce_Internal_Api_Schema_Type {
	mut obj := &Class_Automattic_WooCommerce_Internal_Api_Schema_Type{
		PhpObjectBase: rt.PhpObjectBase{}
	}
	return obj
}

fn (mut this Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Output_DeleteCouponResult) dispatch_method(method_name string, args []rt.PhpVal) ?rt.PhpVal {
	match method_name {
		'get' {
			return Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Output_DeleteCouponResult.get()
		}
		else {
			return none
		}
	}
}

fn (this &Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Output_DeleteCouponResult) dispatch_get_prop(prop_name string) ?rt.PhpVal {
	return this.PhpObjectBase.dispatch_get_prop(prop_name)
}

fn (mut this Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Output_DeleteCouponResult) dispatch_set_prop(prop_name string, val rt.PhpVal) bool {
	return this.PhpObjectBase.dispatch_set_prop(prop_name, val)
}

fn (mut this Class_Automattic_WooCommerce_Internal_Api_Schema_ObjectType) dispatch_method(method_name string, args []rt.PhpVal) ?rt.PhpVal {
	return none
}

fn (this &Class_Automattic_WooCommerce_Internal_Api_Schema_ObjectType) dispatch_get_prop(prop_name string) ?rt.PhpVal {
	return this.PhpObjectBase.dispatch_get_prop(prop_name)
}

fn (mut this Class_Automattic_WooCommerce_Internal_Api_Schema_ObjectType) dispatch_set_prop(prop_name string, val rt.PhpVal) bool {
	return this.PhpObjectBase.dispatch_set_prop(prop_name, val)
}

fn (mut this Class_Automattic_WooCommerce_Internal_Api_Schema_Type) dispatch_method(method_name string, args []rt.PhpVal) ?rt.PhpVal {
	return none
}

fn (this &Class_Automattic_WooCommerce_Internal_Api_Schema_Type) dispatch_get_prop(prop_name string) ?rt.PhpVal {
	return this.PhpObjectBase.dispatch_get_prop(prop_name)
}

fn (mut this Class_Automattic_WooCommerce_Internal_Api_Schema_Type) dispatch_set_prop(prop_name string, val rt.PhpVal) bool {
	return this.PhpObjectBase.dispatch_set_prop(prop_name, val)
}

fn main() {
	defer {
		rt.shutdown()
	}
}
