import rt

struct Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Output_SimpleProduct {
	rt.PhpObjectBase
}

fn init_static_automattic_woocommerce_internal_api_autogenerated_graphqltypes_output_simpleproduct() {
	rt.init_static_prop('Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Output_SimpleProduct',
		'instance', rt.new_null())
}

fn Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Output_SimpleProduct.get() rt.PhpVal {
	if rt.is_true(rt.identical(rt.new_null(), rt.get_static_prop('Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Output_SimpleProduct',
		'instance')))
	{
		closure_2_fn := fn (this_ptr rt.PhpVal, args []rt.PhpVal) rt.PhpVal {
			mut iife_temp_1 :=
				Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Interfaces_Product{}
			mut iife_result_1 := iife_temp_1.get()
			return rt.create_array([rt.ArrayItem{ key: none, val: iife_result_1 }])
		}
		closure_44_fn := fn (this_ptr rt.PhpVal, args []rt.PhpVal) rt.PhpVal {
			mut iife_temp_3 := Class_Automattic_WooCommerce_Internal_Api_Schema_Type{}
			mut iife_result_3 := iife_temp_3.string()
			mut iife_temp_4 := Class_Automattic_WooCommerce_Internal_Api_Schema_Type{}
			mut iife_result_4 := iife_temp_4.nonnull(iife_result_3)
			mut iife_temp_5 := Class_Automattic_WooCommerce_Internal_Api_Schema_Type{}
			mut iife_result_5 := iife_temp_5.string()
			mut iife_temp_6 := Class_Automattic_WooCommerce_Internal_Api_Schema_Type{}
			mut iife_result_6 := iife_temp_6.nonnull(iife_result_5)
			mut iife_temp_7 := Class_Automattic_WooCommerce_Internal_Api_Schema_Type{}
			mut iife_result_7 := iife_temp_7.string()
			mut iife_temp_8 := Class_Automattic_WooCommerce_Internal_Api_Schema_Type{}
			mut iife_result_8 := iife_temp_8.string()
			mut iife_temp_9 := Class_Automattic_WooCommerce_Internal_Api_Schema_Type{}
			mut iife_result_9 := iife_temp_9.nonnull(iife_result_8)
			mut iife_temp_10 := Class_Automattic_WooCommerce_Internal_Api_Schema_Type{}
			mut iife_result_10 := iife_temp_10.string()
			mut iife_temp_11 := Class_Automattic_WooCommerce_Internal_Api_Schema_Type{}
			mut iife_result_11 := iife_temp_11.nonnull(iife_result_10)
			mut iife_temp_12 :=
				Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Enums_ProductStatus{}
			mut iife_result_12 := iife_temp_12.get()
			mut iife_temp_13 := Class_Automattic_WooCommerce_Internal_Api_Schema_Type{}
			mut iife_result_13 := iife_temp_13.nonnull(iife_result_12)
			mut iife_temp_14 := Class_Automattic_WooCommerce_Internal_Api_Schema_Type{}
			mut iife_result_14 := iife_temp_14.string()
			mut iife_temp_15 := Class_Automattic_WooCommerce_Internal_Api_Schema_Type{}
			mut iife_result_15 := iife_temp_15.nonnull(iife_result_14)
			mut iife_temp_16 :=
				Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Enums_ProductType{}
			mut iife_result_16 := iife_temp_16.get()
			mut iife_temp_17 := Class_Automattic_WooCommerce_Internal_Api_Schema_Type{}
			mut iife_result_17 := iife_temp_17.nonnull(iife_result_16)
			mut iife_temp_18 := Class_Automattic_WooCommerce_Internal_Api_Schema_Type{}
			mut iife_result_18 := iife_temp_18.string()
			mut iife_temp_19 := Class_Automattic_WooCommerce_Internal_Api_Schema_Type{}
			mut iife_result_19 := iife_temp_19.nonnull(iife_result_18)
			mut iife_temp_20 := Class_Automattic_WooCommerce_Internal_Api_Schema_Type{}
			mut iife_result_20 := iife_temp_20.string()
			mut iife_temp_21 := Class_Automattic_WooCommerce_Internal_Api_Schema_Type{}
			mut iife_result_21 := iife_temp_21.boolean()
			mut iife_temp_22 := Class_Automattic_WooCommerce_Internal_Api_Schema_Type{}
			mut iife_result_22 := iife_temp_22.string()
			mut iife_temp_23 := Class_Automattic_WooCommerce_Internal_Api_Schema_Type{}
			mut iife_result_23 := iife_temp_23.boolean()
			mut iife_temp_24 :=
				Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Enums_StockStatus{}
			mut iife_result_24 := iife_temp_24.get()
			mut iife_temp_25 := Class_Automattic_WooCommerce_Internal_Api_Schema_Type{}
			mut iife_result_25 := iife_temp_25.nonnull(iife_result_24)
			mut iife_temp_26 := Class_Automattic_WooCommerce_Internal_Api_Schema_Type{}
			mut iife_result_26 := iife_temp_26.string()
			mut iife_temp_27 := Class_Automattic_WooCommerce_Internal_Api_Schema_Type{}
			mut iife_result_27 := iife_temp_27.nonnull(iife_result_26)
			mut iife_temp_28 := Class_Automattic_WooCommerce_Internal_Api_Schema_Type{}
			mut iife_result_28 := iife_temp_28.int()
			mut iife_temp_29 :=
				Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Output_ProductDimensions{}
			mut iife_result_29 := iife_temp_29.get()
			mut iife_temp_30 :=
				Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Output_ProductImage{}
			mut iife_result_30 := iife_temp_30.get()
			mut iife_temp_31 := Class_Automattic_WooCommerce_Internal_Api_Schema_Type{}
			mut iife_result_31 := iife_temp_31.nonnull(iife_result_30)
			mut iife_temp_32 := Class_Automattic_WooCommerce_Internal_Api_Schema_Type{}
			mut iife_result_32 := iife_temp_32.listof(iife_result_31)
			mut iife_temp_33 := Class_Automattic_WooCommerce_Internal_Api_Schema_Type{}
			mut iife_result_33 := iife_temp_33.nonnull(iife_result_32)
			mut iife_temp_34 :=
				Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Output_ProductAttribute{}
			mut iife_result_34 := iife_temp_34.get()
			mut iife_temp_35 := Class_Automattic_WooCommerce_Internal_Api_Schema_Type{}
			mut iife_result_35 := iife_temp_35.nonnull(iife_result_34)
			mut iife_temp_36 := Class_Automattic_WooCommerce_Internal_Api_Schema_Type{}
			mut iife_result_36 := iife_temp_36.listof(iife_result_35)
			mut iife_temp_37 := Class_Automattic_WooCommerce_Internal_Api_Schema_Type{}
			mut iife_result_37 := iife_temp_37.nonnull(iife_result_36)
			mut iife_temp_38 :=
				Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Pagination_ProductReviewConnection{}
			mut iife_result_38 := iife_temp_38.get()
			mut iife_temp_39 := Class_Automattic_WooCommerce_Internal_Api_Schema_Type{}
			mut iife_result_39 := iife_temp_39.nonnull(iife_result_38)
			mut iife_temp_40 :=
				Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Scalars_DateTime{}
			mut iife_result_40 := iife_temp_40.get()
			mut iife_temp_41 :=
				Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Scalars_DateTime{}
			mut iife_result_41 := iife_temp_41.get()
			mut iife_temp_42 := Class_Automattic_WooCommerce_Internal_Api_Schema_Type{}
			mut iife_result_42 := iife_temp_42.int()
			mut iife_temp_43 := Class_Automattic_WooCommerce_Internal_Api_Schema_Type{}
			mut iife_result_43 := iife_temp_43.nonnull(iife_result_42)
			return rt.create_array([
				rt.ArrayItem{ key: 'name', val: rt.create_array([
					rt.ArrayItem{ key: 'type', val: iife_result_4 },
					rt.ArrayItem{ key: 'description', val: rt.call_function('__', [
						rt.new_string('The product name.'),
						rt.new_string('woocommerce'),
					]) },
				]) },
				rt.ArrayItem{ key: 'slug', val: rt.create_array([
					rt.ArrayItem{ key: 'type', val: iife_result_6 },
					rt.ArrayItem{ key: 'description', val: rt.call_function('__', [
						rt.new_string('The product slug.'),
						rt.new_string('woocommerce'),
					]) },
				]) },
				rt.ArrayItem{ key: 'sku', val: rt.create_array([
					rt.ArrayItem{ key: 'type', val: iife_result_7 },
					rt.ArrayItem{ key: 'description', val: rt.call_function('__', [
						rt.new_string('The product SKU.'),
						rt.new_string('woocommerce'),
					]) },
				]) },
				rt.ArrayItem{ key: 'description', val: rt.create_array([
					rt.ArrayItem{ key: 'type', val: iife_result_9 },
					rt.ArrayItem{ key: 'description', val: rt.call_function('__', [
						rt.new_string('The full product description.'),
						rt.new_string('woocommerce'),
					]) },
				]) },
				rt.ArrayItem{ key: 'short_description', val: rt.create_array([
					rt.ArrayItem{ key: 'type', val: iife_result_11 },
					rt.ArrayItem{ key: 'description', val: rt.call_function('__', [
						rt.new_string('The short product description.'),
						rt.new_string('woocommerce'),
					]) },
					rt.ArrayItem{ key: 'deprecationReason', val: 'Use description instead.' },
				]) },
				rt.ArrayItem{ key: 'status', val: rt.create_array([
					rt.ArrayItem{ key: 'type', val: iife_result_13 },
					rt.ArrayItem{ key: 'description', val: rt.call_function('__', [
						rt.new_string('The product status.'),
						rt.new_string('woocommerce'),
					]) },
				]) },
				rt.ArrayItem{ key: 'raw_status', val: rt.create_array([
					rt.ArrayItem{ key: 'type', val: iife_result_15 },
					rt.ArrayItem{ key: 'description', val: rt.call_function('__', [
						rt.new_string('The raw status as stored in WordPress. Useful when status is OTHER (e.g. plugin-added post statuses).'),
						rt.new_string('woocommerce'),
					]) },
				]) },
				rt.ArrayItem{ key: 'product_type', val: rt.create_array([
					rt.ArrayItem{ key: 'type', val: iife_result_17 },
					rt.ArrayItem{ key: 'description', val: rt.call_function('__', [
						rt.new_string('The product type.'),
						rt.new_string('woocommerce'),
					]) },
				]) },
				rt.ArrayItem{ key: 'raw_product_type', val: rt.create_array([
					rt.ArrayItem{ key: 'type', val: iife_result_19 },
					rt.ArrayItem{ key: 'description', val: rt.call_function('__', [
						rt.new_string('The raw product type as stored in WooCommerce. Useful when product_type is OTHER (e.g. plugin-added types like subscription, bundle).'),
						rt.new_string('woocommerce'),
					]) },
				]) },
				rt.ArrayItem{ key: 'regular_price', val: rt.create_array([
					rt.ArrayItem{ key: 'type', val: iife_result_20 },
					rt.ArrayItem{ key: 'description', val: rt.call_function('__', [
						rt.new_string('The regular price of the product. Null when not set.'),
						rt.new_string('woocommerce'),
					]) },
					rt.ArrayItem{ key: 'args', val: rt.create_array([
						rt.ArrayItem{ key: 'formatted', val: rt.create_array([
							rt.ArrayItem{ key: 'type', val: iife_result_21 },
							rt.ArrayItem{ key: 'defaultValue', val: true },
							rt.ArrayItem{ key: 'description', val: rt.call_function('__', [
								rt.new_string('Whether to apply currency formatting.'),
								rt.new_string('woocommerce'),
							]) },
						]) },
					]) },
				]) },
				rt.ArrayItem{ key: 'sale_price', val: rt.create_array([
					rt.ArrayItem{ key: 'type', val: iife_result_22 },
					rt.ArrayItem{ key: 'description', val: rt.call_function('__', [
						rt.new_string('The sale price of the product.'),
						rt.new_string('woocommerce'),
					]) },
					rt.ArrayItem{ key: 'args', val: rt.create_array([
						rt.ArrayItem{ key: 'formatted', val: rt.create_array([
							rt.ArrayItem{ key: 'type', val: iife_result_23 },
							rt.ArrayItem{ key: 'defaultValue', val: true },
							rt.ArrayItem{ key: 'description', val: rt.call_function('__', [
								rt.new_string('When true, returns price with currency symbol.'),
								rt.new_string('woocommerce'),
							]) },
						]) },
					]) },
				]) },
				rt.ArrayItem{ key: 'stock_status', val: rt.create_array([
					rt.ArrayItem{ key: 'type', val: iife_result_25 },
					rt.ArrayItem{ key: 'description', val: rt.call_function('__', [
						rt.new_string('The stock status of the product.'),
						rt.new_string('woocommerce'),
					]) },
				]) },
				rt.ArrayItem{ key: 'raw_stock_status', val: rt.create_array([
					rt.ArrayItem{ key: 'type', val: iife_result_27 },
					rt.ArrayItem{ key: 'description', val: rt.call_function('__', [
						rt.new_string('The raw stock status as stored in WooCommerce. Useful when stock_status is OTHER (e.g. plugin-added statuses).'),
						rt.new_string('woocommerce'),
					]) },
				]) },
				rt.ArrayItem{ key: 'stock_quantity', val: rt.create_array([
					rt.ArrayItem{ key: 'type', val: iife_result_28 },
					rt.ArrayItem{ key: 'description', val: rt.call_function('__', [
						rt.new_string('The number of items in stock.'),
						rt.new_string('woocommerce'),
					]) },
				]) },
				rt.ArrayItem{ key: 'dimensions', val: rt.create_array([
					rt.ArrayItem{ key: 'type', val: iife_result_29 },
					rt.ArrayItem{ key: 'description', val: rt.call_function('__', [
						rt.new_string('The product dimensions.'),
						rt.new_string('woocommerce'),
					]) },
				]) },
				rt.ArrayItem{ key: 'images', val: rt.create_array([
					rt.ArrayItem{ key: 'type', val: iife_result_33 },
					rt.ArrayItem{ key: 'description', val: rt.call_function('__', [
						rt.new_string('The product images.'),
						rt.new_string('woocommerce'),
					]) },
				]) },
				rt.ArrayItem{ key: 'attributes', val: rt.create_array([
					rt.ArrayItem{ key: 'type', val: iife_result_37 },
					rt.ArrayItem{ key: 'description', val: rt.call_function('__', [
						rt.new_string('The product attributes.'),
						rt.new_string('woocommerce'),
					]) },
				]) },
				rt.ArrayItem{ key: 'reviews', val: rt.create_array([
					rt.ArrayItem{ key: 'type', val: iife_result_39 },
					rt.ArrayItem{ key: 'description', val: rt.call_function('__', [
						rt.new_string('Customer reviews for this product.'),
						rt.new_string('woocommerce'),
					]) },
				]) },
				rt.ArrayItem{ key: 'date_created', val: rt.create_array([
					rt.ArrayItem{ key: 'type', val: iife_result_40 },
					rt.ArrayItem{ key: 'description', val: rt.call_function('__', [
						rt.new_string('The date the product was created.'),
						rt.new_string('woocommerce'),
					]) },
				]) },
				rt.ArrayItem{ key: 'date_modified', val: rt.create_array([
					rt.ArrayItem{ key: 'type', val: iife_result_41 },
					rt.ArrayItem{ key: 'description', val: rt.call_function('__', [
						rt.new_string('The date the product was last modified.'),
						rt.new_string('woocommerce'),
					]) },
				]) },
				rt.ArrayItem{ key: 'id', val: rt.create_array([
					rt.ArrayItem{ key: 'type', val: iife_result_43 },
					rt.ArrayItem{ key: 'description', val: rt.call_function('__', [
						rt.new_string('The unique numeric identifier.'),
						rt.new_string('woocommerce'),
					]) },
				]) },
			])
		}
		rt.set_static_prop('Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Output_SimpleProduct',
			'instance', rt.new_object('Automattic_WooCommerce_Internal_Api_Schema_ObjectType',
			[]string{}, create_automattic_woocommerce_internal_api_schema_objecttype(rt.create_array([
			rt.ArrayItem{ key: 'name', val: 'SimpleProduct' },
			rt.ArrayItem{ key: 'description', val: rt.call_function('__', [
				rt.new_string('A simple WooCommerce product.'),
				rt.new_string('woocommerce'),
			]) },
			rt.ArrayItem{ key: 'interfaces', val: rt.new_closure(closure_2_fn) },
			rt.ArrayItem{ key: 'fields', val: rt.new_closure(closure_44_fn) },
		]))))
	}
	return rt.get_static_prop('Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Output_SimpleProduct',
		'instance')
}

struct Class_Automattic_WooCommerce_Internal_Api_Schema_ObjectType {
	rt.PhpObjectBase
}

struct Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Interfaces_Product {
	rt.PhpObjectBase
}

struct Class_Automattic_WooCommerce_Internal_Api_Schema_Type {
	rt.PhpObjectBase
}

struct Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Enums_ProductStatus {
	rt.PhpObjectBase
}

struct Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Enums_ProductType {
	rt.PhpObjectBase
}

struct Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Enums_StockStatus {
	rt.PhpObjectBase
}

struct Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Output_ProductDimensions {
	rt.PhpObjectBase
}

struct Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Output_ProductImage {
	rt.PhpObjectBase
}

struct Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Output_ProductAttribute {
	rt.PhpObjectBase
}

struct Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Pagination_ProductReviewConnection {
	rt.PhpObjectBase
}

struct Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Scalars_DateTime {
	rt.PhpObjectBase
}

fn create_automattic_woocommerce_internal_api_autogenerated_graphqltypes_output_simpleproduct(_args ...rt.PhpVal) &Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Output_SimpleProduct {
	mut obj := &Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Output_SimpleProduct{
		PhpObjectBase: rt.PhpObjectBase{}
	}
	return obj
}

fn create_automattic_woocommerce_internal_api_schema_objecttype(_args ...rt.PhpVal) &Class_Automattic_WooCommerce_Internal_Api_Schema_ObjectType {
	mut obj := &Class_Automattic_WooCommerce_Internal_Api_Schema_ObjectType{
		PhpObjectBase: rt.PhpObjectBase{}
	}
	return obj
}

fn create_automattic_woocommerce_internal_api_autogenerated_graphqltypes_interfaces_product(_args ...rt.PhpVal) &Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Interfaces_Product {
	mut obj := &Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Interfaces_Product{
		PhpObjectBase: rt.PhpObjectBase{}
	}
	return obj
}

fn create_automattic_woocommerce_internal_api_schema_type(_args ...rt.PhpVal) &Class_Automattic_WooCommerce_Internal_Api_Schema_Type {
	mut obj := &Class_Automattic_WooCommerce_Internal_Api_Schema_Type{
		PhpObjectBase: rt.PhpObjectBase{}
	}
	return obj
}

fn create_automattic_woocommerce_internal_api_autogenerated_graphqltypes_enums_productstatus(_args ...rt.PhpVal) &Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Enums_ProductStatus {
	mut obj := &Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Enums_ProductStatus{
		PhpObjectBase: rt.PhpObjectBase{}
	}
	return obj
}

fn create_automattic_woocommerce_internal_api_autogenerated_graphqltypes_enums_producttype(_args ...rt.PhpVal) &Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Enums_ProductType {
	mut obj := &Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Enums_ProductType{
		PhpObjectBase: rt.PhpObjectBase{}
	}
	return obj
}

fn create_automattic_woocommerce_internal_api_autogenerated_graphqltypes_enums_stockstatus(_args ...rt.PhpVal) &Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Enums_StockStatus {
	mut obj := &Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Enums_StockStatus{
		PhpObjectBase: rt.PhpObjectBase{}
	}
	return obj
}

fn create_automattic_woocommerce_internal_api_autogenerated_graphqltypes_output_productdimensions(_args ...rt.PhpVal) &Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Output_ProductDimensions {
	mut obj := &Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Output_ProductDimensions{
		PhpObjectBase: rt.PhpObjectBase{}
	}
	return obj
}

fn create_automattic_woocommerce_internal_api_autogenerated_graphqltypes_output_productimage(_args ...rt.PhpVal) &Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Output_ProductImage {
	mut obj := &Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Output_ProductImage{
		PhpObjectBase: rt.PhpObjectBase{}
	}
	return obj
}

fn create_automattic_woocommerce_internal_api_autogenerated_graphqltypes_output_productattribute(_args ...rt.PhpVal) &Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Output_ProductAttribute {
	mut obj := &Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Output_ProductAttribute{
		PhpObjectBase: rt.PhpObjectBase{}
	}
	return obj
}

fn create_automattic_woocommerce_internal_api_autogenerated_graphqltypes_pagination_productreviewconnection(_args ...rt.PhpVal) &Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Pagination_ProductReviewConnection {
	mut obj := &Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Pagination_ProductReviewConnection{
		PhpObjectBase: rt.PhpObjectBase{}
	}
	return obj
}

fn create_automattic_woocommerce_internal_api_autogenerated_graphqltypes_scalars_datetime(_args ...rt.PhpVal) &Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Scalars_DateTime {
	mut obj := &Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Scalars_DateTime{
		PhpObjectBase: rt.PhpObjectBase{}
	}
	return obj
}

fn (mut this Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Output_SimpleProduct) dispatch_method(method_name string, args []rt.PhpVal) ?rt.PhpVal {
	match method_name {
		'get' {
			return Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Output_SimpleProduct.get()
		}
		else {
			return none
		}
	}
}

fn (this &Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Output_SimpleProduct) dispatch_get_prop(prop_name string) ?rt.PhpVal {
	return this.PhpObjectBase.dispatch_get_prop(prop_name)
}

fn (mut this Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Output_SimpleProduct) dispatch_set_prop(prop_name string, val rt.PhpVal) bool {
	return this.PhpObjectBase.dispatch_set_prop(prop_name, val)
}

fn (mut this Class_Automattic_WooCommerce_Internal_Api_Schema_ObjectType) dispatch_method(method_name string, args []rt.PhpVal) ?rt.PhpVal {
	return none
}

fn (this &Class_Automattic_WooCommerce_Internal_Api_Schema_ObjectType) dispatch_get_prop(prop_name string) ?rt.PhpVal {
	return this.PhpObjectBase.dispatch_get_prop(prop_name)
}

fn (mut this Class_Automattic_WooCommerce_Internal_Api_Schema_ObjectType) dispatch_set_prop(prop_name string, val rt.PhpVal) bool {
	return this.PhpObjectBase.dispatch_set_prop(prop_name, val)
}

fn (mut this Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Interfaces_Product) dispatch_method(method_name string, args []rt.PhpVal) ?rt.PhpVal {
	return none
}

fn (this &Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Interfaces_Product) dispatch_get_prop(prop_name string) ?rt.PhpVal {
	return this.PhpObjectBase.dispatch_get_prop(prop_name)
}

fn (mut this Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Interfaces_Product) dispatch_set_prop(prop_name string, val rt.PhpVal) bool {
	return this.PhpObjectBase.dispatch_set_prop(prop_name, val)
}

fn (mut this Class_Automattic_WooCommerce_Internal_Api_Schema_Type) dispatch_method(method_name string, args []rt.PhpVal) ?rt.PhpVal {
	return none
}

fn (this &Class_Automattic_WooCommerce_Internal_Api_Schema_Type) dispatch_get_prop(prop_name string) ?rt.PhpVal {
	return this.PhpObjectBase.dispatch_get_prop(prop_name)
}

fn (mut this Class_Automattic_WooCommerce_Internal_Api_Schema_Type) dispatch_set_prop(prop_name string, val rt.PhpVal) bool {
	return this.PhpObjectBase.dispatch_set_prop(prop_name, val)
}

fn (mut this Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Enums_ProductStatus) dispatch_method(method_name string, args []rt.PhpVal) ?rt.PhpVal {
	return none
}

fn (this &Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Enums_ProductStatus) dispatch_get_prop(prop_name string) ?rt.PhpVal {
	return this.PhpObjectBase.dispatch_get_prop(prop_name)
}

fn (mut this Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Enums_ProductStatus) dispatch_set_prop(prop_name string, val rt.PhpVal) bool {
	return this.PhpObjectBase.dispatch_set_prop(prop_name, val)
}

fn (mut this Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Enums_ProductType) dispatch_method(method_name string, args []rt.PhpVal) ?rt.PhpVal {
	return none
}

fn (this &Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Enums_ProductType) dispatch_get_prop(prop_name string) ?rt.PhpVal {
	return this.PhpObjectBase.dispatch_get_prop(prop_name)
}

fn (mut this Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Enums_ProductType) dispatch_set_prop(prop_name string, val rt.PhpVal) bool {
	return this.PhpObjectBase.dispatch_set_prop(prop_name, val)
}

fn (mut this Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Enums_StockStatus) dispatch_method(method_name string, args []rt.PhpVal) ?rt.PhpVal {
	return none
}

fn (this &Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Enums_StockStatus) dispatch_get_prop(prop_name string) ?rt.PhpVal {
	return this.PhpObjectBase.dispatch_get_prop(prop_name)
}

fn (mut this Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Enums_StockStatus) dispatch_set_prop(prop_name string, val rt.PhpVal) bool {
	return this.PhpObjectBase.dispatch_set_prop(prop_name, val)
}

fn (mut this Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Output_ProductDimensions) dispatch_method(method_name string, args []rt.PhpVal) ?rt.PhpVal {
	return none
}

fn (this &Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Output_ProductDimensions) dispatch_get_prop(prop_name string) ?rt.PhpVal {
	return this.PhpObjectBase.dispatch_get_prop(prop_name)
}

fn (mut this Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Output_ProductDimensions) dispatch_set_prop(prop_name string, val rt.PhpVal) bool {
	return this.PhpObjectBase.dispatch_set_prop(prop_name, val)
}

fn (mut this Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Output_ProductImage) dispatch_method(method_name string, args []rt.PhpVal) ?rt.PhpVal {
	return none
}

fn (this &Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Output_ProductImage) dispatch_get_prop(prop_name string) ?rt.PhpVal {
	return this.PhpObjectBase.dispatch_get_prop(prop_name)
}

fn (mut this Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Output_ProductImage) dispatch_set_prop(prop_name string, val rt.PhpVal) bool {
	return this.PhpObjectBase.dispatch_set_prop(prop_name, val)
}

fn (mut this Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Output_ProductAttribute) dispatch_method(method_name string, args []rt.PhpVal) ?rt.PhpVal {
	return none
}

fn (this &Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Output_ProductAttribute) dispatch_get_prop(prop_name string) ?rt.PhpVal {
	return this.PhpObjectBase.dispatch_get_prop(prop_name)
}

fn (mut this Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Output_ProductAttribute) dispatch_set_prop(prop_name string, val rt.PhpVal) bool {
	return this.PhpObjectBase.dispatch_set_prop(prop_name, val)
}

fn (mut this Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Pagination_ProductReviewConnection) dispatch_method(method_name string, args []rt.PhpVal) ?rt.PhpVal {
	return none
}

fn (this &Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Pagination_ProductReviewConnection) dispatch_get_prop(prop_name string) ?rt.PhpVal {
	return this.PhpObjectBase.dispatch_get_prop(prop_name)
}

fn (mut this Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Pagination_ProductReviewConnection) dispatch_set_prop(prop_name string, val rt.PhpVal) bool {
	return this.PhpObjectBase.dispatch_set_prop(prop_name, val)
}

fn (mut this Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Scalars_DateTime) dispatch_method(method_name string, args []rt.PhpVal) ?rt.PhpVal {
	return none
}

fn (this &Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Scalars_DateTime) dispatch_get_prop(prop_name string) ?rt.PhpVal {
	return this.PhpObjectBase.dispatch_get_prop(prop_name)
}

fn (mut this Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Scalars_DateTime) dispatch_set_prop(prop_name string, val rt.PhpVal) bool {
	return this.PhpObjectBase.dispatch_set_prop(prop_name, val)
}

fn main() {
	defer {
		rt.shutdown()
	}
}
