[server]
host = "127.0.0.1"
port = 19892

[files]
pid_file = "/tmp/vhttpd_vslim_websocket_dispatch.pid"
event_log = "/tmp/vhttpd_vslim_websocket_dispatch.events.ndjson"

[worker]
autostart = true
read_timeout_ms = 60000
pool_size = 1
websocket_dispatch = true
socket = "/tmp/vslim_websocket_dispatch_worker.sock"
cmd = "php -d extension=/Users/guweigang/Source/vphpx/vslim/vslim.so /Users/guweigang/Source/vhttpd/php/package/bin/php-worker"

[worker.env]
VHTTPD_APP = "/Users/guweigang/Source/vphpx/vslim/examples/websocket_app.php"

[admin]
host = "127.0.0.1"
port = 19992
token = ""

[assets]
enabled = true
prefix = "/assets"
root = "/Users/guweigang/Source/vphpx/vslim/examples/public"
cache_control = "public, max-age=3600"
