import rt

struct Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Scalars_DateTime {
	rt.PhpObjectBase
}

fn init_static_automattic_woocommerce_internal_api_autogenerated_graphqltypes_scalars_datetime() {
	rt.init_static_prop('Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Scalars_DateTime',
		'instance', rt.new_null())
}

fn Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Scalars_DateTime.get() rt.PhpVal {
	mut var_value := rt.new_null()
	if rt.is_true(rt.identical(rt.new_null(), rt.get_static_prop('Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Scalars_DateTime',
		'instance')))
	{
		closure_2_fn := fn (this_ptr rt.PhpVal, args []rt.PhpVal) rt.PhpVal {
			mut var_value := if args.len > 0 { args[0].clone() } else { rt.new_null() }
			mut iife_temp_1 := Class_Automattic_WooCommerce_Api_Scalars_DateTime{}
			mut iife_result_1 := iife_temp_1.serialize(var_value.clone())
			return iife_result_1
		}
		closure_4_fn := fn (this_ptr rt.PhpVal, args []rt.PhpVal) rt.PhpVal {
			mut var_value := if args.len > 0 { args[0].clone() } else { rt.new_null() }
			mut iife_temp_3 := Class_Automattic_WooCommerce_Api_Scalars_DateTime{}
			mut iife_result_3 := iife_temp_3.parse(var_value.clone())
			return iife_result_3
			unsafe {
				goto end_label_1
			}
			catch_label_1:
			mut var_e_1 := rt.get_and_clear_exception()
			if rt.instance_of(var_e_1,
				'Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Scalars_InvalidArgumentException')
			{
				mut var_e := var_e_1.clone()
				rt.throw_exception(rt.new_object('Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Scalars_Automattic_WooCommerce_Internal_Api_Schema_Error',
					[]string{}, create_automattic_woocommerce_internal_api_autogenerated_graphqltypes_scalars_automattic_woocommerce_internal_api_schema_error(rt.call_method(var_e,
					'getMessage', []rt.PhpVal{}))))
				unsafe {
					goto end_label_1
				}
			} else {
				rt.throw_exception(var_e_1)
				unsafe {
					goto end_label_1
				}
			}

			end_label_1:
			return rt.new_null()
		}
		closure_6_fn := fn (this_ptr rt.PhpVal, args []rt.PhpVal) rt.PhpVal {
			mut var_value_node := if args.len > 0 { args[0].clone() } else { rt.new_null() }
			mut var_variables := if args.len > 1 { args[1].clone() } else { rt.new_null() }
			if rt.is_true(rt.new_bool(rt.instance_of(var_value_node,
				'Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Scalars_Automattic_WooCommerce_Internal_Api_Schema_AST_StringValueNode')))
			{
				mut iife_temp_5 := Class_Automattic_WooCommerce_Api_Scalars_DateTime{}
				mut iife_result_5 := iife_temp_5.parse(rt.get_property(var_value_node, 'value'))
				return iife_result_5
				unsafe {
					goto end_label_2
				}
				catch_label_2:
				mut var_e_2 := rt.get_and_clear_exception()
				if rt.instance_of(var_e_2,
					'Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Scalars_InvalidArgumentException')
				{
					mut var_e := var_e_2.clone()
					rt.throw_exception(rt.new_object('Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Scalars_Automattic_WooCommerce_Internal_Api_Schema_Error',
						[]string{}, create_automattic_woocommerce_internal_api_autogenerated_graphqltypes_scalars_automattic_woocommerce_internal_api_schema_error(rt.call_method(var_e,
						'getMessage', []rt.PhpVal{}))))
					unsafe {
						goto end_label_2
					}
				} else {
					rt.throw_exception(var_e_2)
					unsafe {
						goto end_label_2
					}
				}

				end_label_2:
			}
			rt.throw_exception(rt.new_object('Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Scalars_Automattic_WooCommerce_Internal_Api_Schema_Error',
				[]string{}, create_automattic_woocommerce_internal_api_autogenerated_graphqltypes_scalars_automattic_woocommerce_internal_api_schema_error(
				'DateTime must be a string, got: ' + (rt.get_property(var_value_node, 'kind')).str())))
			return rt.new_null()
		}
		rt.set_static_prop('Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Scalars_DateTime',
			'instance', rt.new_object('Automattic_WooCommerce_Internal_Api_Schema_CustomScalarType',
			[]string{}, create_automattic_woocommerce_internal_api_schema_customscalartype(rt.create_array([
			rt.ArrayItem{ key: 'name', val: 'DateTime' },
			rt.ArrayItem{ key: 'description', val: rt.call_function('__', [
				rt.new_string('An ISO 8601 encoded date and time string.'),
				rt.new_string('woocommerce'),
			]) },
			rt.ArrayItem{ key: 'serialize', val: rt.new_closure(closure_2_fn) },
			rt.ArrayItem{ key: 'parseValue', val: rt.new_closure(closure_4_fn) },
			rt.ArrayItem{ key: 'parseLiteral', val: rt.new_closure(closure_6_fn) },
		]))))
	}
	return rt.get_static_prop('Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Scalars_DateTime',
		'instance')
}

struct Class_Automattic_WooCommerce_Internal_Api_Schema_CustomScalarType {
	rt.PhpObjectBase
}

struct Class_Automattic_WooCommerce_Api_Scalars_DateTime {
	rt.PhpObjectBase
}

struct Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Scalars_Automattic_WooCommerce_Internal_Api_Schema_Error {
	rt.PhpObjectBase
}

fn create_automattic_woocommerce_internal_api_autogenerated_graphqltypes_scalars_datetime(_args ...rt.PhpVal) &Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Scalars_DateTime {
	mut obj := &Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Scalars_DateTime{
		PhpObjectBase: rt.PhpObjectBase{}
	}
	return obj
}

fn create_automattic_woocommerce_internal_api_schema_customscalartype(_args ...rt.PhpVal) &Class_Automattic_WooCommerce_Internal_Api_Schema_CustomScalarType {
	mut obj := &Class_Automattic_WooCommerce_Internal_Api_Schema_CustomScalarType{
		PhpObjectBase: rt.PhpObjectBase{}
	}
	return obj
}

fn create_automattic_woocommerce_api_scalars_datetime(_args ...rt.PhpVal) &Class_Automattic_WooCommerce_Api_Scalars_DateTime {
	mut obj := &Class_Automattic_WooCommerce_Api_Scalars_DateTime{
		PhpObjectBase: rt.PhpObjectBase{}
	}
	return obj
}

fn create_automattic_woocommerce_internal_api_autogenerated_graphqltypes_scalars_automattic_woocommerce_internal_api_schema_error(_args ...rt.PhpVal) &Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Scalars_Automattic_WooCommerce_Internal_Api_Schema_Error {
	mut obj := &Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Scalars_Automattic_WooCommerce_Internal_Api_Schema_Error{
		PhpObjectBase: rt.PhpObjectBase{}
	}
	return obj
}

fn (mut this Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Scalars_DateTime) dispatch_method(method_name string, args []rt.PhpVal) ?rt.PhpVal {
	match method_name {
		'get' {
			return Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Scalars_DateTime.get()
		}
		else {
			return none
		}
	}
}

fn (this &Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Scalars_DateTime) dispatch_get_prop(prop_name string) ?rt.PhpVal {
	return this.PhpObjectBase.dispatch_get_prop(prop_name)
}

fn (mut this Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Scalars_DateTime) dispatch_set_prop(prop_name string, val rt.PhpVal) bool {
	return this.PhpObjectBase.dispatch_set_prop(prop_name, val)
}

fn (mut this Class_Automattic_WooCommerce_Internal_Api_Schema_CustomScalarType) dispatch_method(method_name string, args []rt.PhpVal) ?rt.PhpVal {
	return none
}

fn (this &Class_Automattic_WooCommerce_Internal_Api_Schema_CustomScalarType) dispatch_get_prop(prop_name string) ?rt.PhpVal {
	return this.PhpObjectBase.dispatch_get_prop(prop_name)
}

fn (mut this Class_Automattic_WooCommerce_Internal_Api_Schema_CustomScalarType) dispatch_set_prop(prop_name string, val rt.PhpVal) bool {
	return this.PhpObjectBase.dispatch_set_prop(prop_name, val)
}

fn (mut this Class_Automattic_WooCommerce_Api_Scalars_DateTime) dispatch_method(method_name string, args []rt.PhpVal) ?rt.PhpVal {
	return none
}

fn (this &Class_Automattic_WooCommerce_Api_Scalars_DateTime) dispatch_get_prop(prop_name string) ?rt.PhpVal {
	return this.PhpObjectBase.dispatch_get_prop(prop_name)
}

fn (mut this Class_Automattic_WooCommerce_Api_Scalars_DateTime) dispatch_set_prop(prop_name string, val rt.PhpVal) bool {
	return this.PhpObjectBase.dispatch_set_prop(prop_name, val)
}

fn (mut this Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Scalars_Automattic_WooCommerce_Internal_Api_Schema_Error) dispatch_method(method_name string, args []rt.PhpVal) ?rt.PhpVal {
	return none
}

fn (this &Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Scalars_Automattic_WooCommerce_Internal_Api_Schema_Error) dispatch_get_prop(prop_name string) ?rt.PhpVal {
	return this.PhpObjectBase.dispatch_get_prop(prop_name)
}

fn (mut this Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Scalars_Automattic_WooCommerce_Internal_Api_Schema_Error) dispatch_set_prop(prop_name string, val rt.PhpVal) bool {
	return this.PhpObjectBase.dispatch_set_prop(prop_name, val)
}

fn main() {
	defer {
		rt.shutdown()
	}
}
