#!/usr/bin/env python3
import os
import sys
import json
import subprocess
import glob

def main():
    # 确定路径
    script_dir = os.path.dirname(os.path.abspath(__file__))
    php2v_dir = os.path.dirname(script_dir)
    
    fixtures_dir = os.path.join(php2v_dir, 'tests', 'fixtures')
    parser_php = os.path.join(script_dir, 'parser.php')
    playground_dir = os.path.join(php2v_dir, 'playground')
    output_js = os.path.join(playground_dir, 'data.js')
    
    if not os.path.exists(fixtures_dir):
        print(f"Error: Fixtures directory not found: {fixtures_dir}")
        sys.exit(1)
        
    if not os.path.exists(parser_php):
        print(f"Error: parser.php not found: {parser_php}")
        sys.exit(1)
        
    # 获取所有 *.php 文件
    php_files = glob.glob(os.path.join(fixtures_dir, '*.php'))
    php_files.sort() # 按文件名排序
    
    playground_data = []
    
    for php_path in php_files:
        filename = os.path.basename(php_path)
        name_without_ext = os.path.splitext(filename)[0]
        
        # 1. 读取 PHP 源码
        try:
            with open(php_path, 'r', encoding='utf-8') as f:
                php_code = f.read()
        except Exception as e:
            print(f"Warning: Failed to read PHP file {filename}: {e}")
            continue
            
        # 2. 调用 parser.php 提取 AST JSON
        print(f"Parsing AST for {filename}...")
        try:
            res = subprocess.run(
                ['php', parser_php, php_path],
                capture_output=True,
                text=True,
                check=True
            )
            ast_json = json.loads(res.stdout)
        except subprocess.CalledProcessError as e:
            print(f"Error: Failed to parse AST for {filename}: {e.stderr}")
            ast_json = {"error": f"PHP Parser error: {e.stderr.strip()}"}
        except Exception as e:
            print(f"Error: Failed to parse AST JSON for {filename}: {e}")
            ast_json = {"error": f"Failed to parse JSON: {str(e)}"}
            
        # 3. 读取对应的 V 源码
        v_path = os.path.join(fixtures_dir, name_without_ext + '.v')
        v_code = ""
        if os.path.exists(v_path):
            try:
                with open(v_path, 'r', encoding='utf-8') as f:
                    v_code = f.read()
            except Exception as e:
                print(f"Warning: Failed to read V file {v_path}: {e}")
        else:
            # 如果不存在，尝试用 php2v 编译（若有 php2v 可执行文件）
            php2v_bin = os.path.join(php2v_dir, 'php2v')
            if os.path.exists(php2v_bin):
                print(f"Compiling {filename} to generate V code...")
                try:
                    subprocess.run(
                        [php2v_bin, 'compile', php_path, '-o', v_path],
                        capture_output=True,
                        text=True,
                        check=True
                    )
                    with open(v_path, 'r', encoding='utf-8') as f:
                        v_code = f.read()
                    # 编译后可以删掉临时生成的，或者保留都行。既然是测试夹具，可能原来就有的就不管，原来没有的删除。
                    # 这里如果是自动生成的，我们就读取后删除它，防止污染 fixtures 目录
                    os.remove(v_path)
                except Exception as e:
                    print(f"Warning: Failed to compile {filename} to V: {e}")
                    v_code = f"// Transpilation failed:\n// {e}"
            else:
                v_code = "// V target code not found. Please compile it first."
                
        # 提取分类/标题名称
        # 例如 "01_echo" 转换为 "01 Echo" 或者保持 "01_echo"
        title = name_without_ext.replace('_', ' ').title()
        
        playground_data.append({
            "key": name_without_ext,
            "title": title,
            "filename": filename,
            "php": php_code,
            "v": v_code,
            "ast": ast_json
        })
        
    # 确保输出目录存在
    os.makedirs(playground_dir, exist_ok=True)
    
    # 写入 data.js
    try:
        with open(output_js, 'w', encoding='utf-8') as f:
            f.write("// Auto-generated by generate_playground_data.py. Do not edit manually.\n")
            f.write("window.PLAYGROUND_DATA = ")
            json.dump(playground_data, f, indent=2, ensure_ascii=False)
            f.write(";\n")
        print(f"🎉 Successfully generated {output_js} with {len(playground_data)} items!")
    except Exception as e:
        print(f"Error: Failed to write to {output_js}: {e}")
        sys.exit(1)

if __name__ == '__main__':
    main()
