<?php
declare(strict_types=1);

main($argv);

function main(array $argv): void
{
    $options = parse_options($argv);
    if ($options['help']) {
        fwrite(STDOUT, usage());
        return;
    }

    $root = dirname(__DIR__);
    $defaultExtension = $root . '/vslim.so';
    $extensionPath = $options['extension'] ?? $defaultExtension;
    $outputPath = $options['output'] ?? ($root . '/stubs/vslim.php');
    $stdout = $options['stdout'];

    if (!is_file($extensionPath)) {
        fail("vslim extension not found: {$extensionPath}");
    }

    if (!$options['no_reexec']) {
        exit(reexec_with_extension($argv, $extensionPath));
    }

    if (!extension_loaded('vslim')) {
        fail("vslim extension is not loaded; tried {$extensionPath}");
    }

    $stub = generate_stub(new ReflectionExtension('vslim'));
    if ($stdout) {
        fwrite(STDOUT, $stub);
        return;
    }

    $dir = dirname($outputPath);
    if (!is_dir($dir) && !mkdir($dir, 0777, true) && !is_dir($dir)) {
        fail("failed to create stub directory: {$dir}");
    }

    if (file_put_contents($outputPath, $stub) === false) {
        fail("failed to write stub file: {$outputPath}");
    }

    fwrite(STDOUT, "Generated {$outputPath}\n");
}

/**
 * @return array{extension:?string, output:?string, stdout:bool, help:bool, no_reexec:bool}
 */
function parse_options(array $argv): array
{
    $options = [
        'extension' => null,
        'output' => null,
        'stdout' => false,
        'help' => false,
        'no_reexec' => false,
    ];

    for ($i = 1; $i < count($argv); $i++) {
        $arg = $argv[$i];
        if ($arg === '--help' || $arg === '-h') {
            $options['help'] = true;
            continue;
        }
        if ($arg === '--stdout') {
            $options['stdout'] = true;
            continue;
        }
        if ($arg === '--no-reexec') {
            $options['no_reexec'] = true;
            continue;
        }
        if (str_starts_with($arg, '--extension=')) {
            $options['extension'] = substr($arg, strlen('--extension='));
            continue;
        }
        if ($arg === '--extension') {
            $options['extension'] = $argv[++$i] ?? fail('missing value for --extension');
            continue;
        }
        if (str_starts_with($arg, '--output=')) {
            $options['output'] = substr($arg, strlen('--output='));
            continue;
        }
        if ($arg === '--output') {
            $options['output'] = $argv[++$i] ?? fail('missing value for --output');
            continue;
        }
        fail("unknown argument: {$arg}");
    }

    return $options;
}

function usage(): string
{
    return <<<TXT
Usage:
  php scripts/generate_stubs.php [--extension=/path/to/vslim.so] [--output=/path/to/vslim.php]
  php scripts/generate_stubs.php --stdout

Options:
  --extension   Path to the compiled vslim extension. Defaults to vslim/vslim.so.
  --output      Output path for the generated stub file. Defaults to vslim/stubs/vslim.php.
  --stdout      Print the generated stubs to stdout instead of writing a file.
  --help, -h    Show this help message.

TXT;
}

function reexec_with_extension(array $argv, string $extensionPath): int
{
    $command = [
        PHP_BINARY,
        '-n',
        '-d',
        'extension=' . $extensionPath,
        __FILE__,
        '--no-reexec',
    ];

    for ($i = 1; $i < count($argv); $i++) {
        if ($argv[$i] === '--no-reexec') {
            continue;
        }
        $command[] = $argv[$i];
    }

    $escaped = array_map('escapeshellarg', $command);
    passthru(implode(' ', $escaped), $code);
    return (int) $code;
}

function generate_stub(ReflectionExtension $extension): string
{
    $lines = [
        '<?php',
        'declare(strict_types=1);',
        '',
        '/**',
        ' * Generated by `php vslim/scripts/generate_stubs.php`.',
        ' *',
        ' * This file is for IDEs and static analysis only.',
        ' * Do not load it in production.',
        ' */',
        '',
    ];

    $constants = $extension->getConstants();
    ksort($constants);
    if ($constants !== []) {
        $lines[] = 'namespace {';
        foreach ($constants as $name => $value) {
            $lines[] = '    const ' . $name . ' = ' . render_value($value) . ';';
        }
        $lines[] = '}';
        $lines[] = '';
    }

    $functions = $extension->getFunctions();
    ksort($functions);
    if ($functions !== []) {
        $lines[] = 'namespace {';
        foreach ($functions as $function) {
            $lines = array_merge($lines, render_function($function));
            $lines[] = '';
        }
        array_pop($lines);
        $lines[] = '}';
        $lines[] = '';
    }

    $classes = sort_classes_for_stub($extension->getClasses());
    $byNamespace = [];
    foreach ($classes as $class) {
        $namespace = $class->getNamespaceName();
        $byNamespace[$namespace][] = $class;
    }
    ksort($byNamespace);

    foreach ($byNamespace as $namespace => $group) {
        $lines[] = 'namespace ' . $namespace . ' {';
        foreach ($group as $class) {
            $lines = array_merge($lines, render_class($class));
            $lines[] = '';
        }
        array_pop($lines);
        $lines[] = '}';
        $lines[] = '';
    }

    return rtrim(implode("\n", $lines)) . "\n";
}

/**
 * @param array<string, ReflectionClass> $classes
 * @return list<ReflectionClass>
 */
function sort_classes_for_stub(array $classes): array
{
    ksort($classes);
    $sorted = [];
    $seen = [];

    $visit = static function (ReflectionClass $class) use (&$visit, $classes, &$sorted, &$seen): void {
        $name = $class->getName();
        if (isset($seen[$name])) {
            return;
        }
        $seen[$name] = true;

        $parent = $class->getParentClass();
        if ($parent instanceof ReflectionClass && isset($classes[$parent->getName()])) {
            $visit($classes[$parent->getName()]);
        }

        foreach ($class->getInterfaceNames() as $interface) {
            if (isset($classes[$interface])) {
                $visit($classes[$interface]);
            }
        }

        foreach ($class->getTraitNames() as $trait) {
            if (isset($classes[$trait])) {
                $visit($classes[$trait]);
            }
        }

        $sorted[] = $class;
    };

    foreach ($classes as $class) {
        $visit($class);
    }

    return $sorted;
}

/**
 * @return list<string>
 */
function render_function(ReflectionFunction $function): array
{
    [$signature, $docblock] = render_callable_signature($function);
    $lines = [];
    foreach ($docblock as $line) {
        $lines[] = '    ' . $line;
    }
    $lines[] = '    function ' . $function->getName() . $signature . ' {}';
    return $lines;
}

/**
 * @return list<string>
 */
function render_class(ReflectionClass $class): array
{
    $lines = [];
    $header = '    ';
    if ($class->isFinal() && !$class->isTrait()) {
        $header .= 'final ';
    } elseif ($class->isAbstract() && !$class->isInterface() && !$class->isTrait()) {
        $header .= 'abstract ';
    }

    if ($class->isInterface()) {
        $header .= 'interface ';
    } elseif ($class->isTrait()) {
        $header .= 'trait ';
    } else {
        $header .= 'class ';
    }

    $header .= $class->getShortName();

    $parent = $class->getParentClass();
    if ($parent instanceof ReflectionClass) {
        $header .= ' extends ' . render_class_name($parent->getName());
    }

    $interfaces = $class->getInterfaceNames();
    if (!$class->isInterface() && $interfaces !== []) {
        $header .= ' implements ' . implode(', ', array_map('render_class_name', $interfaces));
    } elseif ($class->isInterface()) {
        $parents = array_values(array_filter(
            $interfaces,
            static fn (string $name): bool => $name !== $class->getName(),
        ));
        if ($parents !== []) {
            $header .= ' extends ' . implode(', ', array_map('render_class_name', $parents));
        }
    }

    $lines[] = $header;
    $lines[] = '    {';

    $constants = $class->getReflectionConstants();
    usort(
        $constants,
        static fn (ReflectionClassConstant $left, ReflectionClassConstant $right): int => strcmp($left->getName(), $right->getName()),
    );
    foreach ($constants as $constant) {
        if ($constant->getDeclaringClass()->getName() !== $class->getName()) {
            continue;
        }
        $visibility = $constant->isPrivate() ? 'private' : ($constant->isProtected() ? 'protected' : 'public');
        $final = $constant->isFinal() ? ' final' : '';
        $lines[] = sprintf(
            '        %s%s const %s = %s;',
            $visibility,
            $final,
            $constant->getName(),
            render_value($constant->getValue()),
        );
    }

    $properties = $class->getProperties();
    usort(
        $properties,
        static fn (ReflectionProperty $left, ReflectionProperty $right): int => strcmp($left->getName(), $right->getName()),
    );
    foreach ($properties as $property) {
        if ($property->getDeclaringClass()->getName() !== $class->getName()) {
            continue;
        }
        $visibility = $property->isPrivate() ? 'private' : ($property->isProtected() ? 'protected' : 'public');
        $static = $property->isStatic() ? ' static' : '';
        $readonly = $property->isReadOnly() ? ' readonly' : '';
        $type = $property->hasType() ? render_type($property->getType()) . ' ' : '';
        $lines[] = sprintf(
            '        %s%s%s %s$%s;',
            $visibility,
            $static,
            $readonly,
            $type,
            $property->getName(),
        );
    }

    $methods = $class->getMethods();
    usort(
        $methods,
        static fn (ReflectionMethod $left, ReflectionMethod $right): int => strcmp($left->getName(), $right->getName()),
    );
    foreach ($methods as $method) {
        if ($method->getDeclaringClass()->getName() !== $class->getName()) {
            continue;
        }

        [$signature, $docblock] = render_callable_signature($method);
        foreach ($docblock as $line) {
            $lines[] = '        ' . $line;
        }

        $prefix = '        ';
        if ($method->isFinal()) {
            $prefix .= 'final ';
        }
        if ($method->isAbstract() && !$class->isInterface()) {
            $prefix .= 'abstract ';
        }
        if (!$class->isInterface()) {
            $prefix .= $method->isPrivate() ? 'private ' : ($method->isProtected() ? 'protected ' : 'public ');
        }
        if ($method->isStatic()) {
            $prefix .= 'static ';
        }

        $reference = $method->returnsReference() ? '&' : '';
        if ($class->isInterface() || $method->isAbstract()) {
            $lines[] = $prefix . 'function ' . $reference . $method->getName() . $signature . ';';
            continue;
        }

        $lines[] = $prefix . 'function ' . $reference . $method->getName() . $signature . ' {}';
    }

    $lines[] = '    }';
    return $lines;
}

/**
 * @return array{0:string,1:list<string>}
 */
function render_callable_signature(ReflectionFunctionAbstract $function): array
{
    $params = [];
    $docblock = [];
    foreach ($function->getParameters() as $parameter) {
        [$rendered, $paramDoc] = render_parameter($parameter);
        $params[] = $rendered;
        if ($paramDoc !== null) {
            $docblock[] = ' * @param ' . $paramDoc . ' $' . $parameter->getName();
        }
    }

    $renderedReturn = '';
    if ($function->hasReturnType()) {
        $renderedReturn = ': ' . render_type($function->getReturnType());
    } elseif ($function instanceof ReflectionMethod && $function->hasTentativeReturnType()) {
        $renderedReturn = ': ' . render_type($function->getTentativeReturnType());
    }

    $signature = '(' . implode(', ', $params) . ')' . $renderedReturn;
    if ($docblock === []) {
        return [$signature, []];
    }

    return [
        $signature,
        array_merge(
            ['/**'],
            $docblock,
            [' */'],
        ),
    ];
}

/**
 * @return array{0:string,1:?string}
 */
function render_parameter(ReflectionParameter $parameter): array
{
    $reference = $parameter->isPassedByReference() ? '&' : '';
    $variadic = $parameter->isVariadic() ? '...' : '';
    $name = '$' . $parameter->getName();
    $type = $parameter->hasType() ? render_type($parameter->getType()) : null;

    if ($parameter->isVariadic()) {
        return [($type !== null ? $type . ' ' : '') . $reference . $variadic . $name, null];
    }

    if (!$parameter->isOptional()) {
        return [($type !== null ? $type . ' ' : '') . $reference . $name, null];
    }

    if ($parameter->isDefaultValueAvailable()) {
        $default = $parameter->isDefaultValueConstant()
            ? $parameter->getDefaultValueConstantName()
            : render_value($parameter->getDefaultValue());
        return [($type !== null ? $type . ' ' : '') . $reference . $name . ' = ' . $default, null];
    }

    return [$reference . $name . ' = null', $type];
}

function render_type(?ReflectionType $type): string
{
    if ($type === null) {
        return 'mixed';
    }

    if ($type instanceof ReflectionNamedType) {
        $name = $type->getName();
        if ($type->allowsNull() && !$type->isBuiltin() && $name !== 'mixed') {
            return '?' . render_named_type($type);
        }
        if ($type->allowsNull() && $type->isBuiltin() && !in_array($name, ['mixed', 'null'], true)) {
            return '?' . $name;
        }
        return render_named_type($type);
    }

    if ($type instanceof ReflectionUnionType) {
        return implode('|', array_map('render_type', $type->getTypes()));
    }

    if ($type instanceof ReflectionIntersectionType) {
        return implode('&', array_map('render_type', $type->getTypes()));
    }

    return 'mixed';
}

function render_named_type(ReflectionNamedType $type): string
{
    $name = $type->getName();
    if ($type->isBuiltin() || in_array($name, ['self', 'static', 'parent'], true)) {
        return $name;
    }
    return render_class_name($name);
}

function render_class_name(string $name): string
{
    return '\\' . ltrim($name, '\\');
}

/**
 * @param mixed $value
 */
function render_value($value): string
{
    if (is_array($value)) {
        if ($value === []) {
            return '[]';
        }
        $parts = [];
        foreach ($value as $key => $item) {
            $parts[] = render_value($key) . ' => ' . render_value($item);
        }
        return '[' . implode(', ', $parts) . ']';
    }

    return match (true) {
        is_string($value) => var_export($value, true),
        is_int($value), is_float($value) => (string) $value,
        is_bool($value) => $value ? 'true' : 'false',
        $value === null => 'null',
        default => var_export($value, true),
    };
}

/**
 * @return never
 */
function fail(string $message)
{
    fwrite(STDERR, $message . PHP_EOL);
    exit(1);
}
