<?php
declare(strict_types=1);

/**
 * Generated by `php vslim/scripts/generate_stubs.php`.
 *
 * This file is for IDEs and static analysis only.
 * Do not load it in production.
 */

namespace {
    function vslim_demo_dispatch(mixed $method_or_envelope, string $raw_path = '', string $body = ''): mixed {}

    function vslim_handle_request(mixed $method_or_envelope, string $raw_path = '', string $body = ''): mixed {}

    function vslim_probe_object(mixed $obj, string $class_name, string $method_name): mixed {}

    function vslim_response_headers(mixed ...$args) {}
}

namespace VPhp\VSlim {
    class Psr7Adapter
    {
        public function __construct() {}
        public static function dispatch($app, mixed $request): \VSlim\Vhttpd\Response {}
        public static function toVSlimRequest(mixed $request): \VSlim\Vhttpd\Request {}
        public static function toWorkerEnvelope(mixed $request): mixed {}
    }
}

namespace VSlim {
    class App
    {
        protected $assets_prefix;
        protected $auth_gate_resolver;
        protected $auth_redirect_path;
        protected $auth_user_resolver;
        protected $base_path;
        protected $booted;
        protected $cache_pool_ref;
        protected $cache_ref;
        protected $clock_ref;
        protected $config_ref;
        protected $container_ref;
        protected $database_ref;
        protected $dispatcher_ref;
        protected $error_handler;
        protected $error_response_json;
        protected $http_client_ref;
        protected $job_dispatcher_ref;
        protected $job_worker_ref;
        protected $listener_provider_ref;
        protected $live_ws_sockets;
        protected $logger_ref;
        protected $mcp_ref;
        protected $migrator_ref;
        protected $module_classes;
        protected $modules;
        protected $not_found_handler;
        protected $php_after_middlewares;
        protected $php_before_middlewares;
        protected $php_group_after_middle;
        protected $php_group_before_middle;
        protected $php_group_middle;
        protected $php_middlewares;
        protected $provider_classes;
        protected $providers;
        protected $psr_logger_ref;
        protected $routes;
        protected $use_demo;
        protected $view_base_path;
        protected $view_cache_configured;
        protected $view_cache_enabled;
        protected $view_helpers;
        protected $websocket_conn_route;
        protected $websocket_routes;
        public function __construct() {}
        public function abilityMiddleware(string $ability): \Psr\Http\Server\MiddlewareInterface {}
        public function after(mixed $handler): \VSlim\App {}
        public function allowed_methods_for(string $raw_path): array {}
        public function any(string $pattern, mixed $handler): \VSlim\App {}
        public function any_named(string $name, string $pattern, mixed $handler): \VSlim\App {}
        public function api_resource(string $resource_path, string $controller): \VSlim\App {}
        public function api_resource_opts(string $resource_path, string $controller, mixed $options): \VSlim\App {}
        public function api_singleton(string $resource_path, string $controller): \VSlim\App {}
        public function api_singleton_opts(string $resource_path, string $controller, mixed $options): \VSlim\App {}
        public function assets_prefix(): string {}
        public function auth(mixed $request): \VSlim\Auth\SessionGuard {}
        public function authCheck(mixed $request): bool {}
        public function authGuest(mixed $request): bool {}
        public function authId(mixed $request): string {}
        public function authMiddleware(): \Psr\Http\Server\MiddlewareInterface {}
        public function authRedirectTo(): string {}
        public function authUser(mixed $request): mixed {}
        public function badRequest(string $message = 'Bad Request'): \VSlim\Vhttpd\Response {}
        public function before(mixed $handler): \VSlim\App {}
        public function boot(): \VSlim\App {}
        public function booted(): bool {}
        public function bootstrap(\Traversable|array $spec): \VSlim\App {}
        public function bootstrapDir(string $path): \VSlim\App {}
        public function bootstrapFile(string $path): \VSlim\App {}
        public function cache(): \Psr\SimpleCache\CacheInterface {}
        public function cachePool(): \Psr\Cache\CacheItemPoolInterface {}
        public function can(string $ability, mixed $request): bool {}
        public function cannot(string $ability, mixed $request): bool {}
        public function clear_view_cache(): \VSlim\App {}
        public function clock(): \Psr\Clock\ClockInterface {}
        public function config(): \VSlim\Config {}
        public function conflict(string $message = 'Conflict'): \VSlim\Vhttpd\Response {}
        public function container(): \VSlim\Container {}
        public function database(): \VSlim\Database\Manager {}
        public function db(): \VSlim\Database\Manager {}
        public function delete(string $pattern, mixed $handler): \VSlim\App {}
        public function delete_named(string $name, string $pattern, mixed $handler): \VSlim\App {}
        public static function demo(): \VSlim\App {}
        public function dispatch(string $method, string $raw_path): \VSlim\Vhttpd\Response {}
        public function dispatch_body(string $method, string $raw_path, string $body): \VSlim\Vhttpd\Response {}
        public function dispatch_envelope(mixed $envelope): \VSlim\Vhttpd\Response {}
        public function dispatch_envelope_map(mixed $envelope): array {}
        public function dispatch_envelope_worker(mixed $envelope): mixed {}
        public function dispatch_request($req): \VSlim\Vhttpd\Response {}
        public function dispatcher(): \Psr\EventDispatcher\EventDispatcherInterface {}
        public function doctor(): array {}
        public function error(mixed $handler): \VSlim\App {}
        public function errorResponse(int $status, string $message, string $error_code = ''): \VSlim\Vhttpd\Response {}
        public function error_response_json_enabled(): bool {}
        public function events(): \Psr\EventDispatcher\EventDispatcherInterface {}
        public function exceptionResponse(mixed $exception, int $fallback_status = 500): \VSlim\Vhttpd\Response {}
        public function forbidden(string $message = 'Forbidden'): \VSlim\Vhttpd\Response {}
        public function get(string $pattern, mixed $handler): \VSlim\App {}
        public function get_named(string $name, string $pattern, mixed $handler): \VSlim\App {}
        public function group(string $prefix): \VSlim\RouteGroup {}
        public function guestMiddleware(): \Psr\Http\Server\MiddlewareInterface {}
        public function handle(\Psr\Http\Message\ServerRequestInterface $request): \Psr\Http\Message\ResponseInterface {}
        public function handle_mcp_dispatch(mixed $frame): mixed {}
        public function handle_websocket(mixed $frame, mixed $conn): mixed {}
        public function hasAuthUserProvider(): bool {}
        public function hasDatabase(): bool {}
        public function hasModule(string $class_name): bool {}
        public function hasProvider(string $class_name): bool {}
        public function has_config(): bool {}
        public function has_container(): bool {}
        public function has_logger(): bool {}
        public function has_mcp(): bool {}
        public function has_migrator(): bool {}
        public function has_route_name(string $name): bool {}
        public function head(string $pattern, mixed $handler): \VSlim\App {}
        public function head_named(string $name, string $pattern, mixed $handler): \VSlim\App {}
        public function helper(string $name, mixed $handler): \VSlim\App {}
        public function httpClient(): \Psr\Http\Client\ClientInterface {}
        public function jobDispatcher(): \VSlim\Job\Dispatcher {}
        public function jobWorker(): \VSlim\Job\Worker {}
        public function listenerProvider(): \Psr\EventDispatcher\ListenerProviderInterface {}
        public function live(string $pattern, mixed $handler): \VSlim\App {}
        public function live_ws(mixed $handler, mixed $frame, mixed $conn): mixed {}
        public function load_config(string $path): \VSlim\App {}
        public function load_config_text(string $text): \VSlim\App {}
        public function logger(): \VSlim\Log\Logger {}
        public function login(mixed $request, mixed $response, string $user_id): bool {}
        public function logout(mixed $request, mixed $response): bool {}
        public function make_view(): \VSlim\View {}
        public function map(mixed $methods, string $pattern, mixed $handler): \VSlim\App {}
        public function map_named(mixed $methods, string $name, string $pattern, mixed $handler): \VSlim\App {}
        public function mcp(): \VSlim\Mcp\App {}
        public function merge_config(string $path): \VSlim\App {}
        public function merge_config_text(string $text): \VSlim\App {}
        public function middleware(mixed $handler): \VSlim\App {}
        public function migrator(): \VSlim\Database\Migrator {}
        public function module(mixed $mod_input): \VSlim\App {}
        public function moduleCount(): int {}
        public function moduleMany(\Traversable|array $modules): \VSlim\App {}
        public function notFound(string $message = 'Not Found'): \VSlim\Vhttpd\Response {}
        public function not_found(mixed $handler): \VSlim\App {}
        public function options(string $pattern, mixed $handler): \VSlim\App {}
        public function options_named(string $name, string $pattern, mixed $handler): \VSlim\App {}
        public function patch(string $pattern, mixed $handler): \VSlim\App {}
        public function patch_named(string $name, string $pattern, mixed $handler): \VSlim\App {}
        public function post(string $pattern, mixed $handler): \VSlim\App {}
        public function post_named(string $name, string $pattern, mixed $handler): \VSlim\App {}
        public function providerCount(): int {}
        public function psrLogger(): \Psr\Log\LoggerInterface {}
        public function put(string $pattern, mixed $handler): \VSlim\App {}
        public function put_named(string $name, string $pattern, mixed $handler): \VSlim\App {}
        public function redirect_to(string $name, mixed $params): \VSlim\Vhttpd\Response {}
        public function redirect_to_query(string $name, mixed $params, mixed $query): \VSlim\Vhttpd\Response {}
        public function register(mixed $provider): \VSlim\App {}
        public function registerMany(\Traversable|array $providers): \VSlim\App {}
        public function resolveAuthUser(string $user_id): mixed {}
        public function resource(string $resource_path, string $controller): \VSlim\App {}
        public function resource_opts(string $resource_path, string $controller, mixed $options): \VSlim\App {}
        public function route_conflict_keys(): array {}
        public function route_conflicts() {}
        public function route_count(): int {}
        public function route_manifest() {}
        public function route_manifest_lines(): array {}
        public function route_names(): array {}
        public function serviceUnavailable(string $message = 'Service Unavailable'): \VSlim\Vhttpd\Response {}
        public function session(mixed $request): \VSlim\Session\Store {}
        public function setAuthGateResolver(mixed $resolver): \VSlim\App {}
        public function setAuthRedirectTo(string $path): \VSlim\App {}
        public function setAuthUserProvider(mixed $provider): \VSlim\App {}
        public function setAuthUserResolver(mixed $resolver): \VSlim\App {}
        public function setCache(\Psr\SimpleCache\CacheInterface $cache): \VSlim\App {}
        public function setCachePool(\Psr\Cache\CacheItemPoolInterface $pool): \VSlim\App {}
        public function setClock(\Psr\Clock\ClockInterface $clock): \VSlim\App {}
        public function setDatabase($database): \VSlim\App {}
        public function setDispatcher(\Psr\EventDispatcher\EventDispatcherInterface $dispatcher): \VSlim\App {}
        public function setHttpClient(\Psr\Http\Client\ClientInterface $client): \VSlim\App {}
        public function setListenerProvider(\Psr\EventDispatcher\ListenerProviderInterface $provider): \VSlim\App {}
        public function setMigrator($migrator): \VSlim\App {}
        public function set_assets_prefix(string $prefix): \VSlim\App {}
        public function set_base_path(string $base_path): \VSlim\App {}
        public function set_config($config): \VSlim\App {}
        public function set_container($container): \VSlim\App {}
        public function set_error_handler(mixed $handler): \VSlim\App {}
        public function set_error_response_json(bool $enabled): \VSlim\App {}
        public function set_logger($logger): \VSlim\App {}
        public function set_mcp($mcp): \VSlim\App {}
        public function set_not_found_handler(mixed $handler): \VSlim\App {}
        public function set_view_base_path(string $base_path): \VSlim\App {}
        public function set_view_cache(bool $enabled): \VSlim\App {}
        public function singleton(string $resource_path, string $controller): \VSlim\App {}
        public function singleton_opts(string $resource_path, string $controller, mixed $options): \VSlim\App {}
        public function startSessionMiddleware(): \Psr\Http\Server\MiddlewareInterface {}
        public function testing(): \VSlim\Testing\Harness {}
        public function unauthorized(string $message = 'Unauthorized'): \VSlim\Vhttpd\Response {}
        public function url_for(string $name, mixed $params): string {}
        public function url_for_abs(string $name, mixed $params, string $scheme, string $host): string {}
        public function url_for_query(string $name, mixed $params, mixed $query): string {}
        public function url_for_query_abs(string $name, mixed $params, mixed $query, string $scheme, string $host): string {}
        public function validate(mixed $data, mixed $rules): \VSlim\Validate\Validator {}
        public function validationError(mixed $errors, int $status = 422): \VSlim\Vhttpd\Response {}
        public function view(string $template, mixed $data): \VSlim\Vhttpd\Response {}
        public function view_base_path(): string {}
        public function view_cache_enabled(): bool {}
        public function view_with_layout(string $template, string $layout, mixed $data): \VSlim\Vhttpd\Response {}
        public function websocket(string $pattern, mixed $handler): \VSlim\App {}
        public function websocket_named(string $name, string $pattern, mixed $handler): \VSlim\App {}
    }

    class Config
    {
        protected $loaded;
        protected $path;
        protected $root;
        public function __construct() {}
        public function all_json(): string {}
        public function get(string $key, mixed $default_value = null): mixed {}
        public function get_bool(string $key, bool $default_value = false): bool {}
        public function get_float(string $key, float $default_value = 0): float {}
        public function get_int(string $key, int $default_value = 0): int {}
        public function get_json(string $key, string $default_json = ''): string {}
        public function get_list(string $key, mixed $default_value = []): mixed {}
        public function get_map(string $key, mixed $default_value = []): mixed {}
        public function get_string(string $key, string $default_value = ''): string {}
        public function get_string_list(string $key): array {}
        public function has(string $key): bool {}
        public function is_loaded(): bool {}
        public function load(string $path): \VSlim\Config {}
        public function load_dir(string $path): \VSlim\Config {}
        public function load_text(string $text): \VSlim\Config {}
        public function merge_dir(string $path): \VSlim\Config {}
        public function merge_file(string $path): \VSlim\Config {}
        public function merge_text(string $text): \VSlim\Config {}
        public function path(): string {}
    }

    class Container
    {
        protected $app_ref;
        protected $entries;
        protected $factories;
        protected $resolved;
        public function __construct() {}
        public function factory(string $id, mixed $callable): \VSlim\Container {}
        public function get(string $id): mixed {}
        public function has(string $id): bool {}
        public function set(string $id, mixed $value): \VSlim\Container {}
    }

    class Controller
    {
        protected $app_ref;
        protected $view_ref;
        public function __construct($app) {}
        public function app(): \VSlim\App {}
        public function json(string $body, int $status): \VSlim\Vhttpd\Response {}
        public function redirect(string $location, int $status): \VSlim\Vhttpd\Response {}
        public function redirect_to(string $name, mixed $params, int $status): \VSlim\Vhttpd\Response {}
        public function redirect_to_query(string $name, mixed $params, mixed $query, int $status): \VSlim\Vhttpd\Response {}
        public function render(string $template, mixed $data): \VSlim\Vhttpd\Response {}
        public function render_with_layout(string $template, string $layout, mixed $data): \VSlim\Vhttpd\Response {}
        public function set_app($app): \VSlim\Controller {}
        public function set_view($view): \VSlim\Controller {}
        public function text(string $body, int $status): \VSlim\Vhttpd\Response {}
        public function url_for(string $name, mixed $params): string {}
        public function url_for_query(string $name, mixed $params, mixed $query): string {}
        public function view(): \VSlim\View {}
    }

    class EnvLoader
    {
        public function __construct() {}
        public static function bootstrap(string $root): array {}
        public static function load(string $path): array {}
    }

    class RouteGroup
    {
        protected $app;
        protected $prefix;
        public function __construct() {}
        public function after(mixed $handler): \VSlim\RouteGroup {}
        public function any(string $pattern, mixed $handler): \VSlim\RouteGroup {}
        public function any_named(string $name, string $pattern, mixed $handler): \VSlim\RouteGroup {}
        public function api_resource(string $resource_path, string $controller): \VSlim\RouteGroup {}
        public function api_resource_opts(string $resource_path, string $controller, mixed $options): \VSlim\RouteGroup {}
        public function api_singleton(string $resource_path, string $controller): \VSlim\RouteGroup {}
        public function api_singleton_opts(string $resource_path, string $controller, mixed $options): \VSlim\RouteGroup {}
        public function before(mixed $handler): \VSlim\RouteGroup {}
        public function delete(string $pattern, mixed $handler): \VSlim\RouteGroup {}
        public function delete_named(string $name, string $pattern, mixed $handler): \VSlim\RouteGroup {}
        public function get(string $pattern, mixed $handler): \VSlim\RouteGroup {}
        public function get_named(string $name, string $pattern, mixed $handler): \VSlim\RouteGroup {}
        public function group(string $prefix): \VSlim\RouteGroup {}
        public function head(string $pattern, mixed $handler): \VSlim\RouteGroup {}
        public function head_named(string $name, string $pattern, mixed $handler): \VSlim\RouteGroup {}
        public function live(string $pattern, mixed $handler): \VSlim\RouteGroup {}
        public function map(mixed $methods, string $pattern, mixed $handler): \VSlim\RouteGroup {}
        public function map_named(mixed $methods, string $name, string $pattern, mixed $handler): \VSlim\RouteGroup {}
        public function middleware(mixed $handler): \VSlim\RouteGroup {}
        public function options(string $pattern, mixed $handler): \VSlim\RouteGroup {}
        public function options_named(string $name, string $pattern, mixed $handler): \VSlim\RouteGroup {}
        public function patch(string $pattern, mixed $handler): \VSlim\RouteGroup {}
        public function patch_named(string $name, string $pattern, mixed $handler): \VSlim\RouteGroup {}
        public function post(string $pattern, mixed $handler): \VSlim\RouteGroup {}
        public function post_named(string $name, string $pattern, mixed $handler): \VSlim\RouteGroup {}
        public function put(string $pattern, mixed $handler): \VSlim\RouteGroup {}
        public function put_named(string $name, string $pattern, mixed $handler): \VSlim\RouteGroup {}
        public function resource(string $resource_path, string $controller): \VSlim\RouteGroup {}
        public function resource_opts(string $resource_path, string $controller, mixed $options): \VSlim\RouteGroup {}
        public function singleton(string $resource_path, string $controller): \VSlim\RouteGroup {}
        public function singleton_opts(string $resource_path, string $controller, mixed $options): \VSlim\RouteGroup {}
        public function websocket(string $pattern, mixed $handler): \VSlim\RouteGroup {}
        public function websocket_named(string $name, string $pattern, mixed $handler): \VSlim\RouteGroup {}
    }

    class Task
    {
        public function __construct() {}
        public static function list(): array {}
        public static function spawn(mixed $target, array $params): \VSlim\TaskHandle {}
    }

    class TaskHandle
    {
        protected $async_ref;
        protected $callable;
        protected $params;
        protected $resolved;
        protected $result_box;
        public function __construct() {}
        public function wait(): mixed {}
    }

    class View
    {
        protected $assets_prefix;
        protected $base_path;
        protected $cache_enabled;
        protected $helpers;
        public function __construct(string $base_path, string $assets_prefix) {}
        public function asset(string $path): string {}
        public function assets_prefix(): string {}
        public function base_path(): string {}
        public function cache_enabled(): bool {}
        public function clear_cache(): \VSlim\View {}
        public function helper(string $name, mixed $handler): \VSlim\View {}
        public function render(string $template, mixed $data): string {}
        public function render_response(string $template, mixed $data): \VSlim\Vhttpd\Response {}
        public function render_response_with_layout(string $template, string $layout, mixed $data): \VSlim\Vhttpd\Response {}
        public function render_with_layout(string $template, string $layout, mixed $data): string {}
        public function set_assets_prefix(string $prefix): \VSlim\View {}
        public function set_base_path(string $base_path): \VSlim\View {}
        public function set_cache_enabled(bool $enabled): \VSlim\View {}
    }
}

namespace VSlim\Auth {
    class GuestMiddleware
    {
        protected $app_ref;
        protected $redirect_path;
        public function __construct() {}
        public function process(\Psr\Http\Message\ServerRequestInterface $request, \Psr\Http\Server\RequestHandlerInterface $handler): \Psr\Http\Message\ResponseInterface {}
        public function redirectTo(): string {}
        public function setApp($app): \VSlim\Auth\GuestMiddleware {}
        public function setRedirectTo(string $path): \VSlim\Auth\GuestMiddleware {}
    }

    class RequireAbilityMiddleware
    {
        protected $ability;
        protected $app_ref;
        protected $message;
        protected $status;
        public function __construct() {}
        public function ability(): string {}
        public function message(): string {}
        public function process(\Psr\Http\Message\ServerRequestInterface $request, \Psr\Http\Server\RequestHandlerInterface $handler): \Psr\Http\Message\ResponseInterface {}
        public function setAbility(string $ability): \VSlim\Auth\RequireAbilityMiddleware {}
        public function setApp($app): \VSlim\Auth\RequireAbilityMiddleware {}
        public function setMessage(string $message): \VSlim\Auth\RequireAbilityMiddleware {}
        public function setStatus(int $status): \VSlim\Auth\RequireAbilityMiddleware {}
        public function status(): int {}
    }

    class RequireAuthMiddleware
    {
        protected $app_ref;
        protected $redirect_path;
        public function __construct() {}
        public function process(\Psr\Http\Message\ServerRequestInterface $request, \Psr\Http\Server\RequestHandlerInterface $handler): \Psr\Http\Message\ResponseInterface {}
        public function redirectTo(): string {}
        public function setApp($app): \VSlim\Auth\RequireAuthMiddleware {}
        public function setRedirectTo(string $path): \VSlim\Auth\RequireAuthMiddleware {}
    }

    class SessionGuard
    {
        protected $store_ref;
        protected $user_key;
        public function __construct() {}
        public function check(): bool {}
        public function guest(): bool {}
        public function id(): string {}
        public function login(string $user_id): \VSlim\Auth\SessionGuard {}
        public function logout(): \VSlim\Auth\SessionGuard {}
        public function setStore($store): \VSlim\Auth\SessionGuard {}
        public function setUserKey(string $key): \VSlim\Auth\SessionGuard {}
        public function store(): \VSlim\Session\Store {}
        public function userKey(): string {}
        public function user_id(): string {}
    }
}

namespace VSlim\Cli {
    class App
    {
        protected $command_aliases;
        protected $command_canonical;
        protected $command_handlers;
        protected $command_hidden;
        protected $command_order;
        protected $core_app_ref;
        protected $core_app_zref;
        protected $current_trace;
        protected $last_arguments;
        protected $last_command_name;
        protected $last_input_parsed;
        protected $last_option_seen;
        protected $last_options;
        protected $last_raw_args;
        protected $last_show_help;
        protected $last_show_list;
        protected $last_show_version;
        protected $last_warnings;
        protected $project_root;
        public function __construct() {}
        public function app(): \VSlim\App {}
        public function argument(string $name, mixed $default_value = null): mixed {}
        public function arguments(): mixed {}
        public function bootstrapDir(string $path): \VSlim\Cli\App {}
        public function bootstrapFile(string $path): \VSlim\Cli\App {}
        public function command(string $name, mixed $handler): \VSlim\Cli\App {}
        public function commandHelp(string $command_name): string {}
        public function commandMany(\Traversable|array $commands): \VSlim\Cli\App {}
        public function commandName(): string {}
        public function commandNames(): array {}
        public function debugBridgePath(string $path): mixed {}
        public function hasCommand(string $name): bool {}
        public function hasOption(string $name): bool {}
        public function helpText(): string {}
        public function inputParsed(): bool {}
        public function option(string $name, mixed $default_value = null): mixed {}
        public function options(): mixed {}
        public function projectRoot(): string {}
        public function rawArgs(): array {}
        public function run(string $name, \Traversable|array $args): int {}
        public function runArgv(\Traversable|array $argv): int {}
        public function warnings(): array {}
    }
}

namespace VSlim\Container {
    class ContainerException extends \Exception implements \Throwable, \Stringable
    {
    }

    class NotFoundException extends \VSlim\Container\ContainerException implements \Stringable, \Throwable
    {
    }
}

namespace VSlim\Database {
    class Config
    {
        protected $database;
        protected $driver;
        protected $host;
        protected $password;
        protected $pool_name;
        protected $pool_size;
        protected $port;
        protected $timeout_ms;
        protected $transport;
        protected $upstream_socket;
        protected $username;
        public function __construct() {}
        public function database(): string {}
        public function driver(): string {}
        public function host(): string {}
        public function password(): string {}
        public function poolName(): string {}
        public function poolSize(): int {}
        public function port(): int {}
        public function setDatabase(string $name): \VSlim\Database\Config {}
        public function setPoolName(string $name): \VSlim\Database\Config {}
        public function setPoolSize(int $size): \VSlim\Database\Config {}
        public function setTimeoutMs(int $timeout_ms): \VSlim\Database\Config {}
        public function setTransport(string $transport): \VSlim\Database\Config {}
        public function setUpstreamSocket(string $socket_path): \VSlim\Database\Config {}
        public function set_driver(string $driver): \VSlim\Database\Config {}
        public function set_host(string $host): \VSlim\Database\Config {}
        public function set_password(string $password): \VSlim\Database\Config {}
        public function set_port(int $port): \VSlim\Database\Config {}
        public function set_username(string $username): \VSlim\Database\Config {}
        public function timeoutMs(): int {}
        public function to_json(): string {}
        public function transport(): string {}
        public function upstreamSocket(): string {}
        public function username(): string {}
    }

    class Manager
    {
        protected $config_ref;
        protected $last_affected_rows;
        protected $last_error;
        protected $last_insert_id;
        protected $mysql_connected;
        protected $mysql_pool;
        protected $mysql_tx_active;
        protected $mysql_tx_conn;
        protected $upstream_connected;
        protected $upstream_session_id;
        protected $upstream_tx_active;
        protected $vhttpd_client_ref;
        public function __construct() {}
        public function affectedRows(): int {}
        public function beginTransaction(): bool {}
        public function commit(): bool {}
        public function config(): \VSlim\Database\Config {}
        public function connect(): bool {}
        public function disconnect(): \VSlim\Database\Manager {}
        public function driver(): string {}
        public function execute(string $query): mixed {}
        public function executeAsync(string $query): \VSlim\Database\PendingResult {}
        public function executeParams(string $query, mixed $params): mixed {}
        public function executeParamsAsync(string $query, mixed $params): \VSlim\Database\PendingResult {}
        public function is_connected(): bool {}
        public function lastError(): string {}
        public function lastInsertId(): int {}
        public function ping(): bool {}
        public function poolSize(): int {}
        public function query(string $query): mixed {}
        public function queryAsync(string $query): \VSlim\Database\PendingResult {}
        public function queryOne(string $query): mixed {}
        public function queryOneParams(string $query, mixed $params): mixed {}
        public function queryParams(string $query, mixed $params): mixed {}
        public function queryParamsAsync(string $query, mixed $params): \VSlim\Database\PendingResult {}
        public function rollback(): bool {}
        public function setConfig($config): \VSlim\Database\Manager {}
        public function table(string $name): \VSlim\Database\Query {}
        public function transport(): string {}
        public function vhttpdClient(): \VSlim\Vhttpd\Client {}
    }

    class Migration
    {
        protected $manager_ref;
        protected $name;
        public function __construct() {}
        public function addColumn(string $table_name, string $column_def): mixed {}
        public function addColumnSql(string $table_name, string $column_def): string {}
        public function createTable(string $table_name, array $columns): mixed {}
        public function createTableSql(string $table_name, array $columns): string {}
        public function db(): \VSlim\Database\Manager {}
        public function down(): bool {}
        public function dropColumn(string $table_name, string $column_name): mixed {}
        public function dropColumnSql(string $table_name, string $column_name): string {}
        public function dropTable(string $table_name): mixed {}
        public function dropTableSql(string $table_name): string {}
        public function execute(string $statement): mixed {}
        public function executeParams(string $statement, mixed $params): mixed {}
        public function manager(): \VSlim\Database\Manager {}
        public function name(): string {}
        public function query(string $statement): mixed {}
        public function queryParams(string $statement, mixed $params): mixed {}
        public function setManager($manager): \VSlim\Database\Migration {}
        public function setName(string $name): \VSlim\Database\Migration {}
        public function up(): bool {}
    }

    class Migrator
    {
        protected $manager_ref;
        protected $migrations_path;
        protected $seeds_path;
        protected $table_name;
        public function __construct() {}
        public function loadMigration(string $file): mixed {}
        public function loadSeeder(string $file): mixed {}
        public function manager(): \VSlim\Database\Manager {}
        public function migrate(): int {}
        public function migrationFiles(): array {}
        public function migrationsPath(): string {}
        public function rollback(): int {}
        public function seed(string $name = ''): int {}
        public function seedFiles(): array {}
        public function seedsPath(): string {}
        public function setManager($manager): \VSlim\Database\Migrator {}
        public function setMigrationsPath(string $path): \VSlim\Database\Migrator {}
        public function setSeedsPath(string $path): \VSlim\Database\Migrator {}
        public function setTable(string $table_name): \VSlim\Database\Migrator {}
        public function status(): mixed {}
        public function table(): string {}
    }

    class Model
    {
        protected $attributes;
        protected $exists_in_db;
        protected $manager_ref;
        protected $primary_key;
        protected $table_name;
        public function __construct() {}
        public function all(): mixed {}
        public function allQuery(): \VSlim\Database\Query {}
        public function attributes(): mixed {}
        public function delete(): bool {}
        public function deleteQuery(): \VSlim\Database\Query {}
        public function exists(): bool {}
        public function fill(mixed $values): \VSlim\Database\Model {}
        public function find(mixed $id): mixed {}
        public function findQuery(mixed $id): \VSlim\Database\Query {}
        public function get(string $key, mixed $default_value): mixed {}
        public function manager(): \VSlim\Database\Manager {}
        public function newQuery(): \VSlim\Database\Query {}
        public function primaryKey(): string {}
        public function save(): \VSlim\Database\Model {}
        public function saveQuery(): \VSlim\Database\Query {}
        public function set(string $key, mixed $value): \VSlim\Database\Model {}
        public function setManager($manager): \VSlim\Database\Model {}
        public function setPrimaryKey(string $name): \VSlim\Database\Model {}
        public function setTable(string $name): \VSlim\Database\Model {}
        public function table(): string {}
    }

    class PendingResult
    {
        protected $active;
        protected $affected_rows;
        protected $async_ref;
        protected $kind;
        protected $last_error;
        protected $last_insert_id;
        protected $resolved;
        protected $result_box;
        public function __construct() {}
        public function affectedRows(): int {}
        public function lastError(): string {}
        public function lastInsertId(): int {}
        public function resolved(): bool {}
        public function wait(): mixed {}
    }

    class Query
    {
        protected $kind;
        protected $limit_count;
        protected $manager_ref;
        protected $mutation_values;
        protected $offset_count;
        protected $order_clauses;
        protected $select_columns;
        protected $table_name;
        protected $where_clauses;
        public function __construct() {}
        public function delete(): \VSlim\Database\Query {}
        public function first(): mixed {}
        public function get(): mixed {}
        public function insert(mixed $values): \VSlim\Database\Query {}
        public function insertGetId(): int {}
        public function limit(int $limit): \VSlim\Database\Query {}
        public function manager(): \VSlim\Database\Manager {}
        public function offset(int $offset): \VSlim\Database\Query {}
        public function orderBy(string $column, string $direction): \VSlim\Database\Query {}
        public function params(): mixed {}
        public function reset(): \VSlim\Database\Query {}
        public function run(): mixed {}
        public function select(mixed $columns): \VSlim\Database\Query {}
        public function setManager($manager): \VSlim\Database\Query {}
        public function table(string $name): \VSlim\Database\Query {}
        public function toSql(): string {}
        public function update(mixed $values): \VSlim\Database\Query {}
        public function where(string $column, mixed $value): \VSlim\Database\Query {}
        public function whereOp(string $column, string $op, mixed $value): \VSlim\Database\Query {}
    }

    class Seeder
    {
        protected $manager_ref;
        protected $name;
        public function __construct() {}
        public function db(): \VSlim\Database\Manager {}
        public function manager(): \VSlim\Database\Manager {}
        public function name(): string {}
        public function run(): bool {}
        public function setManager($manager): \VSlim\Database\Seeder {}
        public function setName(string $name): \VSlim\Database\Seeder {}
    }
}

namespace VSlim\Dev {
    class PhpSignatureProbe
    {
        protected $provider_ref;
        public function __construct() {}
        public function acceptCallable(callable $cb): bool {}
        public function acceptDateTimeInterface(?\DateTimeInterface $expiration): bool {}
        public function acceptFalse(false $flag): bool {}
        public function acceptNull(null $value): bool {}
        public function acceptPsrRequest(\Psr\Http\Message\RequestInterface $request): bool {}
        public function acceptTrue(true $flag): bool {}
        public function alwaysFalse(): false {}
        public function alwaysNull(): null {}
        public function alwaysThrow(): never {}
        public function alwaysTrue(): true {}
        public function borrowedProvider(): \Psr\EventDispatcher\ListenerProviderInterface {}
        public function borrowedProviderAlias(): \Psr\EventDispatcher\ListenerProviderInterface {}
        public function borrowedProviderFromGuard(): \Psr\EventDispatcher\ListenerProviderInterface {}
        public function borrowedProviderFromIfExpr(bool $use_alias): \Psr\EventDispatcher\ListenerProviderInterface {}
        public function borrowedProviderFromIfExprAlias(bool $use_alias): \Psr\EventDispatcher\ListenerProviderInterface {}
        public function borrowedProviderFromMatchExpr(bool $use_alias): \Psr\EventDispatcher\ListenerProviderInterface {}
        public function borrowedProviderFromMatchExprAlias(bool $use_alias): \Psr\EventDispatcher\ListenerProviderInterface {}
        public function borrowedProviderFromOrBlock(): \Psr\EventDispatcher\ListenerProviderInterface {}
        public function borrowedProviderFromOrBlockAlias(): \Psr\EventDispatcher\ListenerProviderInterface {}
        public function freshProvider(): \Psr\EventDispatcher\ListenerProviderInterface {}
        public function freshProviderAlias(): \Psr\EventDispatcher\ListenerProviderInterface {}
        public function freshProviderFromIfExpr(bool $use_alias): \Psr\EventDispatcher\ListenerProviderInterface {}
        public function freshProviderFromIfExprAlias(bool $use_alias): \Psr\EventDispatcher\ListenerProviderInterface {}
        public function freshProviderFromMatchExpr(bool $use_alias): \Psr\EventDispatcher\ListenerProviderInterface {}
        public function freshProviderFromMatchExprAlias(bool $use_alias): \Psr\EventDispatcher\ListenerProviderInterface {}
        public function freshProviderFromOrBlock(): \Psr\EventDispatcher\ListenerProviderInterface {}
        public function freshProviderFromOrBlockAlias(): \Psr\EventDispatcher\ListenerProviderInterface {}
        public function makePsrResponse(): \Psr\Http\Message\ResponseInterface {}
        public static function makeStaticPsrResponse(): \Psr\Http\Message\ResponseInterface {}
        public function optionalTail(string $prefix, string $suffix = ''): string {}
        public function setProvider(\Psr\EventDispatcher\ListenerProviderInterface $provider): \VSlim\Dev\PhpSignatureProbe {}
    }
}

namespace VSlim\Job {
    class Dispatcher
    {
        protected $manager_ref;
        public function __construct() {}
        public function dispatch(string $job_class, mixed $payload, string $queue, int $delay_seconds, int $max_attempts): int {}
        public function manager(): \VSlim\Database\Manager {}
        public function setManager($manager): \VSlim\Job\Dispatcher {}
    }

    class Worker
    {
        protected $manager_ref;
        protected $reserve_timeout_secs;
        protected $retry_delay_seconds;
        protected $worker_id;
        public function __construct() {}
        public function run(string $queue, int $max_jobs, int $sleep_ms, bool $stop_when_empty): int {}
        public function runOnce(string $queue): int {}
        public function setManager($manager): \VSlim\Job\Worker {}
        public function setReserveTimeoutSeconds(int $seconds): \VSlim\Job\Worker {}
        public function setRetryDelaySeconds(int $seconds): \VSlim\Job\Worker {}
        public function setWorkerId(string $worker_id): \VSlim\Job\Worker {}
        public function workerId(): string {}
    }
}

namespace VSlim\Live {
    class Component
    {
        protected $assigns;
        protected $host;
        protected $id;
        protected $socket_ref;
        public function __construct() {}
        public function append_to($socket, string $target_id): \VSlim\Live\Socket {}
        public function append_to_bound(string $target_id): \VSlim\Live\Socket {}
        public function assign(string $key, mixed $value): \VSlim\Live\Component {}
        public function assign_many(mixed $values): \VSlim\Live\Component {}
        public function assigns(): array {}
        public function bind_socket($socket): \VSlim\Live\Component {}
        public function clear_assigns(): \VSlim\Live\Component {}
        public function component_marker(): bool {}
        public function has_socket(): bool {}
        public function html(): string {}
        public function id(): string {}
        public function layout(): string {}
        public function patch($socket): \VSlim\Live\Socket {}
        public function patch_bound(): \VSlim\Live\Socket {}
        public function prepend_to($socket, string $target_id): \VSlim\Live\Socket {}
        public function prepend_to_bound(string $target_id): \VSlim\Live\Socket {}
        public function remove($socket): \VSlim\Live\Socket {}
        public function remove_bound(): \VSlim\Live\Socket {}
        public function render_template(string $template, mixed $data): string {}
        public function set_app($app): \VSlim\Live\Component {}
        public function set_id(string $id): \VSlim\Live\Component {}
        public function set_layout(string $layout): \VSlim\Live\Component {}
        public function set_template(string $template): \VSlim\Live\Component {}
        public function set_view($view): \VSlim\Live\Component {}
        public function state(): \VSlim\Live\ComponentState {}
        public function template(): string {}
        public function view(): \VSlim\View {}
    }

    class ComponentState
    {
        protected $component_id;
        protected $socket_ref;
        public function __construct() {}
        public function available(): bool {}
        public function clear(string $field): \VSlim\Live\ComponentState {}
        public function get(string $field): string {}
        public function get_or(string $field, string $fallback): string {}
        public function set(string $field, mixed $value): \VSlim\Live\ComponentState {}
    }

    class Form
    {
        protected $fields;
        protected $last_error_count;
        protected $name;
        protected $socket_ref;
        protected $validated;
        public function __construct() {}
        public function available(): bool {}
        public function clear_error(string $field): \VSlim\Live\Form {}
        public function clear_errors(): \VSlim\Live\Form {}
        public function data(): mixed {}
        public function error(string $field): string {}
        public function error_count(): int {}
        public function errors(mixed $values): \VSlim\Live\Form {}
        public function fill(mixed $values): \VSlim\Live\Form {}
        public function forget(string $field): \VSlim\Live\Form {}
        public function forget_many(mixed $fields): \VSlim\Live\Form {}
        public function has_error(string $field): bool {}
        public function input(string $field): string {}
        public function input_or(string $field, string $fallback): string {}
        public function invalid(): bool {}
        public function name(): string {}
        public function reset(mixed $values): \VSlim\Live\Form {}
        public function valid(): bool {}
        public function validate(mixed $validator): \VSlim\Live\Form {}
    }

    class Socket
    {
        protected $assigns;
        protected $connected;
        protected $events;
        protected $flashes;
        protected $id;
        protected $navigate_to;
        protected $patches;
        protected $pubsub;
        protected $raw_path;
        protected $redirect_to;
        protected $root_id;
        public function __construct() {}
        public function append(string $target_id, string $html): \VSlim\Live\Socket {}
        public function assign(string $key, mixed $value): \VSlim\Live\Socket {}
        public function assign_component_state(string $component_id, string $field, mixed $value): \VSlim\Live\Socket {}
        public function assign_error(string $field, string $message): \VSlim\Live\Socket {}
        public function assign_errors(mixed $values): \VSlim\Live\Socket {}
        public function assign_form(mixed $values): \VSlim\Live\Socket {}
        public function assign_many(mixed $values): \VSlim\Live\Socket {}
        public function assigns(): array {}
        public function broadcast_info(string $room, string $event, mixed $payload, bool $include_self): \VSlim\Live\Socket {}
        public function clear_assigns(): \VSlim\Live\Socket {}
        public function clear_component_state(string $component_id, string $field): \VSlim\Live\Socket {}
        public function clear_error(string $field): \VSlim\Live\Socket {}
        public function clear_errors(): \VSlim\Live\Socket {}
        public function clear_events(): \VSlim\Live\Socket {}
        public function clear_flashes(): \VSlim\Live\Socket {}
        public function clear_navigate(): \VSlim\Live\Socket {}
        public function clear_patches(): \VSlim\Live\Socket {}
        public function clear_pubsub(): \VSlim\Live\Socket {}
        public function clear_redirect(): \VSlim\Live\Socket {}
        public function component_state(string $component_id, string $field): string {}
        public function component_state_or(string $component_id, string $field, string $fallback): string {}
        public function connected(): bool {}
        public function error(string $field): string {}
        public function events() {}
        public function flash(string $kind, string $message): \VSlim\Live\Socket {}
        public function flashes() {}
        public function forget(string $key): \VSlim\Live\Socket {}
        public function forget_input(string $field): \VSlim\Live\Socket {}
        public function forget_inputs(mixed $fields): \VSlim\Live\Socket {}
        public function form(string $name): \VSlim\Live\Form {}
        public function get(string $key): string {}
        public function has(string $key): bool {}
        public function has_error(string $field): bool {}
        public function id(): string {}
        public function input(string $field): string {}
        public function input_or(string $field, string $fallback): string {}
        public function join_topic(string $room): \VSlim\Live\Socket {}
        public function leave_topic(string $room): \VSlim\Live\Socket {}
        public function navigate(string $location): \VSlim\Live\Socket {}
        public function navigate_to(): string {}
        public function old(string $field): string {}
        public function old_or(string $field, string $fallback): string {}
        public function patch(string $target_id, string $html): \VSlim\Live\Socket {}
        public function patches() {}
        public function prepend(string $target_id, string $html): \VSlim\Live\Socket {}
        public function pubsub_commands() {}
        public function push_event(string $event, string $payload): \VSlim\Live\Socket {}
        public function redirect(string $location): \VSlim\Live\Socket {}
        public function redirect_to(): string {}
        public function remove(string $target_id): \VSlim\Live\Socket {}
        public function reset_form(mixed $values): \VSlim\Live\Socket {}
        public function root_id(): string {}
        public function set_attr(string $target_id, string $name, string $value): \VSlim\Live\Socket {}
        public function set_connected(bool $connected): \VSlim\Live\Socket {}
        public function set_id(string $id): \VSlim\Live\Socket {}
        public function set_root_id(string $root_id): \VSlim\Live\Socket {}
        public function set_target(string $raw_path): \VSlim\Live\Socket {}
        public function set_text(string $target_id, string $text): \VSlim\Live\Socket {}
        public function target(): string {}
    }

    class View
    {
        protected $host;
        protected $root_id;
        protected $sockets;
        public function __construct() {}
        public function attr_name(string $name): string {}
        public function attr_prefix(): string {}
        public function bootstrap_attrs($socket, string $endpoint): string {}
        public function html($socket): string {}
        public function layout(): string {}
        public function live_marker(): bool {}
        public function patch($socket, string $target_id): \VSlim\Live\Socket {}
        public function patch_template($socket, string $target_id, string $template): \VSlim\Live\Socket {}
        public function render_socket(string $template, $socket): string {}
        public function render_socket_with_layout(string $template, string $layout, $socket): string {}
        public function render_template(string $template, mixed $data): string {}
        public function render_template_with_layout(string $template, string $layout, mixed $data): string {}
        public function response($socket): \VSlim\Vhttpd\Response {}
        public function root_id(): string {}
        public function runtime_asset(): string {}
        public function runtime_script_tag(): string {}
        public function set_app($app): \VSlim\Live\View {}
        public function set_layout(string $layout): \VSlim\Live\View {}
        public function set_root_id(string $root_id): \VSlim\Live\View {}
        public function set_template(string $template): \VSlim\Live\View {}
        public function set_view($view): \VSlim\Live\View {}
        public function template(): string {}
        public function view(): \VSlim\View {}
    }
}

namespace VSlim\Log {
    class Level
    {
        public const DEBUG = 'debug';
        public const DISABLED = 'disabled';
        public const ERROR = 'error';
        public const FATAL = 'fatal';
        public const INFO = 'info';
        public const WARN = 'warn';
        public function __construct() {}
        public static function all(): array {}
        public static function debug(): string {}
        public static function disabled(): string {}
        public static function error(): string {}
        public static function fatal(): string {}
        public static function info(): string {}
        public static function warn(): string {}
    }

    class Logger implements \Stringable
    {
        protected $channel;
        protected $console_target;
        protected $context;
        protected $engine_ref;
        protected $level_name;
        protected $local_time_enabled;
        protected $output_file;
        protected $short_tag_enabled;
        public function __construct() {}
        public function __toString(): string {}
        public function alert(string $message): \VSlim\Log\Logger {}
        public function alert_context(string $message, mixed $context): \VSlim\Log\Logger {}
        public function channel(): string {}
        public function clear_context(): \VSlim\Log\Logger {}
        public function context(): array {}
        public function critical(string $message): \VSlim\Log\Logger {}
        public function critical_context(string $message, mixed $context): \VSlim\Log\Logger {}
        public function debug(string $message): \VSlim\Log\Logger {}
        public function debug_context(string $message, mixed $context): \VSlim\Log\Logger {}
        public static function debug_level(): string {}
        public static function disabled_level(): string {}
        public function emergency(string $message): \VSlim\Log\Logger {}
        public function emergency_context(string $message, mixed $context): \VSlim\Log\Logger {}
        public function error(string $message): \VSlim\Log\Logger {}
        public function error_context(string $message, mixed $context): \VSlim\Log\Logger {}
        public static function error_level(): string {}
        public static function fatal_level(): string {}
        public function info(string $message): \VSlim\Log\Logger {}
        public function info_context(string $message, mixed $context): \VSlim\Log\Logger {}
        public static function info_level(): string {}
        public function level(): string {}
        public function log(string $level, string $message): \VSlim\Log\Logger {}
        public function log_context(string $level, string $message, mixed $context): \VSlim\Log\Logger {}
        public function notice(string $message): \VSlim\Log\Logger {}
        public function notice_context(string $message, mixed $context): \VSlim\Log\Logger {}
        public function output_file(): string {}
        public function output_target(): string {}
        public function set_channel(string $channel): \VSlim\Log\Logger {}
        public function set_context(mixed $context): \VSlim\Log\Logger {}
        public function set_level(string $level): \VSlim\Log\Logger {}
        public function set_local_time(bool $enabled): \VSlim\Log\Logger {}
        public function set_output_file(string $path): \VSlim\Log\Logger {}
        public function set_short_tag(bool $enabled): \VSlim\Log\Logger {}
        public function use_stderr(): \VSlim\Log\Logger {}
        public function use_stdout(): \VSlim\Log\Logger {}
        public function warn(string $message): \VSlim\Log\Logger {}
        public function warn_context(string $message, mixed $context): \VSlim\Log\Logger {}
        public static function warn_level(): string {}
        public function warning(string $message): \VSlim\Log\Logger {}
        public function warning_context(string $message, mixed $context): \VSlim\Log\Logger {}
        public function with_context(string $key, string $value): \VSlim\Log\Logger {}
    }

    class PsrLogger implements \Stringable
    {
        protected $logger_ref;
        public function __construct() {}
        public function __toString(): string {}
        public function alert(mixed $message, mixed $default_context = []): void {}
        public function clear_context(): \VSlim\Log\PsrLogger {}
        public function critical(mixed $message, mixed $default_context = []): void {}
        public function debug(mixed $message, mixed $default_context = []): void {}
        public function emergency(mixed $message, mixed $default_context = []): void {}
        public function error(mixed $message, mixed $default_context = []): void {}
        public function info(mixed $message, mixed $default_context = []): void {}
        public function log(mixed $level, mixed $message, mixed $default_context = []): void {}
        public function logger(): \VSlim\Log\Logger {}
        public function notice(mixed $message, mixed $default_context = []): void {}
        public function set_channel(string $channel): \VSlim\Log\PsrLogger {}
        public function set_context(mixed $context): \VSlim\Log\PsrLogger {}
        public function set_level(string $level): \VSlim\Log\PsrLogger {}
        public function set_logger($inner): \VSlim\Log\PsrLogger {}
        public function set_output_file(string $path): \VSlim\Log\PsrLogger {}
        public function use_stderr(): \VSlim\Log\PsrLogger {}
        public function use_stdout(): \VSlim\Log\PsrLogger {}
        public function warning(mixed $message, mixed $default_context = []): void {}
        public function with_context(string $key, string $value): \VSlim\Log\PsrLogger {}
    }
}

namespace VSlim\Mcp {
    class App
    {
        protected $method_handlers;
        protected $prompt_arguments;
        protected $prompt_descriptions;
        protected $prompt_handlers;
        protected $resource_descriptions;
        protected $resource_handlers;
        protected $resource_mime_types;
        protected $resource_names;
        protected $server_capabilities;
        protected $server_info;
        protected $tool_descriptions;
        protected $tool_handlers;
        protected $tool_schemas;
        public function __construct() {}
        public function capabilities(mixed $definitions): \VSlim\Mcp\App {}
        public function capability(string $name, mixed $definition): \VSlim\Mcp\App {}
        public static function capability_error(mixed $frame, string $message, int $status): mixed {}
        public static function client_capabilities(mixed $frame): mixed {}
        public static function client_supports(mixed $frame, string $name): bool {}
        public function handle_mcp_dispatch(mixed $frame): mixed {}
        public static function notification(string $method, mixed $params): string {}
        public static function notify(mixed $id, string $method, mixed $params, string $session_id, string $protocol_version): mixed {}
        public function prompt(string $name, string $description, mixed $arguments, mixed $handler): \VSlim\Mcp\App {}
        public static function queue_log(mixed $id, string $level, string $message, mixed $data, string $logger, string $session_id, string $protocol_version): mixed {}
        public static function queue_messages(mixed $id, mixed $result, mixed $messages, int $status, string $protocol_version, string $session_id, mixed $headers): mixed {}
        public static function queue_notification(mixed $id, string $method, mixed $params, string $session_id, string $protocol_version): mixed {}
        public static function queue_progress(mixed $id, mixed $progress_token, mixed $progress, mixed $total, string $message, string $session_id, string $protocol_version): mixed {}
        public static function queue_request(mixed $response_id, mixed $request_id, string $method, mixed $params, string $session_id, string $protocol_version): mixed {}
        public static function queue_sampling(mixed $response_id, mixed $sampling_id, mixed $messages, string $session_id, string $protocol_version, mixed $model_preferences, string $system_prompt, int $max_tokens): mixed {}
        public static function queued_result(mixed $id, mixed $result, mixed $notifications, int $status, string $protocol_version, string $session_id, mixed $headers): mixed {}
        public function register(string $method, mixed $handler): \VSlim\Mcp\App {}
        public static function request(mixed $id, string $method, mixed $params): string {}
        public static function require_capability(mixed $frame, string $name, string $message, int $status): mixed {}
        public function resource(string $uri, string $name, string $description, string $mime_type, mixed $handler): \VSlim\Mcp\App {}
        public static function sampling_request(mixed $id, mixed $messages, mixed $model_preferences, string $system_prompt, int $max_tokens, mixed $temperature, mixed $tools, mixed $tool_choice): string {}
        public function server_info(mixed $info): \VSlim\Mcp\App {}
        public function tool(string $name, string $description, mixed $input_schema, mixed $handler): \VSlim\Mcp\App {}
    }
}

namespace VSlim\Psr14 {
    class EventDispatcher
    {
        protected $provider_ref;
        public function __construct() {}
        public function dispatch(object $event): object {}
        public function listen(string $event_class, mixed $listener): \VSlim\Psr14\EventDispatcher {}
        public function listenAny(mixed $listener): \VSlim\Psr14\EventDispatcher {}
        public function provider(): \Psr\EventDispatcher\ListenerProviderInterface {}
        public function setProvider(\Psr\EventDispatcher\ListenerProviderInterface $provider): \VSlim\Psr14\EventDispatcher {}
    }

    class ListenerProvider
    {
        protected $listeners;
        public function __construct() {}
        public function getListenersForEvent(object $event): \Traversable|array {}
        public function listen(string $event_class, mixed $listener): \VSlim\Psr14\ListenerProvider {}
        public function listenAny(mixed $listener): \VSlim\Psr14\ListenerProvider {}
        public function listenerCount(): int {}
    }
}

namespace VSlim\Psr15 {
    class ContinueHandler
    {
        protected $state;
        public function __construct() {}
        public function handle(\Psr\Http\Message\ServerRequestInterface $request): \Psr\Http\Message\ResponseInterface {}
    }

    class NextHandler
    {
        protected $state;
        public function __construct() {}
        public function handle(\Psr\Http\Message\ServerRequestInterface $request): \Psr\Http\Message\ResponseInterface {}
    }
}

namespace VSlim\Psr16 {
    class Cache
    {
        protected $clock_ref;
        protected $default_ttl_seconds;
        protected $entries;
        protected $namespace_prefix;
        public function __construct() {}
        public function clear(): bool {}
        public function clock(): \Psr\Clock\ClockInterface {}
        public function defaultTtlSeconds(): int {}
        public function delete(string $key): bool {}
        public function deleteMultiple(\Traversable|array $keys): bool {}
        public function get(string $key, mixed $default_value = null): mixed {}
        public function getMultiple(\Traversable|array $keys, mixed $default_value = null): \Traversable|array {}
        public function has(string $key): bool {}
        public function namespace(): string {}
        public function set(string $key, mixed $value, mixed $ttl = null): bool {}
        public function setClock(\Psr\Clock\ClockInterface $clock): \VSlim\Psr16\Cache {}
        public function setDefaultTtlSeconds(int $seconds): \VSlim\Psr16\Cache {}
        public function setMultiple(\Traversable|array $values, mixed $ttl = null): bool {}
        public function setNamespace(string $prefix): \VSlim\Psr16\Cache {}
    }

    class CacheException extends \Exception implements \Throwable, \Stringable
    {
    }

    class InvalidArgumentException extends \VSlim\Psr16\CacheException implements \Stringable, \Throwable
    {
    }
}

namespace VSlim\Psr17 {
    class RequestFactory
    {
        public function __construct() {}
        public function createRequest(mixed $method, mixed $uri): \Psr\Http\Message\RequestInterface {}
    }

    class ResponseFactory
    {
        public function __construct() {}
        public function createResponse(mixed $default_status = 200, mixed $default_reason_phrase = ''): \Psr\Http\Message\ResponseInterface {}
    }

    class ServerRequestFactory
    {
        public function __construct() {}
        public function createServerRequest(mixed $method, mixed $uri, array $default_server_params = []): \Psr\Http\Message\ServerRequestInterface {}
    }

    class StreamFactory
    {
        public function __construct() {}
        public function createStream(mixed $default_content = ''): \Psr\Http\Message\StreamInterface {}
        public function createStreamFromFile(mixed $filename, mixed $default_mode = 'r'): \Psr\Http\Message\StreamInterface {}
        public function createStreamFromResource(mixed $resource): \Psr\Http\Message\StreamInterface {}
    }

    class UploadedFileFactory
    {
        public function __construct() {}
        public function createUploadedFile(\Psr\Http\Message\StreamInterface $stream, mixed $default_size = null, mixed $default_error = 0, mixed $default_client_filename = null, mixed $default_client_media_type = null): \Psr\Http\Message\UploadedFileInterface {}
    }

    class UriFactory
    {
        public function __construct() {}
        public function createUri(mixed $default_uri = ''): \Psr\Http\Message\UriInterface {}
    }
}

namespace VSlim\Psr18 {
    class Client
    {
        protected $timeout_seconds;
        public function __construct() {}
        public static function ignorePhpWarning(int $err_no, string $err_str, string $err_file, int $err_line): bool {}
        public function sendRequest(\Psr\Http\Message\RequestInterface $request): \Psr\Http\Message\ResponseInterface {}
        public function timeout(int $seconds): \VSlim\Psr18\Client {}
        public function timeout_seconds_value(): int {}
    }

    class ClientException extends \Exception implements \Throwable, \Stringable
    {
    }

    class RequestException extends \VSlim\Psr18\ClientException implements \Stringable, \Throwable
    {
        public $request_ref;
        public function attachRequest(\Psr\Http\Message\RequestInterface $request): void {}
        public function getRequest(): \Psr\Http\Message\RequestInterface {}
    }

    class NetworkException extends \VSlim\Psr18\RequestException implements \Throwable, \Stringable
    {
        public function attachRequest(\Psr\Http\Message\RequestInterface $request): void {}
        public function getRequest(): \Psr\Http\Message\RequestInterface {}
    }
}

namespace VSlim\Psr20 {
    class Clock
    {
        public function __construct() {}
        public function now(): \DateTimeImmutable {}
    }
}

namespace VSlim\Psr6 {
    class CacheException extends \Exception implements \Throwable, \Stringable
    {
    }

    class CacheItem
    {
        protected $clock_ref;
        protected $expires_at_unix;
        protected $has_value;
        protected $hit;
        protected $key;
        protected $value_ref;
        public function __construct() {}
        public function expiresAfter(mixed $time_value): static {}
        public function expiresAt(?\DateTimeInterface $expiration): static {}
        public function get(): mixed {}
        public function getKey(): string {}
        public function isHit(): bool {}
        public function set(mixed $value): static {}
    }

    class CacheItemPool
    {
        protected $clock_ref;
        protected $default_ttl_seconds;
        protected $deferred;
        protected $entries;
        protected $namespace_prefix;
        public function __construct() {}
        public function clear(): bool {}
        public function clock(): \Psr\Clock\ClockInterface {}
        public function commit(): bool {}
        public function defaultTtlSeconds(): int {}
        public function deleteItem(string $key): bool {}
        public function deleteItems(array $keys): bool {}
        public function getItem(string $key): \Psr\Cache\CacheItemInterface {}
        public function getItems(array $keys = []): \Traversable|array {}
        public function hasItem(string $key): bool {}
        public function namespace(): string {}
        public function save(\Psr\Cache\CacheItemInterface $item): bool {}
        public function saveDeferred(\Psr\Cache\CacheItemInterface $item): bool {}
        public function setClock(\Psr\Clock\ClockInterface $clock): \VSlim\Psr6\CacheItemPool {}
        public function setDefaultTtlSeconds(int $seconds): \VSlim\Psr6\CacheItemPool {}
        public function setNamespace(string $prefix): \VSlim\Psr6\CacheItemPool {}
    }

    class InvalidArgumentException extends \VSlim\Psr6\CacheException implements \Stringable, \Throwable
    {
    }
}

namespace VSlim\Psr7 {
    class Request implements \Stringable
    {
        protected $body_ref;
        protected $header_names;
        protected $headers;
        protected $method;
        protected $protocol_version;
        protected $request_target;
        protected $uri_ref;
        public function __construct() {}
        public function __toString(): string {}
        public function getBody(): \Psr\Http\Message\StreamInterface {}
        public function getHeader(mixed $name): array {}
        public function getHeaderLine(mixed $name): string {}
        public function getHeaders(): array {}
        public function getMethod(): string {}
        public function getProtocolVersion(): string {}
        public function getRequestTarget(): string {}
        public function getUri(): \Psr\Http\Message\UriInterface {}
        public function hasHeader(mixed $name): bool {}
        public function withAddedHeader(mixed $name, mixed $value): \Psr\Http\Message\RequestInterface {}
        public function withBody(\Psr\Http\Message\StreamInterface $body): \Psr\Http\Message\RequestInterface {}
        public function withHeader(mixed $name, mixed $value): \Psr\Http\Message\RequestInterface {}
        public function withMethod(mixed $method): \Psr\Http\Message\RequestInterface {}
        public function withProtocolVersion(mixed $version): \Psr\Http\Message\RequestInterface {}
        public function withRequestTarget(mixed $request_target): \Psr\Http\Message\RequestInterface {}
        public function withUri(\Psr\Http\Message\UriInterface $uri, mixed $default_preserve_host = false): \Psr\Http\Message\RequestInterface {}
        public function withoutHeader(mixed $name): \Psr\Http\Message\RequestInterface {}
    }

    class Response implements \Stringable
    {
        protected $body_ref;
        protected $header_names;
        protected $headers;
        protected $protocol_version;
        protected $reason_phrase;
        protected $status;
        public function __construct(int $default_status = 200, string $default_reason_phrase = '') {}
        public function __toString(): string {}
        public function getBody(): \Psr\Http\Message\StreamInterface {}
        public function getHeader(mixed $name): array {}
        public function getHeaderLine(mixed $name): string {}
        public function getHeaders(): array {}
        public function getProtocolVersion(): string {}
        public function getReasonPhrase(): string {}
        public function getStatusCode(): int {}
        public function hasHeader(mixed $name): bool {}
        public function withAddedHeader(mixed $name, mixed $value): \Psr\Http\Message\ResponseInterface {}
        public function withBody(\Psr\Http\Message\StreamInterface $body): \Psr\Http\Message\ResponseInterface {}
        public function withHeader(mixed $name, mixed $value): \Psr\Http\Message\ResponseInterface {}
        public function withProtocolVersion(mixed $version): \Psr\Http\Message\ResponseInterface {}
        public function withStatus(mixed $code, mixed $default_reason_phrase = ''): \Psr\Http\Message\ResponseInterface {}
        public function withoutHeader(mixed $name): \Psr\Http\Message\ResponseInterface {}
    }

    class ServerRequest implements \Stringable
    {
        protected $attributes_ref;
        protected $body_ref;
        protected $cookie_params_ref;
        protected $header_names;
        protected $headers;
        protected $method;
        protected $parsed_body_ref;
        protected $protocol_version;
        protected $query_params_ref;
        protected $request_target;
        protected $server_params_ref;
        protected $uploaded_files_ref;
        protected $uri_ref;
        public function __construct() {}
        public function __toString(): string {}
        public function getAttribute(mixed $name, mixed $default_value = null): mixed {}
        public function getAttributes(): array {}
        public function getBody(): \Psr\Http\Message\StreamInterface {}
        public function getCookieParams(): array {}
        public function getHeader(mixed $name): array {}
        public function getHeaderLine(mixed $name): string {}
        public function getHeaders(): array {}
        public function getMethod(): string {}
        public function getParsedBody(): mixed {}
        public function getProtocolVersion(): string {}
        public function getQueryParams(): array {}
        public function getRequestTarget(): string {}
        public function getServerParams(): array {}
        public function getUploadedFiles(): array {}
        public function getUri(): \Psr\Http\Message\UriInterface {}
        public function hasHeader(mixed $name): bool {}
        public function withAddedHeader(mixed $name, mixed $value): \Psr\Http\Message\ServerRequestInterface {}
        public function withAttribute(mixed $name, mixed $value): \Psr\Http\Message\ServerRequestInterface {}
        public function withBody(\Psr\Http\Message\StreamInterface $body): \Psr\Http\Message\ServerRequestInterface {}
        public function withCookieParams(array $cookies): \Psr\Http\Message\ServerRequestInterface {}
        public function withHeader(mixed $name, mixed $value): \Psr\Http\Message\ServerRequestInterface {}
        public function withMethod(mixed $method): \Psr\Http\Message\ServerRequestInterface {}
        public function withParsedBody(mixed $parsed_body): \Psr\Http\Message\ServerRequestInterface {}
        public function withProtocolVersion(mixed $version): \Psr\Http\Message\ServerRequestInterface {}
        public function withQueryParams(array $query): \Psr\Http\Message\ServerRequestInterface {}
        public function withRequestTarget(mixed $request_target): \Psr\Http\Message\ServerRequestInterface {}
        public function withUploadedFiles(mixed $uploaded_files): \Psr\Http\Message\ServerRequestInterface {}
        /**
         * @param mixed $default_preserve_host
         */
        public function withUri(\Psr\Http\Message\UriInterface $uri, $default_preserve_host = null): \Psr\Http\Message\ServerRequestInterface {}
        public function withoutAttribute(mixed $name): \Psr\Http\Message\ServerRequestInterface {}
        public function withoutHeader(mixed $name): \Psr\Http\Message\ServerRequestInterface {}
    }

    class Stream implements \Stringable
    {
        protected $content;
        protected $detached;
        protected $metadata;
        protected $position;
        public function __construct(string $default_content = '') {}
        public function __toString(): string {}
        public function close(): void {}
        public function detach(): mixed {}
        public function eof(): bool {}
        public function getContents(): string {}
        public function getMetadata(mixed $default_key = null): mixed {}
        public function getSize(): ?int {}
        public function isReadable(): bool {}
        public function isSeekable(): bool {}
        public function isWritable(): bool {}
        public function read(mixed $length): string {}
        public function rewind(): void {}
        public function seek(mixed $offset, mixed $default_whence = SEEK_SET): void {}
        public function tell(): int {}
        public function write(mixed $chunk): int {}
    }

    class UploadedFile implements \Stringable
    {
        protected $client_filename;
        protected $client_media_type;
        protected $error_code;
        protected $moved;
        protected $size_hint;
        protected $stream_ref;
        protected $target_path;
        public function __construct(mixed $default_stream, ?int $default_size, int $default_error, ?string $default_client_filename, ?string $default_client_media_type) {}
        public function __toString(): string {}
        public function getClientFilename(): ?string {}
        public function getClientMediaType(): ?string {}
        public function getError(): int {}
        public function getSize(): ?int {}
        public function getStream(): \Psr\Http\Message\StreamInterface {}
        public function moveTo(mixed $target_path): void {}
    }

    class Uri implements \Stringable
    {
        protected $fragment;
        protected $host;
        protected $password;
        protected $path;
        protected $port;
        protected $query;
        protected $scheme;
        protected $user;
        public function __construct(string $default_uri = '') {}
        public function __toString(): string {}
        public function getAuthority(): string {}
        public function getFragment(): string {}
        public function getHost(): string {}
        public function getPath(): string {}
        public function getPort(): ?int {}
        public function getQuery(): string {}
        public function getScheme(): string {}
        public function getUserInfo(): string {}
        public function withFragment(mixed $fragment): \Psr\Http\Message\UriInterface {}
        public function withHost(mixed $host): \Psr\Http\Message\UriInterface {}
        public function withPath(mixed $path): \Psr\Http\Message\UriInterface {}
        public function withPort(mixed $port): \Psr\Http\Message\UriInterface {}
        public function withQuery(mixed $query): \Psr\Http\Message\UriInterface {}
        public function withScheme(mixed $scheme): \Psr\Http\Message\UriInterface {}
        public function withUserInfo(mixed $user, mixed $default_password = ''): \Psr\Http\Message\UriInterface {}
    }
}

namespace VSlim\Session {
    class StartMiddleware
    {
        protected $app_ref;
        public function __construct() {}
        public function process(\Psr\Http\Message\ServerRequestInterface $request, \Psr\Http\Server\RequestHandlerInterface $handler): \Psr\Http\Message\ResponseInterface {}
        public function setApp($app): \VSlim\Session\StartMiddleware {}
    }

    class Store
    {
        protected $cookie_name;
        protected $destroyed;
        protected $dirty;
        protected $domain;
        protected $http_only;
        protected $loaded;
        protected $path;
        protected $same_site;
        protected $secret;
        protected $secure;
        protected $ttl_seconds;
        protected $values;
        public function __construct() {}
        public function all(): array {}
        public function clear(): \VSlim\Session\Store {}
        public function clearFlashes(): \VSlim\Session\Store {}
        public function commit(mixed $response): bool {}
        public function cookie(): string {}
        public function destroy(mixed $response): bool {}
        public function domain(): string {}
        public function flash(string $key, string $value): \VSlim\Session\Store {}
        public function forget(string $key): \VSlim\Session\Store {}
        public function get(string $key, string $default_value = ''): string {}
        public function getFlash(string $key, string $default_value = ''): string {}
        public function has(string $key): bool {}
        public function hasFlash(string $key): bool {}
        public function httpOnly(): bool {}
        public function is_loaded(): bool {}
        public function load(mixed $request): \VSlim\Session\Store {}
        public function path(): string {}
        public function pull(string $key, string $default_value = ''): string {}
        public function pullFlash(string $key, string $default_value = ''): string {}
        public function sameSite(): string {}
        public function secret(): string {}
        public function secure(): bool {}
        public function set(string $key, string $value): \VSlim\Session\Store {}
        public function setCookie(string $name): \VSlim\Session\Store {}
        public function setDomain(string $domain): \VSlim\Session\Store {}
        public function setHttpOnly(bool $http_only): \VSlim\Session\Store {}
        public function setPath(string $path): \VSlim\Session\Store {}
        public function setSameSite(string $same_site): \VSlim\Session\Store {}
        public function setSecret(string $secret): \VSlim\Session\Store {}
        public function setSecure(bool $secure): \VSlim\Session\Store {}
        public function setTtlSeconds(int $ttl_seconds): \VSlim\Session\Store {}
        public function ttlSeconds(): int {}
    }
}

namespace VSlim\Stream {
    class Factory
    {
        public function __construct() {}
        public static function ollama_sse(mixed $request_payload): mixed {}
        public static function ollama_sse_with(mixed $request_payload, mixed $options): mixed {}
        public static function ollama_text(mixed $request_payload): mixed {}
        public static function ollama_text_with(mixed $request_payload, mixed $options): mixed {}
        public static function sse(mixed $events): mixed {}
        public static function sse_with(mixed $events, int $status, mixed $headers): mixed {}
        public static function text(mixed $chunks): mixed {}
        public static function text_with(mixed $chunks, int $status, string $content_type, mixed $headers): mixed {}
    }

    class NdjsonDecoder
    {
        public function __construct() {}
        public static function decode(mixed $stream): mixed {}
    }

    class OllamaClient
    {
        protected $api_key;
        protected $chat_url;
        protected $default_model;
        protected $fixture_path;
        public function __construct(string $chat_url, string $default_model, string $api_key, string $fixture_path) {}
        public function api_key(): string {}
        public function chat_url(): string {}
        public function default_model(): string {}
        public function fixture_path(): string {}
        public static function from_app($app): \VSlim\Stream\OllamaClient {}
        public static function from_config($config): \VSlim\Stream\OllamaClient {}
        public static function from_env(): \VSlim\Stream\OllamaClient {}
        public static function from_options(mixed $options): \VSlim\Stream\OllamaClient {}
        public function open_stream(mixed $payload): mixed {}
        public function payload(mixed $input): mixed {}
        public function payload_from_request(mixed $request_payload): mixed {}
        public function sse_response_from_request(mixed $request_payload): mixed {}
        public function text_response_from_request(mixed $request_payload): mixed {}
    }

    class Response
    {
        protected $chunks_ref;
        public $content_type;
        protected $headers;
        public $status;
        public $stream_type;
        public function __construct(string $stream_type, mixed $chunks, int $status, string $content_type, mixed $headers) {}
        public function chunks(): mixed {}
        public function has_header(string $name): bool {}
        public function header(string $name): string {}
        public function headers(): array {}
        public function set_chunks(mixed $chunks): \VSlim\Stream\Response {}
        public function set_content_type(string $content_type): \VSlim\Stream\Response {}
        public function set_header(string $name, string $value): \VSlim\Stream\Response {}
        public function set_status(int $status): \VSlim\Stream\Response {}
        public static function sse(mixed $events): \VSlim\Stream\Response {}
        public static function sse_with(mixed $events, int $status, mixed $headers): \VSlim\Stream\Response {}
        public static function text(mixed $chunks): \VSlim\Stream\Response {}
        public static function text_with(mixed $chunks, int $status, string $content_type, mixed $headers): \VSlim\Stream\Response {}
    }

    class SseEncoder
    {
        public function __construct() {}
        public static function from_ollama(mixed $rows, string $model): mixed {}
    }
}

namespace VSlim\Support {
    class Module
    {
        protected $app_ref;
        public function __construct() {}
        public function app(): \VSlim\App {}
        public function hasApp(): bool {}
        public function setApp($app): \VSlim\Support\Module {}
    }

    class ServiceProvider
    {
        protected $app_ref;
        public function __construct() {}
        public function app(): \VSlim\App {}
        public function hasApp(): bool {}
        public function setApp($app): \VSlim\Support\ServiceProvider {}
    }
}

namespace VSlim\Testing {
    class Harness
    {
        protected $app_ref;
        protected $cookies;
        public function __construct() {}
        public function actingAs(string $user_id): \VSlim\Testing\Harness {}
        public function app(): \VSlim\App {}
        public function assertBodyContains(mixed $response, string $needle): \VSlim\Testing\Harness {}
        public function assertHeader(mixed $response, string $name, string $expected): \VSlim\Testing\Harness {}
        public function assertStatus(mixed $response, int $expected): \VSlim\Testing\Harness {}
        public function clearCookies(): \VSlim\Testing\Harness {}
        public function container(): \VSlim\Container {}
        public function cookies(): array {}
        public function delete(string $uri, string $body = ''): \VSlim\Vhttpd\Response {}
        public function deleteJson(string $uri, mixed $payload): \VSlim\Vhttpd\Response {}
        public function dispatch(string $method, string $uri, string $body = ''): \VSlim\Vhttpd\Response {}
        public function dispatchJson(string $method, string $uri, mixed $payload): \VSlim\Vhttpd\Response {}
        public function get(string $uri): \VSlim\Vhttpd\Response {}
        public function getJson(string $uri): \VSlim\Vhttpd\Response {}
        public function handle(\Psr\Http\Message\ServerRequestInterface $request): \Psr\Http\Message\ResponseInterface {}
        public function handleJson(string $method, string $uri, mixed $payload): \Psr\Http\Message\ResponseInterface {}
        public function handleRequest(string $method, string $uri, string $body = ''): \Psr\Http\Message\ResponseInterface {}
        public function jsonRequest(string $method, string $uri, mixed $payload): \Psr\Http\Message\ServerRequestInterface {}
        public function patch(string $uri, string $body = ''): \VSlim\Vhttpd\Response {}
        public function patchJson(string $uri, mixed $payload): \VSlim\Vhttpd\Response {}
        public function post(string $uri, string $body = ''): \VSlim\Vhttpd\Response {}
        public function postJson(string $uri, mixed $payload): \VSlim\Vhttpd\Response {}
        public function put(string $uri, string $body = ''): \VSlim\Vhttpd\Response {}
        public function putJson(string $uri, mixed $payload): \VSlim\Vhttpd\Response {}
        public function request(string $method, string $uri, string $body = ''): \Psr\Http\Message\ServerRequestInterface {}
        public function responseBody(mixed $response): string {}
        public function responseHeader(mixed $response, string $name): string {}
        public function responseJson(mixed $response): mixed {}
        public function responseStatus(mixed $response): int {}
        public function setApp($app): \VSlim\Testing\Harness {}
        public function withConfig(string $path): \VSlim\Testing\Harness {}
        public function withConfigText(string $text): \VSlim\Testing\Harness {}
        public function withCookie(string $name, string $value): \VSlim\Testing\Harness {}
        public function withFactory(string $id, mixed $callable): \VSlim\Testing\Harness {}
        public function withService(string $id, mixed $value): \VSlim\Testing\Harness {}
        public function withSession(mixed $values): \VSlim\Testing\Harness {}
        public function withoutCookie(string $name): \VSlim\Testing\Harness {}
    }
}

namespace VSlim\Validate {
    class Validator
    {
        protected $error_map;
        protected $input_data;
        protected $rule_map;
        protected $validated_data;
        protected $validation_ran;
        public function __construct() {}
        public function data(): mixed {}
        public function errors(): mixed {}
        public function fails(): bool {}
        public static function make(mixed $data, mixed $rules): \VSlim\Validate\Validator {}
        public function passes(): bool {}
        public function setData(mixed $data): \VSlim\Validate\Validator {}
        public function setRules(mixed $rules): \VSlim\Validate\Validator {}
        public function validate(): \VSlim\Validate\Validator {}
        public function validated(): mixed {}
    }
}

namespace VSlim\Vhttpd {
    class Client
    {
        protected $connect_timeout_seconds;
        protected $socket_path;
        public function __construct(string $socket_path, float $connect_timeout_seconds) {}
        public function connectTimeoutSeconds(): float {}
        public function request(mixed $payload): mixed {}
        public function requestFrames(mixed $payload, array $frames = []): mixed {}
        public function socketPath(): string {}
    }

    class Request implements \Stringable
    {
        protected $attributes;
        public $body;
        protected $cookies;
        protected $headers;
        public $host;
        public $method;
        protected $params;
        public $path;
        public $port;
        public $protocol_version;
        protected $query;
        public $query_string;
        public $raw_path;
        public $remote_addr;
        public $scheme;
        protected $server;
        protected $uploaded_files;
        public function __construct(string $method, string $raw_path, string $body) {}
        public function __toString(): string {}
        public function all_inputs(): array {}
        public function attribute(string $name): string {}
        public function attributes(): array {}
        public function attributes_all(): array {}
        public function body_format(): string {}
        public function content_type(): string {}
        public function cookie(string $name): string {}
        public function cookies(): array {}
        public function cookies_all(): array {}
        public function form_body(): array {}
        public function has_attribute(string $name): bool {}
        public function has_cookie(string $name): bool {}
        public function has_header(string $name): bool {}
        public function has_input(string $key): bool {}
        public function has_param(string $name): bool {}
        public function has_query(string $key): bool {}
        public function has_server(string $name): bool {}
        public function has_uploaded_files(): bool {}
        public function header(string $name): string {}
        public function headers(): array {}
        public function headers_all(): array {}
        public function input(string $key): string {}
        public function input_or(string $key, string $default_value = ''): string {}
        public function is_form_body(): bool {}
        public function is_json_body(): bool {}
        public function is_multipart_body(): bool {}
        public function is_secure(): bool {}
        public function json_body(): array {}
        public function multipart_body(): array {}
        public function param(string $name): string {}
        public function params_all(): array {}
        public function parse_error(): string {}
        public function parsed_body(): array {}
        public function query(string $key): string {}
        public function query_all(): array {}
        public function query_params(): array {}
        public function request_id(): string {}
        public function route_params(): array {}
        public function server_all(): array {}
        public function server_params(): array {}
        public function server_value(string $name): string {}
        public function set_attributes(mixed $attributes): \VSlim\Vhttpd\Request {}
        public function set_body(string $body): \VSlim\Vhttpd\Request {}
        public function set_cookies(mixed $cookies): \VSlim\Vhttpd\Request {}
        public function set_headers(mixed $headers): \VSlim\Vhttpd\Request {}
        public function set_host(string $host): \VSlim\Vhttpd\Request {}
        public function set_method(string $method): \VSlim\Vhttpd\Request {}
        public function set_params(mixed $params): \VSlim\Vhttpd\Request {}
        public function set_port(string $port): \VSlim\Vhttpd\Request {}
        public function set_protocol_version(string $protocol_version): \VSlim\Vhttpd\Request {}
        public function set_query(mixed $query): \VSlim\Vhttpd\Request {}
        public function set_remote_addr(string $remote_addr): \VSlim\Vhttpd\Request {}
        public function set_scheme(string $scheme): \VSlim\Vhttpd\Request {}
        public function set_server(mixed $server): \VSlim\Vhttpd\Request {}
        public function set_target(string $raw_path): \VSlim\Vhttpd\Request {}
        public function set_uploaded_files(mixed $uploaded_files): \VSlim\Vhttpd\Request {}
        public function trace_id(): string {}
        public function uploaded_file_count(): int {}
        public function uploaded_files(): array {}
        public function uploaded_files_all(): array {}
    }

    class Response implements \Stringable
    {
        public $body;
        public $content_type;
        protected $headers;
        public $status;
        public function __construct(int $status, string $body, string $content_type) {}
        public function __toString(): string {}
        public function content_length(): int {}
        public function cookie_header(): string {}
        public function delete_cookie(string $name): \VSlim\Vhttpd\Response {}
        public function has_header(string $name): bool {}
        public function header(string $name): string {}
        public function headers(): array {}
        public function headers_all(): array {}
        public function html(string $body): \VSlim\Vhttpd\Response {}
        public function json(string $body): \VSlim\Vhttpd\Response {}
        public function redirect(string $location): \VSlim\Vhttpd\Response {}
        public function redirect_with_status(string $location, int $status): \VSlim\Vhttpd\Response {}
        public function set_content_type(string $content_type): \VSlim\Vhttpd\Response {}
        public function set_cookie(string $name, string $value): \VSlim\Vhttpd\Response {}
        public function set_cookie_full(string $name, string $value, string $path, string $domain, int $max_age, bool $secure, bool $http_only, string $same_site): \VSlim\Vhttpd\Response {}
        public function set_cookie_opts(string $name, string $value, string $path): \VSlim\Vhttpd\Response {}
        public function set_header(string $name, string $value): \VSlim\Vhttpd\Response {}
        public function set_status(int $status): \VSlim\Vhttpd\Response {}
        public function text(string $body): \VSlim\Vhttpd\Response {}
        public function with_request_id(string $request_id): \VSlim\Vhttpd\Response {}
        public function with_status(int $status): \VSlim\Vhttpd\Response {}
        public function with_trace_id(string $trace_id): \VSlim\Vhttpd\Response {}
    }
}

namespace VSlim\WebSocket {
    class App
    {
        protected $connections;
        protected $on_close_handler;
        protected $on_message_handler;
        protected $on_open_handler;
        protected $rooms;
        public function __construct() {}
        public function broadcast(string $data, string $room, string $except_id): int {}
        public function connection_ids(): array {}
        public function forget(mixed $conn_or_id): \VSlim\WebSocket\App {}
        public function handle_websocket(mixed $frame, mixed $conn): mixed {}
        public function has_connection(mixed $conn_or_id): bool {}
        public function has_on_close(): bool {}
        public function has_on_message(): bool {}
        public function has_on_open(): bool {}
        public function join(string $room, mixed $conn_or_id): \VSlim\WebSocket\App {}
        public function leave(string $room, mixed $conn_or_id): \VSlim\WebSocket\App {}
        public function members(string $room): array {}
        public function on_close(mixed $handler): \VSlim\WebSocket\App {}
        public function on_message(mixed $handler): \VSlim\WebSocket\App {}
        public function on_open(mixed $handler): \VSlim\WebSocket\App {}
        public function remember(mixed $conn): \VSlim\WebSocket\App {}
        public function rooms_for(mixed $conn_or_id): array {}
        public function send_to(mixed $conn_or_id, string $data): bool {}
    }
}
