import rt

pub fn Class_Automattic_WooCommerce_Internal_Api_Main.feature_slug() string {
	return 'dual_code_graphql_api'
}
pub fn Class_Automattic_WooCommerce_Internal_Api_Main.option_get_endpoint_enabled() string {
	return 'woocommerce_graphql_get_endpoint_enabled'
}
struct Class_Automattic_WooCommerce_Internal_Api_Main {
	rt.PhpObjectBase
}

fn Class_Automattic_WooCommerce_Internal_Api_Main.is_enabled() bool {
	return rt.is_true(rt.greater_equal(rt.get_constant('PHP_VERSION_ID'), rt.new_int(80100))) && rt.is_true(fn (arg_0 rt.PhpVal) rt.PhpVal { mut temp := Class_Automattic_WooCommerce_Utilities_FeaturesUtil{}; return temp.feature_is_enabled(arg_0) }(Class_Automattic_WooCommerce_Internal_Api_Automattic_WooCommerce_Internal_Api_Main.feature_slug()))
}

fn Class_Automattic_WooCommerce_Internal_Api_Main.is_get_endpoint_enabled() bool {
	return (rt.call_function('wc_string_to_bool', [rt.call_function('get_option', [Class_Automattic_WooCommerce_Internal_Api_Automattic_WooCommerce_Internal_Api_Main.option_get_endpoint_enabled(), rt.new_string('yes')])])).to_bool()
}

fn Class_Automattic_WooCommerce_Internal_Api_Main.filter_methods_against_settings(mut var_methods Class_Automattic_WooCommerce_Internal_Api_array) rt.PhpVal {
	mut var_methods_mutated := var_methods
	if rt.is_true(rt.new_bool(!(rt.is_true(Class_Automattic_WooCommerce_Internal_Api_Main.is_get_endpoint_enabled())))) {
		var_methods_mutated = rt.call_function('array_values', [rt.call_function('array_diff', [var_methods_mutated.dup(), rt.create_array([rt.ArrayItem{ key: none, val: 'GET' }])])])
	}
	return rt.new_object('Automattic_WooCommerce_Internal_Api_array', []string{}, var_methods_mutated)
}

fn Class_Automattic_WooCommerce_Internal_Api_Main.register()  {
	rt.call_function('add_action', [rt.new_string('rest_api_init'), rt.create_array([rt.ArrayItem{ key: none, val: Class_Automattic_WooCommerce_Internal_Api_Automattic_WooCommerce_Internal_Api_Main.class() }, rt.ArrayItem{ key: none, val: 'handle_rest_api_init_for_core' }])])
	mut var_settings := rt.call_method(rt.call_function('wc_get_container', []rt.PhpVal{}), 'get', [Class_Automattic_WooCommerce_Internal_Api_Settings.class()])
	rt.call_method(var_settings, 'register', []rt.PhpVal{})
}

fn Class_Automattic_WooCommerce_Internal_Api_Main.handle_rest_api_init_for_core()  {
	if rt.is_true(rt.new_bool(!(rt.is_true(Class_Automattic_WooCommerce_Internal_Api_Main.is_enabled())))) {
		return rt.new_null()
	}
	rt.call_method(rt.call_method(rt.call_function('wc_get_container', []rt.PhpVal{}), 'get', [Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLController.class()]), 'register', []rt.PhpVal{})
}

fn Class_Automattic_WooCommerce_Internal_Api_Main.instantiate_graphql_controller(controller_class_name string) rt.PhpVal {
	mut controller_class_name_mutated := controller_class_name
	if rt.is_true(rt.new_bool(!(rt.is_true(Class_Automattic_WooCommerce_Internal_Api_Main.is_enabled())))) {
		return rt.new_null()
	}
	Class_Automattic_WooCommerce_Internal_Api_Main.assert_is_controller_subclass(controller_class_name_mutated)
	mut var_controller := rt.create_object_dynamically(controller_class_name_mutated, []rt.PhpVal{})
	rt.call_method(var_controller, 'init', [rt.call_method(rt.call_function('wc_get_container', []rt.PhpVal{}), 'get', [Class_Automattic_WooCommerce_Internal_Api_QueryCache.class()])])
	return var_controller.dup()
}

fn Class_Automattic_WooCommerce_Internal_Api_Main.register_graphql_endpoint(plugin_dir_or_controller_class string, route_namespace string, route string, mut var_methods Class_Automattic_WooCommerce_Internal_Api_array)  {
	mut var_methods_mutated := var_methods
	if rt.is_true(rt.new_bool(!(rt.is_true(Class_Automattic_WooCommerce_Internal_Api_Main.is_enabled())))) {
		return rt.new_null()
	}
	mut var_controller_class_name := Class_Automattic_WooCommerce_Internal_Api_Main.resolve_controller_class(plugin_dir_or_controller_class)
	Class_Automattic_WooCommerce_Internal_Api_Main.assert_is_controller_subclass((var_controller_class_name).str())
	mut var_registrar := create_automattic_woocommerce_internal_api_graphqlendpointregistrar(var_controller_class_name.dup(), rt.new_string(route_namespace).dup(), rt.new_string(route).dup(), var_methods_mutated.dup())
	if rt.is_true(rt.call_function('did_action', [rt.new_string('rest_api_init')])) {
		var_registrar.handle_rest_api_init()
	} else {
		rt.call_function('add_action', [rt.new_string('rest_api_init'), rt.create_array([rt.ArrayItem{ key: none, val: var_registrar }, rt.ArrayItem{ key: none, val: 'handle_rest_api_init' }])])
	}
}

fn Class_Automattic_WooCommerce_Internal_Api_Main.resolve_controller_class(arg string) string {
	if rt.is_true(rt.new_bool(!(rt.is_true(rt.call_function('is_dir', [rt.new_string(arg)]))))) {
		return arg
	}
	mut var_controller_file := rt.new_string(arg.trim_right(' \t\n\r') + '/src/Internal/Api/Autogenerated/GraphQLController.php')
	if rt.is_true(rt.new_bool(!(rt.is_true(rt.call_function('is_file', [var_controller_file.dup()]))))) {
		rt.throw_exception(rt.new_object('Automattic_WooCommerce_Internal_Api_InvalidArgumentException', []string{}, create_automattic_woocommerce_internal_api_invalidargumentexception(rt.call_function('sprintf', [rt.new_string('Expected a generated GraphQL controller at %s, but the file does not exist. Run the plugin\'s API build script first, or pass an explicit controller class name.'), rt.call_function('esc_html', [var_controller_file.dup()])]))))
	}
	mut var_head := rt.call_function('file_get_contents', [var_controller_file.dup(), rt.new_bool(false), rt.new_null(), rt.new_int(0), rt.new_int(4096)])
	if rt.is_true(rt.identical(rt.new_bool(false), var_head)) {
		rt.throw_exception(rt.new_object('Automattic_WooCommerce_Internal_Api_InvalidArgumentException', []string{}, create_automattic_woocommerce_internal_api_invalidargumentexception(rt.call_function('sprintf', [rt.new_string('Could not read the controller file at %s.'), rt.call_function('esc_html', [var_controller_file.dup()])]))))
	}
	mut var_namespace := Class_Automattic_WooCommerce_Internal_Api_Main.extract_namespace_from_php_source((var_head).str())
	if rt.is_true(rt.identical(rt.new_null(), var_namespace)) {
		rt.throw_exception(rt.new_object('Automattic_WooCommerce_Internal_Api_InvalidArgumentException', []string{}, create_automattic_woocommerce_internal_api_invalidargumentexception(rt.call_function('sprintf', [rt.new_string('Could not determine the PHP namespace of the controller at %s.'), rt.call_function('esc_html', [var_controller_file.dup()])]))))
	}
	return (var_namespace).str() + '\\GraphQLController'
}

fn Class_Automattic_WooCommerce_Internal_Api_Main.extract_namespace_from_php_source(source string) string {
	mut var_tokens := rt.call_function('token_get_all', [rt.new_string(source)])
	mut var_count := rt.new_int(rt.new_int(var_tokens.dup().array_count()))
	{
		mut var_i := rt.new_int(rt.new_int(0))
		for {
			if !(rt.is_true(rt.less(var_i, var_count))) { break }
			if rt.is_true(rt.new_bool(rt.is_true(rt.new_bool(!(rt.is_true(rt.new_bool(var_tokens.array_get(var_i).is_array()))))) || rt.is_true(// unsupported expression: Expr_BinaryOp_NotIdentical))) {
				continue
			}
			mut var_namespace := rt.new_string(rt.new_string(''))
			{
				mut var_j := rt.add(var_i, rt.new_int(1))
				for {
					if !(rt.is_true(rt.less(var_j, var_count))) { break }
					mut var_token := var_tokens.array_get(var_j)
					if rt.is_true(rt.new_bool(var_token.dup().is_array())) {
						if rt.is_true(rt.new_bool(rt.is_true(rt.new_bool(rt.is_true(rt.call_function('in_array', [var_token.array_get(0), rt.create_array([rt.ArrayItem{ key: none, val: rt.get_constant('T_STRING') }, rt.ArrayItem{ key: none, val: rt.get_constant('T_NS_SEPARATOR') }]), rt.new_bool(true)])) || rt.is_true(rt.new_bool(rt.is_true(rt.call_function('defined', [rt.new_string('T_NAME_QUALIFIED')])) && rt.is_true(rt.identical(rt.get_constant('T_NAME_QUALIFIED'), var_token.array_get(0))))))) || rt.is_true(rt.new_bool(rt.is_true(rt.call_function('defined', [rt.new_string('T_NAME_FULLY_QUALIFIED')])) && rt.is_true(rt.identical(rt.get_constant('T_NAME_FULLY_QUALIFIED'), var_token.array_get(0))))))) {
							// unsupported expression: Expr_AssignOp_Concat
							continue
						}
						if rt.is_true(rt.identical(rt.get_constant('T_WHITESPACE'), var_token.array_get(0))) {
							continue
						}
					}
					break
					rt.post_inc(var_j)
				}
			}
			var_namespace = rt.new_string(rt.new_string(var_namespace.dup().to_string().trim_space()))
			if rt.is_true(// unsupported expression: Expr_BinaryOp_NotIdentical) {
				return (var_namespace).str()
			}
			rt.post_inc(var_i)
		}
	}
	return (rt.new_null()).str()
}

fn Class_Automattic_WooCommerce_Internal_Api_Main.assert_is_controller_subclass(controller_class_name string)  {
	mut controller_class_name_mutated := controller_class_name
	if rt.is_true(rt.new_bool(!(rt.is_true(rt.call_function('class_exists', [rt.new_string(controller_class_name_mutated).dup()]))))) {
		rt.throw_exception(rt.new_object('Automattic_WooCommerce_Internal_Api_InvalidArgumentException', []string{}, create_automattic_woocommerce_internal_api_invalidargumentexception(rt.call_function('sprintf', [rt.new_string('GraphQL controller class "%s" does not exist or is not autoloadable. Check the spelling, or run `composer dump-autoload` if it was added since the last autoloader regeneration.'), rt.call_function('esc_html', [rt.new_string(controller_class_name_mutated).dup()])]))))
	}
	if rt.is_true(rt.new_bool(!(rt.is_true(rt.call_function('is_subclass_of', [rt.new_string(controller_class_name_mutated).dup(), Class_Automattic_WooCommerce_Internal_Api_GraphQLController.class()]))))) {
		rt.throw_exception(rt.new_object('Automattic_WooCommerce_Internal_Api_InvalidArgumentException', []string{}, create_automattic_woocommerce_internal_api_invalidargumentexception(rt.call_function('sprintf', [rt.new_string('Class "%s" must extend %s.'), rt.call_function('esc_html', [rt.new_string(controller_class_name_mutated).dup()]), rt.call_function('esc_html', [Class_Automattic_WooCommerce_Internal_Api_GraphQLController.class()])]))))
	}
}

struct Class_Automattic_WooCommerce_Utilities_FeaturesUtil {
	rt.PhpObjectBase
}

struct Class_Automattic_WooCommerce_Internal_Api_GraphQLEndpointRegistrar {
	rt.PhpObjectBase
}

struct Class_Automattic_WooCommerce_Internal_Api_InvalidArgumentException {
	rt.PhpObjectBase
}

fn create_automattic_woocommerce_internal_api_main() &Class_Automattic_WooCommerce_Internal_Api_Main {
	mut obj := &Class_Automattic_WooCommerce_Internal_Api_Main{
		PhpObjectBase: rt.PhpObjectBase{}
	}
	return obj
}

fn create_automattic_woocommerce_utilities_featuresutil() &Class_Automattic_WooCommerce_Utilities_FeaturesUtil {
	mut obj := &Class_Automattic_WooCommerce_Utilities_FeaturesUtil{
		PhpObjectBase: rt.PhpObjectBase{}
	}
	return obj
}

fn create_automattic_woocommerce_internal_api_graphqlendpointregistrar() &Class_Automattic_WooCommerce_Internal_Api_GraphQLEndpointRegistrar {
	mut obj := &Class_Automattic_WooCommerce_Internal_Api_GraphQLEndpointRegistrar{
		PhpObjectBase: rt.PhpObjectBase{}
	}
	return obj
}

fn create_automattic_woocommerce_internal_api_invalidargumentexception() &Class_Automattic_WooCommerce_Internal_Api_InvalidArgumentException {
	mut obj := &Class_Automattic_WooCommerce_Internal_Api_InvalidArgumentException{
		PhpObjectBase: rt.PhpObjectBase{}
	}
	return obj
}

fn (mut this Class_Automattic_WooCommerce_Internal_Api_Main) dispatch_method(method_name string, args []rt.PhpVal) ?rt.PhpVal {
	match method_name {
		'is_enabled' {
			return rt.new_bool(Class_Automattic_WooCommerce_Internal_Api_Main.is_enabled())
		}
		'is_get_endpoint_enabled' {
			return rt.new_bool(Class_Automattic_WooCommerce_Internal_Api_Main.is_get_endpoint_enabled())
		}
		'filter_methods_against_settings' {
			mut dispatch_arg_0 := rt.cast_object_ptr[Class_Automattic_WooCommerce_Internal_Api_array](if args.len > 0 { args[0] } else { rt.new_null() })
			return Class_Automattic_WooCommerce_Internal_Api_Main.filter_methods_against_settings(mut dispatch_arg_0)
		}
		'register' {
			Class_Automattic_WooCommerce_Internal_Api_Main.register()
			return rt.new_null()
		}
		'handle_rest_api_init_for_core' {
			Class_Automattic_WooCommerce_Internal_Api_Main.handle_rest_api_init_for_core()
			return rt.new_null()
		}
		'instantiate_graphql_controller' {
			dispatch_arg_0 := (if args.len > 0 { args[0] } else { rt.new_null() }).str()
			return Class_Automattic_WooCommerce_Internal_Api_Main.instantiate_graphql_controller(dispatch_arg_0)
		}
		'register_graphql_endpoint' {
			dispatch_arg_0 := (if args.len > 0 { args[0] } else { rt.new_null() }).str()
			dispatch_arg_1 := (if args.len > 1 { args[1] } else { rt.new_null() }).str()
			dispatch_arg_2 := (if args.len > 2 { args[2] } else { rt.new_null() }).str()
			mut dispatch_arg_3 := rt.cast_object_ptr[Class_Automattic_WooCommerce_Internal_Api_array](if args.len > 3 { args[3] } else { rt.new_null() })
			Class_Automattic_WooCommerce_Internal_Api_Main.register_graphql_endpoint(dispatch_arg_0, dispatch_arg_1, dispatch_arg_2, mut dispatch_arg_3)
			return rt.new_null()
		}
		'resolve_controller_class' {
			dispatch_arg_0 := (if args.len > 0 { args[0] } else { rt.new_null() }).str()
			return rt.new_string(Class_Automattic_WooCommerce_Internal_Api_Main.resolve_controller_class(dispatch_arg_0))
		}
		'extract_namespace_from_php_source' {
			dispatch_arg_0 := (if args.len > 0 { args[0] } else { rt.new_null() }).str()
			return rt.new_string(Class_Automattic_WooCommerce_Internal_Api_Main.extract_namespace_from_php_source(dispatch_arg_0))
		}
		'assert_is_controller_subclass' {
			dispatch_arg_0 := (if args.len > 0 { args[0] } else { rt.new_null() }).str()
			Class_Automattic_WooCommerce_Internal_Api_Main.assert_is_controller_subclass(dispatch_arg_0)
			return rt.new_null()
		}
		else { return none }
	}
}

fn (this &Class_Automattic_WooCommerce_Internal_Api_Main) dispatch_get_prop(prop_name string) ?rt.PhpVal {
	return this.PhpObjectBase.dispatch_get_prop(prop_name)
}

fn (mut this Class_Automattic_WooCommerce_Internal_Api_Main) dispatch_set_prop(prop_name string, val rt.PhpVal) bool {
	return this.PhpObjectBase.dispatch_set_prop(prop_name, val)
}


fn (mut this Class_Automattic_WooCommerce_Utilities_FeaturesUtil) dispatch_method(method_name string, args []rt.PhpVal) ?rt.PhpVal {
	return none
}

fn (this &Class_Automattic_WooCommerce_Utilities_FeaturesUtil) dispatch_get_prop(prop_name string) ?rt.PhpVal {
	return this.PhpObjectBase.dispatch_get_prop(prop_name)
}

fn (mut this Class_Automattic_WooCommerce_Utilities_FeaturesUtil) dispatch_set_prop(prop_name string, val rt.PhpVal) bool {
	return this.PhpObjectBase.dispatch_set_prop(prop_name, val)
}


fn (mut this Class_Automattic_WooCommerce_Internal_Api_GraphQLEndpointRegistrar) dispatch_method(method_name string, args []rt.PhpVal) ?rt.PhpVal {
	return none
}

fn (this &Class_Automattic_WooCommerce_Internal_Api_GraphQLEndpointRegistrar) dispatch_get_prop(prop_name string) ?rt.PhpVal {
	return this.PhpObjectBase.dispatch_get_prop(prop_name)
}

fn (mut this Class_Automattic_WooCommerce_Internal_Api_GraphQLEndpointRegistrar) dispatch_set_prop(prop_name string, val rt.PhpVal) bool {
	return this.PhpObjectBase.dispatch_set_prop(prop_name, val)
}


fn (mut this Class_Automattic_WooCommerce_Internal_Api_InvalidArgumentException) dispatch_method(method_name string, args []rt.PhpVal) ?rt.PhpVal {
	return none
}

fn (this &Class_Automattic_WooCommerce_Internal_Api_InvalidArgumentException) dispatch_get_prop(prop_name string) ?rt.PhpVal {
	return this.PhpObjectBase.dispatch_get_prop(prop_name)
}

fn (mut this Class_Automattic_WooCommerce_Internal_Api_InvalidArgumentException) dispatch_set_prop(prop_name string, val rt.PhpVal) bool {
	return this.PhpObjectBase.dispatch_set_prop(prop_name, val)
}


fn init_registry() {
	rt.register_class_factory('Automattic_WooCommerce_Internal_Api_Main', fn(args []rt.PhpVal) rt.PhpVal {
		obj := create_automattic_woocommerce_internal_api_main()
		return rt.new_object('Automattic_WooCommerce_Internal_Api_Main', []string{}, obj)
	})
	rt.register_class_factory('Automattic_WooCommerce_Utilities_FeaturesUtil', fn(args []rt.PhpVal) rt.PhpVal {
		obj := create_automattic_woocommerce_utilities_featuresutil()
		return rt.new_object('Automattic_WooCommerce_Utilities_FeaturesUtil', []string{}, obj)
	})
	rt.register_class_factory('Automattic_WooCommerce_Internal_Api_GraphQLEndpointRegistrar', fn(args []rt.PhpVal) rt.PhpVal {
		obj := create_automattic_woocommerce_internal_api_graphqlendpointregistrar()
		return rt.new_object('Automattic_WooCommerce_Internal_Api_GraphQLEndpointRegistrar', []string{}, obj)
	})
	rt.register_class_factory('Automattic_WooCommerce_Internal_Api_InvalidArgumentException', fn(args []rt.PhpVal) rt.PhpVal {
		obj := create_automattic_woocommerce_internal_api_invalidargumentexception()
		return rt.new_object('Automattic_WooCommerce_Internal_Api_InvalidArgumentException', []string{}, obj)
	})
}

fn init() {
	init_registry()
}



pub fn init_wp_content_plugins_woocommerce_src_internal_api_main_php() {
	// unsupported statement: Stmt_Declare
}
