import rt

struct Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Interfaces_ObjectWithId {
	rt.PhpObjectBase
}

fn init_static_automattic_woocommerce_internal_api_autogenerated_graphqltypes_interfaces_objectwithid() {
	rt.init_static_prop('Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Interfaces_ObjectWithId',
		'instance', rt.new_null())
}

fn Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Interfaces_ObjectWithId.get() rt.PhpVal {
	if rt.is_true(rt.identical(rt.new_null(), rt.get_static_prop('Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Interfaces_ObjectWithId',
		'instance')))
	{
		closure_3_fn := fn (this_ptr rt.PhpVal, args []rt.PhpVal) rt.PhpVal {
			mut iife_temp_1 := Class_Automattic_WooCommerce_Internal_Api_Schema_Type{}
			mut iife_result_1 := iife_temp_1.int()
			mut iife_temp_2 := Class_Automattic_WooCommerce_Internal_Api_Schema_Type{}
			mut iife_result_2 := iife_temp_2.nonnull(iife_result_1)
			return rt.create_array([
				rt.ArrayItem{ key: 'id', val: rt.create_array([
					rt.ArrayItem{ key: 'type', val: iife_result_2 },
					rt.ArrayItem{ key: 'description', val: rt.call_function('__', [
						rt.new_string('The unique numeric identifier.'),
						rt.new_string('woocommerce'),
					]) },
				]) },
			])
		}
		closure_5_fn := fn (this_ptr rt.PhpVal, args []rt.PhpVal) rt.PhpVal {
			mut var_value := if args.len > 0 { args[0].clone() } else { rt.new_null() }
			mut var_class := rt.call_function('get_class', [var_value.clone()])
			mut iife_temp_4 :=
				Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Output_Coupon{}
			mut iife_result_4 := iife_temp_4.get()
			mut var_map := rt.create_array([
				rt.ArrayItem{
					key: 'Automattic\\WooCommerce\\Api\\Types\\Coupons\\Coupon'
					val: iife_result_4
				},
			])
			return if !(var_map.array_get(var_class)).is_null() {
				var_map.array_get(var_class)
			} else {
				rt.new_null()
			}
		}
		rt.set_static_prop('Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Interfaces_ObjectWithId',
			'instance', rt.new_object('Automattic_WooCommerce_Internal_Api_Schema_InterfaceType',
			[]string{}, create_automattic_woocommerce_internal_api_schema_interfacetype(rt.create_array([
			rt.ArrayItem{ key: 'name', val: 'ObjectWithId' },
			rt.ArrayItem{ key: 'description', val: rt.call_function('__', [
				rt.new_string('An object with a numeric ID.'),
				rt.new_string('woocommerce'),
			]) },
			rt.ArrayItem{ key: 'fields', val: rt.new_closure(closure_3_fn) },
			rt.ArrayItem{ key: 'resolveType', val: rt.new_closure(closure_5_fn) },
		]))))
	}
	return rt.get_static_prop('Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Interfaces_ObjectWithId',
		'instance')
}

struct Class_Automattic_WooCommerce_Internal_Api_Schema_InterfaceType {
	rt.PhpObjectBase
}

struct Class_Automattic_WooCommerce_Internal_Api_Schema_Type {
	rt.PhpObjectBase
}

struct Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Output_Coupon {
	rt.PhpObjectBase
}

fn create_automattic_woocommerce_internal_api_autogenerated_graphqltypes_interfaces_objectwithid(_args ...rt.PhpVal) &Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Interfaces_ObjectWithId {
	mut obj := &Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Interfaces_ObjectWithId{
		PhpObjectBase: rt.PhpObjectBase{}
	}
	return obj
}

fn create_automattic_woocommerce_internal_api_schema_interfacetype(_args ...rt.PhpVal) &Class_Automattic_WooCommerce_Internal_Api_Schema_InterfaceType {
	mut obj := &Class_Automattic_WooCommerce_Internal_Api_Schema_InterfaceType{
		PhpObjectBase: rt.PhpObjectBase{}
	}
	return obj
}

fn create_automattic_woocommerce_internal_api_schema_type(_args ...rt.PhpVal) &Class_Automattic_WooCommerce_Internal_Api_Schema_Type {
	mut obj := &Class_Automattic_WooCommerce_Internal_Api_Schema_Type{
		PhpObjectBase: rt.PhpObjectBase{}
	}
	return obj
}

fn create_automattic_woocommerce_internal_api_autogenerated_graphqltypes_output_coupon(_args ...rt.PhpVal) &Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Output_Coupon {
	mut obj := &Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Output_Coupon{
		PhpObjectBase: rt.PhpObjectBase{}
	}
	return obj
}

fn (mut this Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Interfaces_ObjectWithId) dispatch_method(method_name string, args []rt.PhpVal) ?rt.PhpVal {
	match method_name {
		'get' {
			return Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Interfaces_ObjectWithId.get()
		}
		else {
			return none
		}
	}
}

fn (this &Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Interfaces_ObjectWithId) dispatch_get_prop(prop_name string) ?rt.PhpVal {
	return this.PhpObjectBase.dispatch_get_prop(prop_name)
}

fn (mut this Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Interfaces_ObjectWithId) dispatch_set_prop(prop_name string, val rt.PhpVal) bool {
	return this.PhpObjectBase.dispatch_set_prop(prop_name, val)
}

fn (mut this Class_Automattic_WooCommerce_Internal_Api_Schema_InterfaceType) dispatch_method(method_name string, args []rt.PhpVal) ?rt.PhpVal {
	return none
}

fn (this &Class_Automattic_WooCommerce_Internal_Api_Schema_InterfaceType) dispatch_get_prop(prop_name string) ?rt.PhpVal {
	return this.PhpObjectBase.dispatch_get_prop(prop_name)
}

fn (mut this Class_Automattic_WooCommerce_Internal_Api_Schema_InterfaceType) dispatch_set_prop(prop_name string, val rt.PhpVal) bool {
	return this.PhpObjectBase.dispatch_set_prop(prop_name, val)
}

fn (mut this Class_Automattic_WooCommerce_Internal_Api_Schema_Type) dispatch_method(method_name string, args []rt.PhpVal) ?rt.PhpVal {
	return none
}

fn (this &Class_Automattic_WooCommerce_Internal_Api_Schema_Type) dispatch_get_prop(prop_name string) ?rt.PhpVal {
	return this.PhpObjectBase.dispatch_get_prop(prop_name)
}

fn (mut this Class_Automattic_WooCommerce_Internal_Api_Schema_Type) dispatch_set_prop(prop_name string, val rt.PhpVal) bool {
	return this.PhpObjectBase.dispatch_set_prop(prop_name, val)
}

fn (mut this Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Output_Coupon) dispatch_method(method_name string, args []rt.PhpVal) ?rt.PhpVal {
	return none
}

fn (this &Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Output_Coupon) dispatch_get_prop(prop_name string) ?rt.PhpVal {
	return this.PhpObjectBase.dispatch_get_prop(prop_name)
}

fn (mut this Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Output_Coupon) dispatch_set_prop(prop_name string, val rt.PhpVal) bool {
	return this.PhpObjectBase.dispatch_set_prop(prop_name, val)
}

fn main() {
	defer {
		rt.shutdown()
	}
}
