import rt

struct Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLQueries_GetProduct {
	rt.PhpObjectBase
}

fn Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLQueries_GetProduct.get_field_definition() rt.PhpVal {
	mut iife_temp_0 :=
		Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Interfaces_Product{}
	mut iife_result_0 := iife_temp_0.get()
	mut iife_temp_1 := Class_Automattic_WooCommerce_Internal_Api_Schema_Type{}
	mut iife_result_1 := iife_temp_1.int()
	mut iife_temp_2 := Class_Automattic_WooCommerce_Internal_Api_Schema_Type{}
	mut iife_result_2 := iife_temp_2.nonnull(iife_result_1)
	return rt.create_array([rt.ArrayItem{ key: 'type', val: iife_result_0 },
		rt.ArrayItem{ key: 'description', val: rt.call_function('__', [
			rt.new_string('Retrieve a single product by ID.'),
			rt.new_string('woocommerce'),
		]) }, rt.ArrayItem{ key: 'args', val: rt.create_array([
			rt.ArrayItem{ key: 'id', val: rt.create_array([
				rt.ArrayItem{ key: 'type', val: iife_result_2 },
				rt.ArrayItem{ key: 'description', val: rt.call_function('__', [
					rt.new_string('The ID of the product to retrieve.'),
					rt.new_string('woocommerce'),
				]) },
			]) },
		]) }, rt.ArrayItem{ key: 'resolve', val: rt.create_array([
			rt.ArrayItem{
				key: none
				val: Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLQueries_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLQueries_GetProduct.class()
			},
			rt.ArrayItem{ key: none, val: 'resolve' },
		]) }])
}

fn Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLQueries_GetProduct.resolve(mut var_root Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLQueries_mixed, mut var_args Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLQueries_array, mut var_context Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLQueries_mixed, mut var_info Class_Automattic_WooCommerce_Internal_Api_Schema_ResolveInfo) rt.PhpVal {
	mut iife_temp_3 :=
		Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLQueries_Automattic_WooCommerce_Api_Container{}
	mut iife_result_3 :=
		iife_temp_3.get(Class_Automattic_WooCommerce_Api_Queries_Products_GetProduct.class())
	mut var_command := iife_result_3
	mut var_execute_args := rt.new_array()
	if rt.is_true(rt.new_bool(var_args.array_isset(rt.new_string('id')))) {
		var_execute_args.array_set('id', var_args.array_get(rt.new_string('id')))
	}
	mut iife_temp_4 := Class_Automattic_WooCommerce_Internal_Api_QueryInfoExtractor{}
	mut iife_result_4 := iife_temp_4.extract_from_info(rt.new_object('Automattic_WooCommerce_Internal_Api_Schema_ResolveInfo',
		[]string{}, var_info), rt.new_object('Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLQueries_array',
		[]string{}, var_args))
	var_execute_args.array_set('_query_info', iife_result_4)
	mut iife_temp_5 := Class_Automattic_WooCommerce_Internal_Api_Utils{}
	mut iife_result_5 := iife_temp_5.authorize_command(var_command.clone(), rt.create_array([
		rt.ArrayItem{ key: 'id', val: var_execute_args.array_get(rt.new_string('id')) },
		rt.ArrayItem{ key: '_preauthorized', val: rt.call_function('current_user_can', [
			rt.new_string('read_product'),
		]) },
	]))
	if rt.is_true(rt.new_bool(!(rt.is_true(iife_result_5)))) {
		rt.throw_exception(rt.new_object('Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLQueries_Automattic_WooCommerce_Internal_Api_Schema_Error',
			[]string{}, create_automattic_woocommerce_internal_api_autogenerated_graphqlqueries_automattic_woocommerce_internal_api_schema_error(rt.new_string('You do not have permission to perform this action.'), rt.create_array([
			rt.ArrayItem{ key: 'code', val: 'UNAUTHORIZED' },
		]))))
	}
	mut iife_temp_6 := Class_Automattic_WooCommerce_Internal_Api_Utils{}
	mut iife_result_6 := iife_temp_6.execute_command(var_command.clone(), var_execute_args.clone())
	mut var_result := iife_result_6
	return var_result.clone()
}

struct Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Interfaces_Product {
	rt.PhpObjectBase
}

struct Class_Automattic_WooCommerce_Internal_Api_Schema_Type {
	rt.PhpObjectBase
}

struct Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLQueries_Automattic_WooCommerce_Api_Container {
	rt.PhpObjectBase
}

struct Class_Automattic_WooCommerce_Internal_Api_QueryInfoExtractor {
	rt.PhpObjectBase
}

struct Class_Automattic_WooCommerce_Internal_Api_Utils {
	rt.PhpObjectBase
}

struct Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLQueries_Automattic_WooCommerce_Internal_Api_Schema_Error {
	rt.PhpObjectBase
}

fn create_automattic_woocommerce_internal_api_autogenerated_graphqlqueries_getproduct(_args ...rt.PhpVal) &Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLQueries_GetProduct {
	mut obj := &Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLQueries_GetProduct{
		PhpObjectBase: rt.PhpObjectBase{}
	}
	return obj
}

fn create_automattic_woocommerce_internal_api_autogenerated_graphqltypes_interfaces_product(_args ...rt.PhpVal) &Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Interfaces_Product {
	mut obj := &Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Interfaces_Product{
		PhpObjectBase: rt.PhpObjectBase{}
	}
	return obj
}

fn create_automattic_woocommerce_internal_api_schema_type(_args ...rt.PhpVal) &Class_Automattic_WooCommerce_Internal_Api_Schema_Type {
	mut obj := &Class_Automattic_WooCommerce_Internal_Api_Schema_Type{
		PhpObjectBase: rt.PhpObjectBase{}
	}
	return obj
}

fn create_automattic_woocommerce_internal_api_autogenerated_graphqlqueries_automattic_woocommerce_api_container(_args ...rt.PhpVal) &Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLQueries_Automattic_WooCommerce_Api_Container {
	mut obj := &Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLQueries_Automattic_WooCommerce_Api_Container{
		PhpObjectBase: rt.PhpObjectBase{}
	}
	return obj
}

fn create_automattic_woocommerce_internal_api_queryinfoextractor(_args ...rt.PhpVal) &Class_Automattic_WooCommerce_Internal_Api_QueryInfoExtractor {
	mut obj := &Class_Automattic_WooCommerce_Internal_Api_QueryInfoExtractor{
		PhpObjectBase: rt.PhpObjectBase{}
	}
	return obj
}

fn create_automattic_woocommerce_internal_api_utils(_args ...rt.PhpVal) &Class_Automattic_WooCommerce_Internal_Api_Utils {
	mut obj := &Class_Automattic_WooCommerce_Internal_Api_Utils{
		PhpObjectBase: rt.PhpObjectBase{}
	}
	return obj
}

fn create_automattic_woocommerce_internal_api_autogenerated_graphqlqueries_automattic_woocommerce_internal_api_schema_error(_args ...rt.PhpVal) &Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLQueries_Automattic_WooCommerce_Internal_Api_Schema_Error {
	mut obj := &Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLQueries_Automattic_WooCommerce_Internal_Api_Schema_Error{
		PhpObjectBase: rt.PhpObjectBase{}
	}
	return obj
}

fn (mut this Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLQueries_GetProduct) dispatch_method(method_name string, args []rt.PhpVal) ?rt.PhpVal {
	match method_name {
		'get_field_definition' {
			return Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLQueries_GetProduct.get_field_definition()
		}
		'resolve' {
			mut dispatch_arg_0 := rt.cast_object_ptr[Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLQueries_mixed](if args.len > 0 {
				args[0]
			} else {
				rt.new_null()
			})
			mut dispatch_arg_1 := rt.cast_object_ptr[Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLQueries_array](if args.len > 1 {
				args[1]
			} else {
				rt.new_null()
			})
			mut dispatch_arg_2 := rt.cast_object_ptr[Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLQueries_mixed](if args.len > 2 {
				args[2]
			} else {
				rt.new_null()
			})
			mut dispatch_arg_3 := rt.cast_object_ptr[Class_Automattic_WooCommerce_Internal_Api_Schema_ResolveInfo](if args.len > 3 {
				args[3]
			} else {
				rt.new_null()
			})
			return Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLQueries_GetProduct.resolve(mut dispatch_arg_0, mut
				dispatch_arg_1, mut dispatch_arg_2, mut dispatch_arg_3)
		}
		else {
			return none
		}
	}
}

fn (this &Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLQueries_GetProduct) dispatch_get_prop(prop_name string) ?rt.PhpVal {
	return this.PhpObjectBase.dispatch_get_prop(prop_name)
}

fn (mut this Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLQueries_GetProduct) dispatch_set_prop(prop_name string, val rt.PhpVal) bool {
	return this.PhpObjectBase.dispatch_set_prop(prop_name, val)
}

fn (mut this Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Interfaces_Product) dispatch_method(method_name string, args []rt.PhpVal) ?rt.PhpVal {
	return none
}

fn (this &Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Interfaces_Product) dispatch_get_prop(prop_name string) ?rt.PhpVal {
	return this.PhpObjectBase.dispatch_get_prop(prop_name)
}

fn (mut this Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Interfaces_Product) dispatch_set_prop(prop_name string, val rt.PhpVal) bool {
	return this.PhpObjectBase.dispatch_set_prop(prop_name, val)
}

fn (mut this Class_Automattic_WooCommerce_Internal_Api_Schema_Type) dispatch_method(method_name string, args []rt.PhpVal) ?rt.PhpVal {
	return none
}

fn (this &Class_Automattic_WooCommerce_Internal_Api_Schema_Type) dispatch_get_prop(prop_name string) ?rt.PhpVal {
	return this.PhpObjectBase.dispatch_get_prop(prop_name)
}

fn (mut this Class_Automattic_WooCommerce_Internal_Api_Schema_Type) dispatch_set_prop(prop_name string, val rt.PhpVal) bool {
	return this.PhpObjectBase.dispatch_set_prop(prop_name, val)
}

fn (mut this Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLQueries_Automattic_WooCommerce_Api_Container) dispatch_method(method_name string, args []rt.PhpVal) ?rt.PhpVal {
	return none
}

fn (this &Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLQueries_Automattic_WooCommerce_Api_Container) dispatch_get_prop(prop_name string) ?rt.PhpVal {
	return this.PhpObjectBase.dispatch_get_prop(prop_name)
}

fn (mut this Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLQueries_Automattic_WooCommerce_Api_Container) dispatch_set_prop(prop_name string, val rt.PhpVal) bool {
	return this.PhpObjectBase.dispatch_set_prop(prop_name, val)
}

fn (mut this Class_Automattic_WooCommerce_Internal_Api_QueryInfoExtractor) dispatch_method(method_name string, args []rt.PhpVal) ?rt.PhpVal {
	return none
}

fn (this &Class_Automattic_WooCommerce_Internal_Api_QueryInfoExtractor) dispatch_get_prop(prop_name string) ?rt.PhpVal {
	return this.PhpObjectBase.dispatch_get_prop(prop_name)
}

fn (mut this Class_Automattic_WooCommerce_Internal_Api_QueryInfoExtractor) dispatch_set_prop(prop_name string, val rt.PhpVal) bool {
	return this.PhpObjectBase.dispatch_set_prop(prop_name, val)
}

fn (mut this Class_Automattic_WooCommerce_Internal_Api_Utils) dispatch_method(method_name string, args []rt.PhpVal) ?rt.PhpVal {
	return none
}

fn (this &Class_Automattic_WooCommerce_Internal_Api_Utils) dispatch_get_prop(prop_name string) ?rt.PhpVal {
	return this.PhpObjectBase.dispatch_get_prop(prop_name)
}

fn (mut this Class_Automattic_WooCommerce_Internal_Api_Utils) dispatch_set_prop(prop_name string, val rt.PhpVal) bool {
	return this.PhpObjectBase.dispatch_set_prop(prop_name, val)
}

fn (mut this Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLQueries_Automattic_WooCommerce_Internal_Api_Schema_Error) dispatch_method(method_name string, args []rt.PhpVal) ?rt.PhpVal {
	return none
}

fn (this &Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLQueries_Automattic_WooCommerce_Internal_Api_Schema_Error) dispatch_get_prop(prop_name string) ?rt.PhpVal {
	return this.PhpObjectBase.dispatch_get_prop(prop_name)
}

fn (mut this Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLQueries_Automattic_WooCommerce_Internal_Api_Schema_Error) dispatch_set_prop(prop_name string, val rt.PhpVal) bool {
	return this.PhpObjectBase.dispatch_set_prop(prop_name, val)
}

fn main() {
	defer {
		rt.shutdown()
	}
}
