import rt

struct Class_WP_Sitemaps_Stylesheet {
	rt.PhpObjectBase
}

fn (mut this Class_WP_Sitemaps_Stylesheet) render_stylesheet(var_type rt.PhpVal) {
	rt.call_function('header', [
		rt.new_string('Content-Type: application/xml; charset=UTF-8'),
	])
	if rt.is_true(rt.identical(rt.new_string('sitemap'), var_type)) {
		rt.echo_val(this.get_sitemap_stylesheet())
	}
	if rt.is_true(rt.identical(rt.new_string('index'), var_type)) {
		rt.echo_val(this.get_sitemap_index_stylesheet())
	}
	// unsupported expression: Expr_Exit
}

fn (mut this Class_WP_Sitemaps_Stylesheet) get_sitemap_stylesheet() rt.PhpVal {
	mut var_css := this.get_stylesheet_css()
	mut var_title := rt.call_function('esc_xml', [
		rt.call_function('__', [rt.new_string('XML Sitemap')]),
	])
	mut var_description := rt.call_function('esc_xml', [
		rt.call_function('__', [
			rt.new_string('This XML Sitemap is generated by WordPress to make your content more visible for search engines.'),
		]),
	])
	mut var_learn_more := rt.call_function('sprintf', [
		rt.new_string('<a href="%s">%s</a>'),
		rt.call_function('esc_url', [
			rt.call_function('__', [rt.new_string('https://www.sitemaps.org/')]),
		]),
		rt.call_function('esc_xml', [
			rt.call_function('__', [rt.new_string('Learn more about XML sitemaps.')]),
		]),
	])
	mut var_text := rt.call_function('sprintf', [
		rt.call_function('esc_xml', [
			rt.call_function('__', [
				rt.new_string('Number of URLs in this XML Sitemap: %s.'),
			]),
		]),
		rt.new_string('<xsl:value-of select="count( sitemap:urlset/sitemap:url )" />'),
	])
	mut var_lang := rt.call_function('get_language_attributes', [
		rt.new_string('html')])
	mut var_url := rt.call_function('esc_xml', [
		rt.call_function('__', [rt.new_string('URL')]),
	])
	mut var_lastmod := rt.call_function('esc_xml', [
		rt.call_function('__', [rt.new_string('Last Modified')]),
	])
	mut var_changefreq := rt.call_function('esc_xml', [
		rt.call_function('__', [rt.new_string('Change Frequency')]),
	])
	mut var_priority := rt.call_function('esc_xml', [
		rt.call_function('__', [rt.new_string('Priority')]),
	])
	mut var_xsl_content := rt.new_string(rt.concat(rt.concat(rt.concat(rt.concat(rt.concat(rt.concat(rt.concat(rt.concat(rt.concat(rt.concat(rt.concat(rt.concat(rt.concat(rt.concat(rt.concat(rt.concat(rt.concat(rt.concat(rt.concat(rt.concat(rt.concat(rt.concat(rt.new_string('<?xml version="1.0" encoding="UTF-8"?>\n<xsl:stylesheet\n\t\tversion="1.0"\n\t\txmlns:xsl="http://www.w3.org/1999/XSL/Transform"\n\t\txmlns:sitemap="http://www.sitemaps.org/schemas/sitemap/0.9"\n\t\texclude-result-prefixes="sitemap"\n\t\t>\n\n\t<xsl:output method="html" encoding="UTF-8" indent="yes" />\n\n\t<!--\n\t  Set variables for whether lastmod, changefreq or priority occur for any url in the sitemap.\n\t  We do this up front because it can be expensive in a large sitemap.\n\t  -->\n\t<xsl:variable name="has-lastmod"    select="count( /sitemap:urlset/sitemap:url/sitemap:lastmod )"    />\n\t<xsl:variable name="has-changefreq" select="count( /sitemap:urlset/sitemap:url/sitemap:changefreq )" />\n\t<xsl:variable name="has-priority"   select="count( /sitemap:urlset/sitemap:url/sitemap:priority )"   />\n\n\t<xsl:template match="/">\n\t\t<html '),
		var_lang), rt.new_string('>\n\t\t\t<head>\n\t\t\t\t<title>')), var_title),
		rt.new_string('</title>\n\t\t\t\t<style>\n\t\t\t\t\t')), var_css),
		rt.new_string('\n\t\t\t\t</style>\n\t\t\t</head>\n\t\t\t<body>\n\t\t\t\t<div id="sitemap">\n\t\t\t\t\t<div id="sitemap__header">\n\t\t\t\t\t\t<h1>')),
		var_title), rt.new_string('</h1>\n\t\t\t\t\t\t<p>')), var_description),
		rt.new_string('</p>\n\t\t\t\t\t\t<p>')), var_learn_more),
		rt.new_string('</p>\n\t\t\t\t\t</div>\n\t\t\t\t\t<div id="sitemap__content">\n\t\t\t\t\t\t<p class="text">')),
		var_text),
		rt.new_string('</p>\n\t\t\t\t\t\t<table id="sitemap__table">\n\t\t\t\t\t\t\t<thead>\n\t\t\t\t\t\t\t\t<tr>\n\t\t\t\t\t\t\t\t\t<th class="loc">')),
		var_url),
		rt.new_string('</th>\n\t\t\t\t\t\t\t\t\t<xsl:if test="$has-lastmod">\n\t\t\t\t\t\t\t\t\t\t<th class="lastmod">')),
		var_lastmod),
		rt.new_string('</th>\n\t\t\t\t\t\t\t\t\t</xsl:if>\n\t\t\t\t\t\t\t\t\t<xsl:if test="$has-changefreq">\n\t\t\t\t\t\t\t\t\t\t<th class="changefreq">')),
		var_changefreq),
		rt.new_string('</th>\n\t\t\t\t\t\t\t\t\t</xsl:if>\n\t\t\t\t\t\t\t\t\t<xsl:if test="$has-priority">\n\t\t\t\t\t\t\t\t\t\t<th class="priority">')),
		var_priority),
		rt.new_string('</th>\n\t\t\t\t\t\t\t\t\t</xsl:if>\n\t\t\t\t\t\t\t\t</tr>\n\t\t\t\t\t\t\t</thead>\n\t\t\t\t\t\t\t<tbody>\n\t\t\t\t\t\t\t\t<xsl:for-each select="sitemap:urlset/sitemap:url">\n\t\t\t\t\t\t\t\t\t<tr>\n\t\t\t\t\t\t\t\t\t\t<td class="loc"><a href="{sitemap:loc}"><xsl:value-of select="sitemap:loc" /></a></td>\n\t\t\t\t\t\t\t\t\t\t<xsl:if test="$has-lastmod">\n\t\t\t\t\t\t\t\t\t\t\t<td class="lastmod"><xsl:value-of select="sitemap:lastmod" /></td>\n\t\t\t\t\t\t\t\t\t\t</xsl:if>\n\t\t\t\t\t\t\t\t\t\t<xsl:if test="$has-changefreq">\n\t\t\t\t\t\t\t\t\t\t\t<td class="changefreq"><xsl:value-of select="sitemap:changefreq" /></td>\n\t\t\t\t\t\t\t\t\t\t</xsl:if>\n\t\t\t\t\t\t\t\t\t\t<xsl:if test="$has-priority">\n\t\t\t\t\t\t\t\t\t\t\t<td class="priority"><xsl:value-of select="sitemap:priority" /></td>\n\t\t\t\t\t\t\t\t\t\t</xsl:if>\n\t\t\t\t\t\t\t\t\t</tr>\n\t\t\t\t\t\t\t\t</xsl:for-each>\n\t\t\t\t\t\t\t</tbody>\n\t\t\t\t\t\t</table>\n\t\t\t\t\t</div>\n\t\t\t\t</div>\n\t\t\t</body>\n\t\t</html>\n\t</xsl:template>\n</xsl:stylesheet>\n')))
	return rt.call_function('apply_filters', [
		rt.new_string('wp_sitemaps_stylesheet_content'),
		var_xsl_content.dup(),
	])
}

fn (mut this Class_WP_Sitemaps_Stylesheet) get_sitemap_index_stylesheet() rt.PhpVal {
	mut var_css := this.get_stylesheet_css()
	mut var_title := rt.call_function('esc_xml', [
		rt.call_function('__', [rt.new_string('XML Sitemap')]),
	])
	mut var_description := rt.call_function('esc_xml', [
		rt.call_function('__', [
			rt.new_string('This XML Sitemap is generated by WordPress to make your content more visible for search engines.'),
		]),
	])
	mut var_learn_more := rt.call_function('sprintf', [
		rt.new_string('<a href="%s">%s</a>'),
		rt.call_function('esc_url', [
			rt.call_function('__', [rt.new_string('https://www.sitemaps.org/')]),
		]),
		rt.call_function('esc_xml', [
			rt.call_function('__', [rt.new_string('Learn more about XML sitemaps.')]),
		]),
	])
	mut var_text := rt.call_function('sprintf', [
		rt.call_function('esc_xml', [
			rt.call_function('__', [
				rt.new_string('Number of URLs in this XML Sitemap: %s.'),
			]),
		]),
		rt.new_string('<xsl:value-of select="count( sitemap:sitemapindex/sitemap:sitemap )" />'),
	])
	mut var_lang := rt.call_function('get_language_attributes', [
		rt.new_string('html')])
	mut var_url := rt.call_function('esc_xml', [
		rt.call_function('__', [rt.new_string('URL')]),
	])
	mut var_lastmod := rt.call_function('esc_xml', [
		rt.call_function('__', [rt.new_string('Last Modified')]),
	])
	mut var_xsl_content := rt.new_string(rt.concat(rt.concat(rt.concat(rt.concat(rt.concat(rt.concat(rt.concat(rt.concat(rt.concat(rt.concat(rt.concat(rt.concat(rt.concat(rt.concat(rt.concat(rt.concat(rt.concat(rt.concat(rt.new_string('<?xml version="1.0" encoding="UTF-8"?>\n<xsl:stylesheet\n\t\tversion="1.0"\n\t\txmlns:xsl="http://www.w3.org/1999/XSL/Transform"\n\t\txmlns:sitemap="http://www.sitemaps.org/schemas/sitemap/0.9"\n\t\texclude-result-prefixes="sitemap"\n\t\t>\n\n\t<xsl:output method="html" encoding="UTF-8" indent="yes" />\n\n\t<!--\n\t  Set variables for whether lastmod occurs for any sitemap in the index.\n\t  We do this up front because it can be expensive in a large sitemap.\n\t  -->\n\t<xsl:variable name="has-lastmod" select="count( /sitemap:sitemapindex/sitemap:sitemap/sitemap:lastmod )" />\n\n\t<xsl:template match="/">\n\t\t<html '),
		var_lang), rt.new_string('>\n\t\t\t<head>\n\t\t\t\t<title>')), var_title),
		rt.new_string('</title>\n\t\t\t\t<style>\n\t\t\t\t\t')), var_css),
		rt.new_string('\n\t\t\t\t</style>\n\t\t\t</head>\n\t\t\t<body>\n\t\t\t\t<div id="sitemap">\n\t\t\t\t\t<div id="sitemap__header">\n\t\t\t\t\t\t<h1>')),
		var_title), rt.new_string('</h1>\n\t\t\t\t\t\t<p>')), var_description),
		rt.new_string('</p>\n\t\t\t\t\t\t<p>')), var_learn_more),
		rt.new_string('</p>\n\t\t\t\t\t</div>\n\t\t\t\t\t<div id="sitemap__content">\n\t\t\t\t\t\t<p class="text">')),
		var_text),
		rt.new_string('</p>\n\t\t\t\t\t\t<table id="sitemap__table">\n\t\t\t\t\t\t\t<thead>\n\t\t\t\t\t\t\t\t<tr>\n\t\t\t\t\t\t\t\t\t<th class="loc">')),
		var_url),
		rt.new_string('</th>\n\t\t\t\t\t\t\t\t\t<xsl:if test="$has-lastmod">\n\t\t\t\t\t\t\t\t\t\t<th class="lastmod">')),
		var_lastmod),
		rt.new_string('</th>\n\t\t\t\t\t\t\t\t\t</xsl:if>\n\t\t\t\t\t\t\t\t</tr>\n\t\t\t\t\t\t\t</thead>\n\t\t\t\t\t\t\t<tbody>\n\t\t\t\t\t\t\t\t<xsl:for-each select="sitemap:sitemapindex/sitemap:sitemap">\n\t\t\t\t\t\t\t\t\t<tr>\n\t\t\t\t\t\t\t\t\t\t<td class="loc"><a href="{sitemap:loc}"><xsl:value-of select="sitemap:loc" /></a></td>\n\t\t\t\t\t\t\t\t\t\t<xsl:if test="$has-lastmod">\n\t\t\t\t\t\t\t\t\t\t\t<td class="lastmod"><xsl:value-of select="sitemap:lastmod" /></td>\n\t\t\t\t\t\t\t\t\t\t</xsl:if>\n\t\t\t\t\t\t\t\t\t</tr>\n\t\t\t\t\t\t\t\t</xsl:for-each>\n\t\t\t\t\t\t\t</tbody>\n\t\t\t\t\t\t</table>\n\t\t\t\t\t</div>\n\t\t\t\t</div>\n\t\t\t</body>\n\t\t</html>\n\t</xsl:template>\n</xsl:stylesheet>\n')))
	return rt.call_function('apply_filters', [
		rt.new_string('wp_sitemaps_stylesheet_index_content'),
		var_xsl_content.dup(),
	])
}

fn (mut this Class_WP_Sitemaps_Stylesheet) get_stylesheet_css() rt.PhpVal {
	mut var_text_align := rt.new_string(if rt.is_true(rt.call_function('is_rtl', []rt.PhpVal{})) {
		rt.new_string('right')
	} else {
		rt.new_string('left')
	})
	mut var_css :=
		rt.new_string(rt.new_string("\n\t\t\t\t\tbody {\n\t\t\t\t\t\tfont-family: -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, Oxygen-Sans, Ubuntu, Cantarell, \"Helvetica Neue\", sans-serif;\n\t\t\t\t\t\tcolor: #444;\n\t\t\t\t\t}\n\n\t\t\t\t\t#sitemap {\n\t\t\t\t\t\tmax-width: 980px;\n\t\t\t\t\t\tmargin: 0 auto;\n\t\t\t\t\t}\n\n\t\t\t\t\t#sitemap__table {\n\t\t\t\t\t\twidth: 100%;\n\t\t\t\t\t\tborder: solid 1px #ccc;\n\t\t\t\t\t\tborder-collapse: collapse;\n\t\t\t\t\t}\n\n\t\t\t \t\t#sitemap__table tr td.loc {\n\t\t\t\t\t\t/*\n\t\t\t\t\t\t * URLs should always be LTR.\n\t\t\t\t\t\t * See https://core.trac.wordpress.org/ticket/16834\n\t\t\t\t\t\t * and https://core.trac.wordpress.org/ticket/49949\n\t\t\t\t\t\t */\n\t\t\t\t\t\tdirection: ltr;\n\t\t\t\t\t}\n\n\t\t\t\t\t#sitemap__table tr th {\n\t\t\t\t\t\ttext-align: ${var_text_align.to_string()};\n\t\t\t\t\t}\n\n\t\t\t\t\t#sitemap__table tr td,\n\t\t\t\t\t#sitemap__table tr th {\n\t\t\t\t\t\tpadding: 10px;\n\t\t\t\t\t}\n\n\t\t\t\t\t#sitemap__table tr:nth-child(odd) td {\n\t\t\t\t\t\tbackground-color: #eee;\n\t\t\t\t\t}\n\n\t\t\t\t\ta:hover {\n\t\t\t\t\t\ttext-decoration: none;\n\t\t\t\t\t}\n"))
	return rt.call_function('apply_filters', [
		rt.new_string('wp_sitemaps_stylesheet_css'),
		var_css.dup(),
	])
}

fn create_wp_sitemaps_stylesheet() &Class_WP_Sitemaps_Stylesheet {
	mut obj := &Class_WP_Sitemaps_Stylesheet{
		PhpObjectBase: rt.PhpObjectBase{}
	}
	return obj
}

fn (mut this Class_WP_Sitemaps_Stylesheet) dispatch_method(method_name string, args []rt.PhpVal) ?rt.PhpVal {
	match method_name {
		'render_stylesheet' {
			dispatch_arg_0 := if args.len > 0 { args[0] } else { rt.new_null() }
			this.render_stylesheet(dispatch_arg_0)
			return rt.new_null()
		}
		'get_sitemap_stylesheet' {
			return this.get_sitemap_stylesheet()
		}
		'get_sitemap_index_stylesheet' {
			return this.get_sitemap_index_stylesheet()
		}
		'get_stylesheet_css' {
			return this.get_stylesheet_css()
		}
		else {
			return none
		}
	}
}

fn (this &Class_WP_Sitemaps_Stylesheet) dispatch_get_prop(prop_name string) ?rt.PhpVal {
	return this.PhpObjectBase.dispatch_get_prop(prop_name)
}

fn (mut this Class_WP_Sitemaps_Stylesheet) dispatch_set_prop(prop_name string, val rt.PhpVal) bool {
	return this.PhpObjectBase.dispatch_set_prop(prop_name, val)
}

pub fn init_wp_includes_sitemaps_class_wp_sitemaps_stylesheet_php() {
}
