import rt

struct Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLController {
	rt.PhpObjectBase
}

fn (mut this Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLController) build_schema() rt.PhpVal {
	mut iife_temp_0 := Class_Automattic_WooCommerce_Internal_Api_Autogenerated_RootQueryType{}
	mut iife_result_0 := iife_temp_0.get()
	mut iife_temp_1 := Class_Automattic_WooCommerce_Internal_Api_Autogenerated_RootMutationType{}
	mut iife_result_1 := iife_temp_1.get()
	mut iife_temp_2 := Class_Automattic_WooCommerce_Internal_Api_Autogenerated_TypeRegistry{}
	mut iife_result_2 := iife_temp_2.get_interface_implementors()
	return rt.new_object('Automattic_WooCommerce_Internal_Api_Schema_Schema', []string{}, create_automattic_woocommerce_internal_api_schema_schema(rt.create_array([
		rt.ArrayItem{ key: 'query', val: iife_result_0 },
		rt.ArrayItem{ key: 'mutation', val: iife_result_1 },
		rt.ArrayItem{ key: 'types', val: iife_result_2 },
	])))
}

struct Class_Automattic_WooCommerce_Internal_Api_Autogenerated_Automattic_WooCommerce_Internal_Api_GraphQLController {
	rt.PhpObjectBase
}

struct Class_Automattic_WooCommerce_Internal_Api_Schema_Schema {
	rt.PhpObjectBase
}

struct Class_Automattic_WooCommerce_Internal_Api_Autogenerated_RootQueryType {
	rt.PhpObjectBase
}

struct Class_Automattic_WooCommerce_Internal_Api_Autogenerated_RootMutationType {
	rt.PhpObjectBase
}

struct Class_Automattic_WooCommerce_Internal_Api_Autogenerated_TypeRegistry {
	rt.PhpObjectBase
}

fn create_automattic_woocommerce_internal_api_autogenerated_graphqlcontroller(_args ...rt.PhpVal) &Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLController {
	mut obj := &Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLController{
		PhpObjectBase: rt.PhpObjectBase{}
	}
	return obj
}

fn create_automattic_woocommerce_internal_api_autogenerated_automattic_woocommerce_internal_api_graphqlcontroller(_args ...rt.PhpVal) &Class_Automattic_WooCommerce_Internal_Api_Autogenerated_Automattic_WooCommerce_Internal_Api_GraphQLController {
	mut obj := &Class_Automattic_WooCommerce_Internal_Api_Autogenerated_Automattic_WooCommerce_Internal_Api_GraphQLController{
		PhpObjectBase: rt.PhpObjectBase{}
	}
	return obj
}

fn create_automattic_woocommerce_internal_api_schema_schema(_args ...rt.PhpVal) &Class_Automattic_WooCommerce_Internal_Api_Schema_Schema {
	mut obj := &Class_Automattic_WooCommerce_Internal_Api_Schema_Schema{
		PhpObjectBase: rt.PhpObjectBase{}
	}
	return obj
}

fn create_automattic_woocommerce_internal_api_autogenerated_rootquerytype(_args ...rt.PhpVal) &Class_Automattic_WooCommerce_Internal_Api_Autogenerated_RootQueryType {
	mut obj := &Class_Automattic_WooCommerce_Internal_Api_Autogenerated_RootQueryType{
		PhpObjectBase: rt.PhpObjectBase{}
	}
	return obj
}

fn create_automattic_woocommerce_internal_api_autogenerated_rootmutationtype(_args ...rt.PhpVal) &Class_Automattic_WooCommerce_Internal_Api_Autogenerated_RootMutationType {
	mut obj := &Class_Automattic_WooCommerce_Internal_Api_Autogenerated_RootMutationType{
		PhpObjectBase: rt.PhpObjectBase{}
	}
	return obj
}

fn create_automattic_woocommerce_internal_api_autogenerated_typeregistry(_args ...rt.PhpVal) &Class_Automattic_WooCommerce_Internal_Api_Autogenerated_TypeRegistry {
	mut obj := &Class_Automattic_WooCommerce_Internal_Api_Autogenerated_TypeRegistry{
		PhpObjectBase: rt.PhpObjectBase{}
	}
	return obj
}

fn (mut this Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLController) dispatch_method(method_name string, args []rt.PhpVal) ?rt.PhpVal {
	match method_name {
		'build_schema' {
			return this.build_schema()
		}
		else {
			return none
		}
	}
}

fn (this &Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLController) dispatch_get_prop(prop_name string) ?rt.PhpVal {
	return this.PhpObjectBase.dispatch_get_prop(prop_name)
}

fn (mut this Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLController) dispatch_set_prop(prop_name string, val rt.PhpVal) bool {
	return this.PhpObjectBase.dispatch_set_prop(prop_name, val)
}

fn (mut this Class_Automattic_WooCommerce_Internal_Api_Autogenerated_Automattic_WooCommerce_Internal_Api_GraphQLController) dispatch_method(method_name string, args []rt.PhpVal) ?rt.PhpVal {
	return none
}

fn (this &Class_Automattic_WooCommerce_Internal_Api_Autogenerated_Automattic_WooCommerce_Internal_Api_GraphQLController) dispatch_get_prop(prop_name string) ?rt.PhpVal {
	return this.PhpObjectBase.dispatch_get_prop(prop_name)
}

fn (mut this Class_Automattic_WooCommerce_Internal_Api_Autogenerated_Automattic_WooCommerce_Internal_Api_GraphQLController) dispatch_set_prop(prop_name string, val rt.PhpVal) bool {
	return this.PhpObjectBase.dispatch_set_prop(prop_name, val)
}

fn (mut this Class_Automattic_WooCommerce_Internal_Api_Schema_Schema) dispatch_method(method_name string, args []rt.PhpVal) ?rt.PhpVal {
	return none
}

fn (this &Class_Automattic_WooCommerce_Internal_Api_Schema_Schema) dispatch_get_prop(prop_name string) ?rt.PhpVal {
	return this.PhpObjectBase.dispatch_get_prop(prop_name)
}

fn (mut this Class_Automattic_WooCommerce_Internal_Api_Schema_Schema) dispatch_set_prop(prop_name string, val rt.PhpVal) bool {
	return this.PhpObjectBase.dispatch_set_prop(prop_name, val)
}

fn (mut this Class_Automattic_WooCommerce_Internal_Api_Autogenerated_RootQueryType) dispatch_method(method_name string, args []rt.PhpVal) ?rt.PhpVal {
	return none
}

fn (this &Class_Automattic_WooCommerce_Internal_Api_Autogenerated_RootQueryType) dispatch_get_prop(prop_name string) ?rt.PhpVal {
	return this.PhpObjectBase.dispatch_get_prop(prop_name)
}

fn (mut this Class_Automattic_WooCommerce_Internal_Api_Autogenerated_RootQueryType) dispatch_set_prop(prop_name string, val rt.PhpVal) bool {
	return this.PhpObjectBase.dispatch_set_prop(prop_name, val)
}

fn (mut this Class_Automattic_WooCommerce_Internal_Api_Autogenerated_RootMutationType) dispatch_method(method_name string, args []rt.PhpVal) ?rt.PhpVal {
	return none
}

fn (this &Class_Automattic_WooCommerce_Internal_Api_Autogenerated_RootMutationType) dispatch_get_prop(prop_name string) ?rt.PhpVal {
	return this.PhpObjectBase.dispatch_get_prop(prop_name)
}

fn (mut this Class_Automattic_WooCommerce_Internal_Api_Autogenerated_RootMutationType) dispatch_set_prop(prop_name string, val rt.PhpVal) bool {
	return this.PhpObjectBase.dispatch_set_prop(prop_name, val)
}

fn (mut this Class_Automattic_WooCommerce_Internal_Api_Autogenerated_TypeRegistry) dispatch_method(method_name string, args []rt.PhpVal) ?rt.PhpVal {
	return none
}

fn (this &Class_Automattic_WooCommerce_Internal_Api_Autogenerated_TypeRegistry) dispatch_get_prop(prop_name string) ?rt.PhpVal {
	return this.PhpObjectBase.dispatch_get_prop(prop_name)
}

fn (mut this Class_Automattic_WooCommerce_Internal_Api_Autogenerated_TypeRegistry) dispatch_set_prop(prop_name string, val rt.PhpVal) bool {
	return this.PhpObjectBase.dispatch_set_prop(prop_name, val)
}

fn main() {
	defer {
		rt.shutdown()
	}
}
