import rt

struct Class_Automattic_WooCommerce_Internal_Api_Autogenerated_RootQueryType {
	rt.PhpObjectBase
}

fn init_static_automattic_woocommerce_internal_api_autogenerated_rootquerytype() {
	rt.init_static_prop('Automattic_WooCommerce_Internal_Api_Autogenerated_RootQueryType',
		'instance', rt.new_null())
}

fn Class_Automattic_WooCommerce_Internal_Api_Autogenerated_RootQueryType.get() rt.PhpVal {
	if rt.is_true(rt.identical(rt.new_null(), rt.get_static_prop('Automattic_WooCommerce_Internal_Api_Autogenerated_RootQueryType',
		'instance')))
	{
		closure_5_fn := fn (this_ptr rt.PhpVal, args []rt.PhpVal) rt.PhpVal {
			mut iife_temp_1 :=
				Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLQueries_ListProducts{}
			mut iife_result_1 := iife_temp_1.get_field_definition()
			mut iife_temp_2 :=
				Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLQueries_GetProduct{}
			mut iife_result_2 := iife_temp_2.get_field_definition()
			mut iife_temp_3 :=
				Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLQueries_GetCoupon{}
			mut iife_result_3 := iife_temp_3.get_field_definition()
			mut iife_temp_4 :=
				Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLQueries_ListCoupons{}
			mut iife_result_4 := iife_temp_4.get_field_definition()
			return rt.create_array([rt.ArrayItem{ key: 'products', val: iife_result_1 },
				rt.ArrayItem{ key: 'product', val: iife_result_2 },
				rt.ArrayItem{ key: 'coupon', val: iife_result_3 },
				rt.ArrayItem{ key: 'coupons', val: iife_result_4 }])
		}
		rt.set_static_prop('Automattic_WooCommerce_Internal_Api_Autogenerated_RootQueryType',
			'instance', rt.new_object('Automattic_WooCommerce_Internal_Api_Schema_ObjectType',
			[]string{}, create_automattic_woocommerce_internal_api_schema_objecttype(rt.create_array([
			rt.ArrayItem{ key: 'name', val: 'Query' },
			rt.ArrayItem{ key: 'fields', val: rt.new_closure(closure_5_fn) },
		]))))
	}
	return rt.get_static_prop('Automattic_WooCommerce_Internal_Api_Autogenerated_RootQueryType',
		'instance')
}

struct Class_Automattic_WooCommerce_Internal_Api_Schema_ObjectType {
	rt.PhpObjectBase
}

struct Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLQueries_ListProducts {
	rt.PhpObjectBase
}

struct Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLQueries_GetProduct {
	rt.PhpObjectBase
}

struct Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLQueries_GetCoupon {
	rt.PhpObjectBase
}

struct Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLQueries_ListCoupons {
	rt.PhpObjectBase
}

fn create_automattic_woocommerce_internal_api_autogenerated_rootquerytype(_args ...rt.PhpVal) &Class_Automattic_WooCommerce_Internal_Api_Autogenerated_RootQueryType {
	mut obj := &Class_Automattic_WooCommerce_Internal_Api_Autogenerated_RootQueryType{
		PhpObjectBase: rt.PhpObjectBase{}
	}
	return obj
}

fn create_automattic_woocommerce_internal_api_schema_objecttype(_args ...rt.PhpVal) &Class_Automattic_WooCommerce_Internal_Api_Schema_ObjectType {
	mut obj := &Class_Automattic_WooCommerce_Internal_Api_Schema_ObjectType{
		PhpObjectBase: rt.PhpObjectBase{}
	}
	return obj
}

fn create_automattic_woocommerce_internal_api_autogenerated_graphqlqueries_listproducts(_args ...rt.PhpVal) &Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLQueries_ListProducts {
	mut obj := &Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLQueries_ListProducts{
		PhpObjectBase: rt.PhpObjectBase{}
	}
	return obj
}

fn create_automattic_woocommerce_internal_api_autogenerated_graphqlqueries_getproduct(_args ...rt.PhpVal) &Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLQueries_GetProduct {
	mut obj := &Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLQueries_GetProduct{
		PhpObjectBase: rt.PhpObjectBase{}
	}
	return obj
}

fn create_automattic_woocommerce_internal_api_autogenerated_graphqlqueries_getcoupon(_args ...rt.PhpVal) &Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLQueries_GetCoupon {
	mut obj := &Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLQueries_GetCoupon{
		PhpObjectBase: rt.PhpObjectBase{}
	}
	return obj
}

fn create_automattic_woocommerce_internal_api_autogenerated_graphqlqueries_listcoupons(_args ...rt.PhpVal) &Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLQueries_ListCoupons {
	mut obj := &Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLQueries_ListCoupons{
		PhpObjectBase: rt.PhpObjectBase{}
	}
	return obj
}

fn (mut this Class_Automattic_WooCommerce_Internal_Api_Autogenerated_RootQueryType) dispatch_method(method_name string, args []rt.PhpVal) ?rt.PhpVal {
	match method_name {
		'get' {
			return Class_Automattic_WooCommerce_Internal_Api_Autogenerated_RootQueryType.get()
		}
		else {
			return none
		}
	}
}

fn (this &Class_Automattic_WooCommerce_Internal_Api_Autogenerated_RootQueryType) dispatch_get_prop(prop_name string) ?rt.PhpVal {
	return this.PhpObjectBase.dispatch_get_prop(prop_name)
}

fn (mut this Class_Automattic_WooCommerce_Internal_Api_Autogenerated_RootQueryType) dispatch_set_prop(prop_name string, val rt.PhpVal) bool {
	return this.PhpObjectBase.dispatch_set_prop(prop_name, val)
}

fn (mut this Class_Automattic_WooCommerce_Internal_Api_Schema_ObjectType) dispatch_method(method_name string, args []rt.PhpVal) ?rt.PhpVal {
	return none
}

fn (this &Class_Automattic_WooCommerce_Internal_Api_Schema_ObjectType) dispatch_get_prop(prop_name string) ?rt.PhpVal {
	return this.PhpObjectBase.dispatch_get_prop(prop_name)
}

fn (mut this Class_Automattic_WooCommerce_Internal_Api_Schema_ObjectType) dispatch_set_prop(prop_name string, val rt.PhpVal) bool {
	return this.PhpObjectBase.dispatch_set_prop(prop_name, val)
}

fn (mut this Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLQueries_ListProducts) dispatch_method(method_name string, args []rt.PhpVal) ?rt.PhpVal {
	return none
}

fn (this &Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLQueries_ListProducts) dispatch_get_prop(prop_name string) ?rt.PhpVal {
	return this.PhpObjectBase.dispatch_get_prop(prop_name)
}

fn (mut this Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLQueries_ListProducts) dispatch_set_prop(prop_name string, val rt.PhpVal) bool {
	return this.PhpObjectBase.dispatch_set_prop(prop_name, val)
}

fn (mut this Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLQueries_GetProduct) dispatch_method(method_name string, args []rt.PhpVal) ?rt.PhpVal {
	return none
}

fn (this &Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLQueries_GetProduct) dispatch_get_prop(prop_name string) ?rt.PhpVal {
	return this.PhpObjectBase.dispatch_get_prop(prop_name)
}

fn (mut this Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLQueries_GetProduct) dispatch_set_prop(prop_name string, val rt.PhpVal) bool {
	return this.PhpObjectBase.dispatch_set_prop(prop_name, val)
}

fn (mut this Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLQueries_GetCoupon) dispatch_method(method_name string, args []rt.PhpVal) ?rt.PhpVal {
	return none
}

fn (this &Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLQueries_GetCoupon) dispatch_get_prop(prop_name string) ?rt.PhpVal {
	return this.PhpObjectBase.dispatch_get_prop(prop_name)
}

fn (mut this Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLQueries_GetCoupon) dispatch_set_prop(prop_name string, val rt.PhpVal) bool {
	return this.PhpObjectBase.dispatch_set_prop(prop_name, val)
}

fn (mut this Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLQueries_ListCoupons) dispatch_method(method_name string, args []rt.PhpVal) ?rt.PhpVal {
	return none
}

fn (this &Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLQueries_ListCoupons) dispatch_get_prop(prop_name string) ?rt.PhpVal {
	return this.PhpObjectBase.dispatch_get_prop(prop_name)
}

fn (mut this Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLQueries_ListCoupons) dispatch_set_prop(prop_name string, val rt.PhpVal) bool {
	return this.PhpObjectBase.dispatch_set_prop(prop_name, val)
}

fn main() {
	defer {
		rt.shutdown()
	}
}
