import rt

struct Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Input_CreateProduct {
	rt.PhpObjectBase
}

fn init_static_automattic_woocommerce_internal_api_autogenerated_graphqltypes_input_createproduct() {
	rt.init_static_prop('Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Input_CreateProduct',
		'instance', rt.new_null())
}

fn Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Input_CreateProduct.get() rt.PhpVal {
	if rt.is_true(rt.identical(rt.new_null(), rt.get_static_prop('Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Input_CreateProduct',
		'instance')))
	{
		closure_14_fn := fn (this_ptr rt.PhpVal, args []rt.PhpVal) rt.PhpVal {
			mut iife_temp_1 := Class_Automattic_WooCommerce_Internal_Api_Schema_Type{}
			mut iife_result_1 := iife_temp_1.string()
			mut iife_temp_2 := Class_Automattic_WooCommerce_Internal_Api_Schema_Type{}
			mut iife_result_2 := iife_temp_2.nonnull(iife_result_1)
			mut iife_temp_3 := Class_Automattic_WooCommerce_Internal_Api_Schema_Type{}
			mut iife_result_3 := iife_temp_3.string()
			mut iife_temp_4 := Class_Automattic_WooCommerce_Internal_Api_Schema_Type{}
			mut iife_result_4 := iife_temp_4.string()
			mut iife_temp_5 := Class_Automattic_WooCommerce_Internal_Api_Schema_Type{}
			mut iife_result_5 := iife_temp_5.string()
			mut iife_temp_6 := Class_Automattic_WooCommerce_Internal_Api_Schema_Type{}
			mut iife_result_6 := iife_temp_6.string()
			mut iife_temp_7 :=
				Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Enums_ProductStatus{}
			mut iife_result_7 := iife_temp_7.get()
			mut iife_temp_8 :=
				Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Enums_ProductType{}
			mut iife_result_8 := iife_temp_8.get()
			mut iife_temp_9 := Class_Automattic_WooCommerce_Internal_Api_Schema_Type{}
			mut iife_result_9 := iife_temp_9.float()
			mut iife_temp_10 := Class_Automattic_WooCommerce_Internal_Api_Schema_Type{}
			mut iife_result_10 := iife_temp_10.float()
			mut iife_temp_11 := Class_Automattic_WooCommerce_Internal_Api_Schema_Type{}
			mut iife_result_11 := iife_temp_11.boolean()
			mut iife_temp_12 := Class_Automattic_WooCommerce_Internal_Api_Schema_Type{}
			mut iife_result_12 := iife_temp_12.int()
			mut iife_temp_13 :=
				Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Input_Dimensions{}
			mut iife_result_13 := iife_temp_13.get()
			return rt.create_array([
				rt.ArrayItem{ key: 'name', val: rt.create_array([
					rt.ArrayItem{ key: 'type', val: iife_result_2 },
					rt.ArrayItem{ key: 'description', val: rt.call_function('__', [
						rt.new_string('The product name.'),
						rt.new_string('woocommerce'),
					]) },
				]) },
				rt.ArrayItem{ key: 'slug', val: rt.create_array([
					rt.ArrayItem{ key: 'type', val: iife_result_3 },
					rt.ArrayItem{ key: 'description', val: rt.call_function('__', [
						rt.new_string('The product slug.'),
						rt.new_string('woocommerce'),
					]) },
				]) },
				rt.ArrayItem{ key: 'sku', val: rt.create_array([
					rt.ArrayItem{ key: 'type', val: iife_result_4 },
					rt.ArrayItem{ key: 'description', val: rt.call_function('__', [
						rt.new_string('The product SKU.'),
						rt.new_string('woocommerce'),
					]) },
				]) },
				rt.ArrayItem{ key: 'description', val: rt.create_array([
					rt.ArrayItem{ key: 'type', val: iife_result_5 },
					rt.ArrayItem{ key: 'description', val: rt.call_function('__', [
						rt.new_string('The full product description.'),
						rt.new_string('woocommerce'),
					]) },
				]) },
				rt.ArrayItem{ key: 'short_description', val: rt.create_array([
					rt.ArrayItem{ key: 'type', val: iife_result_6 },
					rt.ArrayItem{ key: 'description', val: rt.call_function('__', [
						rt.new_string('The short product description.'),
						rt.new_string('woocommerce'),
					]) },
				]) },
				rt.ArrayItem{ key: 'status', val: rt.create_array([
					rt.ArrayItem{ key: 'type', val: iife_result_7 },
					rt.ArrayItem{ key: 'description', val: rt.call_function('__', [
						rt.new_string('The product status.'),
						rt.new_string('woocommerce'),
					]) },
				]) },
				rt.ArrayItem{ key: 'product_type', val: rt.create_array([
					rt.ArrayItem{ key: 'type', val: iife_result_8 },
					rt.ArrayItem{ key: 'description', val: rt.call_function('__', [
						rt.new_string('The product type.'),
						rt.new_string('woocommerce'),
					]) },
				]) },
				rt.ArrayItem{ key: 'regular_price', val: rt.create_array([
					rt.ArrayItem{ key: 'type', val: iife_result_9 },
					rt.ArrayItem{ key: 'description', val: rt.call_function('__', [
						rt.new_string('The regular price.'),
						rt.new_string('woocommerce'),
					]) },
				]) },
				rt.ArrayItem{ key: 'sale_price', val: rt.create_array([
					rt.ArrayItem{ key: 'type', val: iife_result_10 },
					rt.ArrayItem{ key: 'description', val: rt.call_function('__', [
						rt.new_string('The sale price.'),
						rt.new_string('woocommerce'),
					]) },
				]) },
				rt.ArrayItem{ key: 'manage_stock', val: rt.create_array([
					rt.ArrayItem{ key: 'type', val: iife_result_11 },
					rt.ArrayItem{ key: 'description', val: rt.call_function('__', [
						rt.new_string('Whether to manage stock.'),
						rt.new_string('woocommerce'),
					]) },
				]) },
				rt.ArrayItem{ key: 'stock_quantity', val: rt.create_array([
					rt.ArrayItem{ key: 'type', val: iife_result_12 },
					rt.ArrayItem{ key: 'description', val: rt.call_function('__', [
						rt.new_string('The number of items in stock.'),
						rt.new_string('woocommerce'),
					]) },
				]) },
				rt.ArrayItem{ key: 'dimensions', val: rt.create_array([
					rt.ArrayItem{ key: 'type', val: iife_result_13 },
					rt.ArrayItem{ key: 'description', val: rt.call_function('__', [
						rt.new_string('The product dimensions.'),
						rt.new_string('woocommerce'),
					]) },
				]) },
			])
		}
		rt.set_static_prop('Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Input_CreateProduct',
			'instance', rt.new_object('Automattic_WooCommerce_Internal_Api_Schema_InputObjectType',
			[]string{}, create_automattic_woocommerce_internal_api_schema_inputobjecttype(rt.create_array([
			rt.ArrayItem{ key: 'name', val: 'CreateProductInput' },
			rt.ArrayItem{ key: 'description', val: rt.call_function('__', [
				rt.new_string('Data required to create a new product.'),
				rt.new_string('woocommerce'),
			]) },
			rt.ArrayItem{ key: 'fields', val: rt.new_closure(closure_14_fn) },
		]))))
	}
	return rt.get_static_prop('Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Input_CreateProduct',
		'instance')
}

struct Class_Automattic_WooCommerce_Internal_Api_Schema_InputObjectType {
	rt.PhpObjectBase
}

struct Class_Automattic_WooCommerce_Internal_Api_Schema_Type {
	rt.PhpObjectBase
}

struct Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Enums_ProductStatus {
	rt.PhpObjectBase
}

struct Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Enums_ProductType {
	rt.PhpObjectBase
}

struct Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Input_Dimensions {
	rt.PhpObjectBase
}

fn create_automattic_woocommerce_internal_api_autogenerated_graphqltypes_input_createproduct(_args ...rt.PhpVal) &Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Input_CreateProduct {
	mut obj := &Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Input_CreateProduct{
		PhpObjectBase: rt.PhpObjectBase{}
	}
	return obj
}

fn create_automattic_woocommerce_internal_api_schema_inputobjecttype(_args ...rt.PhpVal) &Class_Automattic_WooCommerce_Internal_Api_Schema_InputObjectType {
	mut obj := &Class_Automattic_WooCommerce_Internal_Api_Schema_InputObjectType{
		PhpObjectBase: rt.PhpObjectBase{}
	}
	return obj
}

fn create_automattic_woocommerce_internal_api_schema_type(_args ...rt.PhpVal) &Class_Automattic_WooCommerce_Internal_Api_Schema_Type {
	mut obj := &Class_Automattic_WooCommerce_Internal_Api_Schema_Type{
		PhpObjectBase: rt.PhpObjectBase{}
	}
	return obj
}

fn create_automattic_woocommerce_internal_api_autogenerated_graphqltypes_enums_productstatus(_args ...rt.PhpVal) &Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Enums_ProductStatus {
	mut obj := &Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Enums_ProductStatus{
		PhpObjectBase: rt.PhpObjectBase{}
	}
	return obj
}

fn create_automattic_woocommerce_internal_api_autogenerated_graphqltypes_enums_producttype(_args ...rt.PhpVal) &Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Enums_ProductType {
	mut obj := &Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Enums_ProductType{
		PhpObjectBase: rt.PhpObjectBase{}
	}
	return obj
}

fn create_automattic_woocommerce_internal_api_autogenerated_graphqltypes_input_dimensions(_args ...rt.PhpVal) &Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Input_Dimensions {
	mut obj := &Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Input_Dimensions{
		PhpObjectBase: rt.PhpObjectBase{}
	}
	return obj
}

fn (mut this Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Input_CreateProduct) dispatch_method(method_name string, args []rt.PhpVal) ?rt.PhpVal {
	match method_name {
		'get' {
			return Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Input_CreateProduct.get()
		}
		else {
			return none
		}
	}
}

fn (this &Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Input_CreateProduct) dispatch_get_prop(prop_name string) ?rt.PhpVal {
	return this.PhpObjectBase.dispatch_get_prop(prop_name)
}

fn (mut this Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Input_CreateProduct) dispatch_set_prop(prop_name string, val rt.PhpVal) bool {
	return this.PhpObjectBase.dispatch_set_prop(prop_name, val)
}

fn (mut this Class_Automattic_WooCommerce_Internal_Api_Schema_InputObjectType) dispatch_method(method_name string, args []rt.PhpVal) ?rt.PhpVal {
	return none
}

fn (this &Class_Automattic_WooCommerce_Internal_Api_Schema_InputObjectType) dispatch_get_prop(prop_name string) ?rt.PhpVal {
	return this.PhpObjectBase.dispatch_get_prop(prop_name)
}

fn (mut this Class_Automattic_WooCommerce_Internal_Api_Schema_InputObjectType) dispatch_set_prop(prop_name string, val rt.PhpVal) bool {
	return this.PhpObjectBase.dispatch_set_prop(prop_name, val)
}

fn (mut this Class_Automattic_WooCommerce_Internal_Api_Schema_Type) dispatch_method(method_name string, args []rt.PhpVal) ?rt.PhpVal {
	return none
}

fn (this &Class_Automattic_WooCommerce_Internal_Api_Schema_Type) dispatch_get_prop(prop_name string) ?rt.PhpVal {
	return this.PhpObjectBase.dispatch_get_prop(prop_name)
}

fn (mut this Class_Automattic_WooCommerce_Internal_Api_Schema_Type) dispatch_set_prop(prop_name string, val rt.PhpVal) bool {
	return this.PhpObjectBase.dispatch_set_prop(prop_name, val)
}

fn (mut this Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Enums_ProductStatus) dispatch_method(method_name string, args []rt.PhpVal) ?rt.PhpVal {
	return none
}

fn (this &Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Enums_ProductStatus) dispatch_get_prop(prop_name string) ?rt.PhpVal {
	return this.PhpObjectBase.dispatch_get_prop(prop_name)
}

fn (mut this Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Enums_ProductStatus) dispatch_set_prop(prop_name string, val rt.PhpVal) bool {
	return this.PhpObjectBase.dispatch_set_prop(prop_name, val)
}

fn (mut this Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Enums_ProductType) dispatch_method(method_name string, args []rt.PhpVal) ?rt.PhpVal {
	return none
}

fn (this &Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Enums_ProductType) dispatch_get_prop(prop_name string) ?rt.PhpVal {
	return this.PhpObjectBase.dispatch_get_prop(prop_name)
}

fn (mut this Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Enums_ProductType) dispatch_set_prop(prop_name string, val rt.PhpVal) bool {
	return this.PhpObjectBase.dispatch_set_prop(prop_name, val)
}

fn (mut this Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Input_Dimensions) dispatch_method(method_name string, args []rt.PhpVal) ?rt.PhpVal {
	return none
}

fn (this &Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Input_Dimensions) dispatch_get_prop(prop_name string) ?rt.PhpVal {
	return this.PhpObjectBase.dispatch_get_prop(prop_name)
}

fn (mut this Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Input_Dimensions) dispatch_set_prop(prop_name string, val rt.PhpVal) bool {
	return this.PhpObjectBase.dispatch_set_prop(prop_name, val)
}

fn main() {
	defer {
		rt.shutdown()
	}
}
