import rt

struct Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Input_ProductFilter {
	rt.PhpObjectBase
}

fn init_static_automattic_woocommerce_internal_api_autogenerated_graphqltypes_input_productfilter() {
	rt.init_static_prop('Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Input_ProductFilter',
		'instance', rt.new_null())
}

fn Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Input_ProductFilter.get() rt.PhpVal {
	if rt.is_true(rt.identical(rt.new_null(), rt.get_static_prop('Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Input_ProductFilter',
		'instance')))
	{
		closure_4_fn := fn (this_ptr rt.PhpVal, args []rt.PhpVal) rt.PhpVal {
			mut iife_temp_1 :=
				Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Enums_ProductStatus{}
			mut iife_result_1 := iife_temp_1.get()
			mut iife_temp_2 :=
				Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Enums_StockStatus{}
			mut iife_result_2 := iife_temp_2.get()
			mut iife_temp_3 := Class_Automattic_WooCommerce_Internal_Api_Schema_Type{}
			mut iife_result_3 := iife_temp_3.string()
			return rt.create_array([
				rt.ArrayItem{ key: 'status', val: rt.create_array([
					rt.ArrayItem{ key: 'type', val: iife_result_1 },
					rt.ArrayItem{ key: 'description', val: rt.call_function('__', [
						rt.new_string('Filter by product status.'),
						rt.new_string('woocommerce'),
					]) },
				]) },
				rt.ArrayItem{ key: 'stock_status', val: rt.create_array([
					rt.ArrayItem{ key: 'type', val: iife_result_2 },
					rt.ArrayItem{ key: 'description', val: rt.call_function('__', [
						rt.new_string('Filter by stock status.'),
						rt.new_string('woocommerce'),
					]) },
				]) },
				rt.ArrayItem{ key: 'search', val: rt.create_array([
					rt.ArrayItem{ key: 'type', val: iife_result_3 },
					rt.ArrayItem{ key: 'description', val: rt.call_function('__', [
						rt.new_string('Search products by keyword.'),
						rt.new_string('woocommerce'),
					]) },
				]) },
			])
		}
		rt.set_static_prop('Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Input_ProductFilter',
			'instance', rt.new_object('Automattic_WooCommerce_Internal_Api_Schema_InputObjectType',
			[]string{}, create_automattic_woocommerce_internal_api_schema_inputobjecttype(rt.create_array([
			rt.ArrayItem{ key: 'name', val: 'ProductFilterInput' },
			rt.ArrayItem{ key: 'description', val: rt.call_function('__', [
				rt.new_string('Filter criteria for listing products.'),
				rt.new_string('woocommerce'),
			]) },
			rt.ArrayItem{ key: 'fields', val: rt.new_closure(closure_4_fn) },
		]))))
	}
	return rt.get_static_prop('Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Input_ProductFilter',
		'instance')
}

struct Class_Automattic_WooCommerce_Internal_Api_Schema_InputObjectType {
	rt.PhpObjectBase
}

struct Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Enums_ProductStatus {
	rt.PhpObjectBase
}

struct Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Enums_StockStatus {
	rt.PhpObjectBase
}

struct Class_Automattic_WooCommerce_Internal_Api_Schema_Type {
	rt.PhpObjectBase
}

fn create_automattic_woocommerce_internal_api_autogenerated_graphqltypes_input_productfilter(_args ...rt.PhpVal) &Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Input_ProductFilter {
	mut obj := &Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Input_ProductFilter{
		PhpObjectBase: rt.PhpObjectBase{}
	}
	return obj
}

fn create_automattic_woocommerce_internal_api_schema_inputobjecttype(_args ...rt.PhpVal) &Class_Automattic_WooCommerce_Internal_Api_Schema_InputObjectType {
	mut obj := &Class_Automattic_WooCommerce_Internal_Api_Schema_InputObjectType{
		PhpObjectBase: rt.PhpObjectBase{}
	}
	return obj
}

fn create_automattic_woocommerce_internal_api_autogenerated_graphqltypes_enums_productstatus(_args ...rt.PhpVal) &Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Enums_ProductStatus {
	mut obj := &Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Enums_ProductStatus{
		PhpObjectBase: rt.PhpObjectBase{}
	}
	return obj
}

fn create_automattic_woocommerce_internal_api_autogenerated_graphqltypes_enums_stockstatus(_args ...rt.PhpVal) &Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Enums_StockStatus {
	mut obj := &Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Enums_StockStatus{
		PhpObjectBase: rt.PhpObjectBase{}
	}
	return obj
}

fn create_automattic_woocommerce_internal_api_schema_type(_args ...rt.PhpVal) &Class_Automattic_WooCommerce_Internal_Api_Schema_Type {
	mut obj := &Class_Automattic_WooCommerce_Internal_Api_Schema_Type{
		PhpObjectBase: rt.PhpObjectBase{}
	}
	return obj
}

fn (mut this Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Input_ProductFilter) dispatch_method(method_name string, args []rt.PhpVal) ?rt.PhpVal {
	match method_name {
		'get' {
			return Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Input_ProductFilter.get()
		}
		else {
			return none
		}
	}
}

fn (this &Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Input_ProductFilter) dispatch_get_prop(prop_name string) ?rt.PhpVal {
	return this.PhpObjectBase.dispatch_get_prop(prop_name)
}

fn (mut this Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Input_ProductFilter) dispatch_set_prop(prop_name string, val rt.PhpVal) bool {
	return this.PhpObjectBase.dispatch_set_prop(prop_name, val)
}

fn (mut this Class_Automattic_WooCommerce_Internal_Api_Schema_InputObjectType) dispatch_method(method_name string, args []rt.PhpVal) ?rt.PhpVal {
	return none
}

fn (this &Class_Automattic_WooCommerce_Internal_Api_Schema_InputObjectType) dispatch_get_prop(prop_name string) ?rt.PhpVal {
	return this.PhpObjectBase.dispatch_get_prop(prop_name)
}

fn (mut this Class_Automattic_WooCommerce_Internal_Api_Schema_InputObjectType) dispatch_set_prop(prop_name string, val rt.PhpVal) bool {
	return this.PhpObjectBase.dispatch_set_prop(prop_name, val)
}

fn (mut this Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Enums_ProductStatus) dispatch_method(method_name string, args []rt.PhpVal) ?rt.PhpVal {
	return none
}

fn (this &Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Enums_ProductStatus) dispatch_get_prop(prop_name string) ?rt.PhpVal {
	return this.PhpObjectBase.dispatch_get_prop(prop_name)
}

fn (mut this Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Enums_ProductStatus) dispatch_set_prop(prop_name string, val rt.PhpVal) bool {
	return this.PhpObjectBase.dispatch_set_prop(prop_name, val)
}

fn (mut this Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Enums_StockStatus) dispatch_method(method_name string, args []rt.PhpVal) ?rt.PhpVal {
	return none
}

fn (this &Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Enums_StockStatus) dispatch_get_prop(prop_name string) ?rt.PhpVal {
	return this.PhpObjectBase.dispatch_get_prop(prop_name)
}

fn (mut this Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Enums_StockStatus) dispatch_set_prop(prop_name string, val rt.PhpVal) bool {
	return this.PhpObjectBase.dispatch_set_prop(prop_name, val)
}

fn (mut this Class_Automattic_WooCommerce_Internal_Api_Schema_Type) dispatch_method(method_name string, args []rt.PhpVal) ?rt.PhpVal {
	return none
}

fn (this &Class_Automattic_WooCommerce_Internal_Api_Schema_Type) dispatch_get_prop(prop_name string) ?rt.PhpVal {
	return this.PhpObjectBase.dispatch_get_prop(prop_name)
}

fn (mut this Class_Automattic_WooCommerce_Internal_Api_Schema_Type) dispatch_set_prop(prop_name string, val rt.PhpVal) bool {
	return this.PhpObjectBase.dispatch_set_prop(prop_name, val)
}

fn main() {
	defer {
		rt.shutdown()
	}
}
