import rt

struct Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Input_UpdateCoupon {
	rt.PhpObjectBase
}

fn init_static_automattic_woocommerce_internal_api_autogenerated_graphqltypes_input_updatecoupon() {
	rt.init_static_prop('Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Input_UpdateCoupon',
		'instance', rt.new_null())
}

fn Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Input_UpdateCoupon.get() rt.PhpVal {
	if rt.is_true(rt.identical(rt.new_null(), rt.get_static_prop('Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Input_UpdateCoupon',
		'instance')))
	{
		closure_32_fn := fn (this_ptr rt.PhpVal, args []rt.PhpVal) rt.PhpVal {
			mut iife_temp_1 := Class_Automattic_WooCommerce_Internal_Api_Schema_Type{}
			mut iife_result_1 := iife_temp_1.int()
			mut iife_temp_2 := Class_Automattic_WooCommerce_Internal_Api_Schema_Type{}
			mut iife_result_2 := iife_temp_2.nonnull(iife_result_1)
			mut iife_temp_3 := Class_Automattic_WooCommerce_Internal_Api_Schema_Type{}
			mut iife_result_3 := iife_temp_3.string()
			mut iife_temp_4 := Class_Automattic_WooCommerce_Internal_Api_Schema_Type{}
			mut iife_result_4 := iife_temp_4.string()
			mut iife_temp_5 :=
				Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Enums_DiscountType{}
			mut iife_result_5 := iife_temp_5.get()
			mut iife_temp_6 := Class_Automattic_WooCommerce_Internal_Api_Schema_Type{}
			mut iife_result_6 := iife_temp_6.float()
			mut iife_temp_7 :=
				Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Enums_CouponStatus{}
			mut iife_result_7 := iife_temp_7.get()
			mut iife_temp_8 := Class_Automattic_WooCommerce_Internal_Api_Schema_Type{}
			mut iife_result_8 := iife_temp_8.string()
			mut iife_temp_9 := Class_Automattic_WooCommerce_Internal_Api_Schema_Type{}
			mut iife_result_9 := iife_temp_9.boolean()
			mut iife_temp_10 := Class_Automattic_WooCommerce_Internal_Api_Schema_Type{}
			mut iife_result_10 := iife_temp_10.int()
			mut iife_temp_11 := Class_Automattic_WooCommerce_Internal_Api_Schema_Type{}
			mut iife_result_11 := iife_temp_11.nonnull(iife_result_10)
			mut iife_temp_12 := Class_Automattic_WooCommerce_Internal_Api_Schema_Type{}
			mut iife_result_12 := iife_temp_12.listof(iife_result_11)
			mut iife_temp_13 := Class_Automattic_WooCommerce_Internal_Api_Schema_Type{}
			mut iife_result_13 := iife_temp_13.int()
			mut iife_temp_14 := Class_Automattic_WooCommerce_Internal_Api_Schema_Type{}
			mut iife_result_14 := iife_temp_14.nonnull(iife_result_13)
			mut iife_temp_15 := Class_Automattic_WooCommerce_Internal_Api_Schema_Type{}
			mut iife_result_15 := iife_temp_15.listof(iife_result_14)
			mut iife_temp_16 := Class_Automattic_WooCommerce_Internal_Api_Schema_Type{}
			mut iife_result_16 := iife_temp_16.int()
			mut iife_temp_17 := Class_Automattic_WooCommerce_Internal_Api_Schema_Type{}
			mut iife_result_17 := iife_temp_17.int()
			mut iife_temp_18 := Class_Automattic_WooCommerce_Internal_Api_Schema_Type{}
			mut iife_result_18 := iife_temp_18.int()
			mut iife_temp_19 := Class_Automattic_WooCommerce_Internal_Api_Schema_Type{}
			mut iife_result_19 := iife_temp_19.boolean()
			mut iife_temp_20 := Class_Automattic_WooCommerce_Internal_Api_Schema_Type{}
			mut iife_result_20 := iife_temp_20.int()
			mut iife_temp_21 := Class_Automattic_WooCommerce_Internal_Api_Schema_Type{}
			mut iife_result_21 := iife_temp_21.nonnull(iife_result_20)
			mut iife_temp_22 := Class_Automattic_WooCommerce_Internal_Api_Schema_Type{}
			mut iife_result_22 := iife_temp_22.listof(iife_result_21)
			mut iife_temp_23 := Class_Automattic_WooCommerce_Internal_Api_Schema_Type{}
			mut iife_result_23 := iife_temp_23.int()
			mut iife_temp_24 := Class_Automattic_WooCommerce_Internal_Api_Schema_Type{}
			mut iife_result_24 := iife_temp_24.nonnull(iife_result_23)
			mut iife_temp_25 := Class_Automattic_WooCommerce_Internal_Api_Schema_Type{}
			mut iife_result_25 := iife_temp_25.listof(iife_result_24)
			mut iife_temp_26 := Class_Automattic_WooCommerce_Internal_Api_Schema_Type{}
			mut iife_result_26 := iife_temp_26.boolean()
			mut iife_temp_27 := Class_Automattic_WooCommerce_Internal_Api_Schema_Type{}
			mut iife_result_27 := iife_temp_27.float()
			mut iife_temp_28 := Class_Automattic_WooCommerce_Internal_Api_Schema_Type{}
			mut iife_result_28 := iife_temp_28.float()
			mut iife_temp_29 := Class_Automattic_WooCommerce_Internal_Api_Schema_Type{}
			mut iife_result_29 := iife_temp_29.string()
			mut iife_temp_30 := Class_Automattic_WooCommerce_Internal_Api_Schema_Type{}
			mut iife_result_30 := iife_temp_30.nonnull(iife_result_29)
			mut iife_temp_31 := Class_Automattic_WooCommerce_Internal_Api_Schema_Type{}
			mut iife_result_31 := iife_temp_31.listof(iife_result_30)
			return rt.create_array([
				rt.ArrayItem{ key: 'id', val: rt.create_array([
					rt.ArrayItem{ key: 'type', val: iife_result_2 },
					rt.ArrayItem{ key: 'description', val: rt.call_function('__', [
						rt.new_string('The ID of the coupon to update.'),
						rt.new_string('woocommerce'),
					]) },
				]) },
				rt.ArrayItem{ key: 'code', val: rt.create_array([
					rt.ArrayItem{ key: 'type', val: iife_result_3 },
					rt.ArrayItem{ key: 'description', val: rt.call_function('__', [
						rt.new_string('The coupon code.'),
						rt.new_string('woocommerce'),
					]) },
				]) },
				rt.ArrayItem{ key: 'description', val: rt.create_array([
					rt.ArrayItem{ key: 'type', val: iife_result_4 },
					rt.ArrayItem{ key: 'description', val: rt.call_function('__', [
						rt.new_string('The coupon description.'),
						rt.new_string('woocommerce'),
					]) },
				]) },
				rt.ArrayItem{ key: 'discount_type', val: rt.create_array([
					rt.ArrayItem{ key: 'type', val: iife_result_5 },
					rt.ArrayItem{ key: 'description', val: rt.call_function('__', [
						rt.new_string('The type of discount.'),
						rt.new_string('woocommerce'),
					]) },
				]) },
				rt.ArrayItem{ key: 'amount', val: rt.create_array([
					rt.ArrayItem{ key: 'type', val: iife_result_6 },
					rt.ArrayItem{ key: 'description', val: rt.call_function('__', [
						rt.new_string('The discount amount.'),
						rt.new_string('woocommerce'),
					]) },
				]) },
				rt.ArrayItem{ key: 'status', val: rt.create_array([
					rt.ArrayItem{ key: 'type', val: iife_result_7 },
					rt.ArrayItem{ key: 'description', val: rt.call_function('__', [
						rt.new_string('The coupon status.'),
						rt.new_string('woocommerce'),
					]) },
				]) },
				rt.ArrayItem{ key: 'date_expires', val: rt.create_array([
					rt.ArrayItem{ key: 'type', val: iife_result_8 },
					rt.ArrayItem{ key: 'description', val: rt.call_function('__', [
						rt.new_string('The date the coupon expires (ISO 8601).'),
						rt.new_string('woocommerce'),
					]) },
				]) },
				rt.ArrayItem{ key: 'individual_use', val: rt.create_array([
					rt.ArrayItem{ key: 'type', val: iife_result_9 },
					rt.ArrayItem{ key: 'description', val: rt.call_function('__', [
						rt.new_string('Whether the coupon can only be used alone.'),
						rt.new_string('woocommerce'),
					]) },
				]) },
				rt.ArrayItem{ key: 'product_ids', val: rt.create_array([
					rt.ArrayItem{ key: 'type', val: iife_result_12 },
					rt.ArrayItem{ key: 'description', val: rt.call_function('__', [
						rt.new_string('Product IDs the coupon can be applied to.'),
						rt.new_string('woocommerce'),
					]) },
				]) },
				rt.ArrayItem{ key: 'excluded_product_ids', val: rt.create_array([
					rt.ArrayItem{ key: 'type', val: iife_result_15 },
					rt.ArrayItem{ key: 'description', val: rt.call_function('__', [
						rt.new_string('Product IDs excluded from the coupon.'),
						rt.new_string('woocommerce'),
					]) },
				]) },
				rt.ArrayItem{ key: 'usage_limit', val: rt.create_array([
					rt.ArrayItem{ key: 'type', val: iife_result_16 },
					rt.ArrayItem{ key: 'description', val: rt.call_function('__', [
						rt.new_string('Maximum number of times the coupon can be used in total.'),
						rt.new_string('woocommerce'),
					]) },
				]) },
				rt.ArrayItem{ key: 'usage_limit_per_user', val: rt.create_array([
					rt.ArrayItem{ key: 'type', val: iife_result_17 },
					rt.ArrayItem{ key: 'description', val: rt.call_function('__', [
						rt.new_string('Maximum number of times the coupon can be used per customer.'),
						rt.new_string('woocommerce'),
					]) },
				]) },
				rt.ArrayItem{ key: 'limit_usage_to_x_items', val: rt.create_array([
					rt.ArrayItem{ key: 'type', val: iife_result_18 },
					rt.ArrayItem{ key: 'description', val: rt.call_function('__', [
						rt.new_string('Maximum number of items the coupon can be applied to.'),
						rt.new_string('woocommerce'),
					]) },
				]) },
				rt.ArrayItem{ key: 'free_shipping', val: rt.create_array([
					rt.ArrayItem{ key: 'type', val: iife_result_19 },
					rt.ArrayItem{ key: 'description', val: rt.call_function('__', [
						rt.new_string('Whether the coupon grants free shipping.'),
						rt.new_string('woocommerce'),
					]) },
				]) },
				rt.ArrayItem{ key: 'product_categories', val: rt.create_array([
					rt.ArrayItem{ key: 'type', val: iife_result_22 },
					rt.ArrayItem{ key: 'description', val: rt.call_function('__', [
						rt.new_string('Product category IDs the coupon applies to.'),
						rt.new_string('woocommerce'),
					]) },
				]) },
				rt.ArrayItem{ key: 'excluded_product_categories', val: rt.create_array([
					rt.ArrayItem{ key: 'type', val: iife_result_25 },
					rt.ArrayItem{ key: 'description', val: rt.call_function('__', [
						rt.new_string('Product category IDs excluded from the coupon.'),
						rt.new_string('woocommerce'),
					]) },
				]) },
				rt.ArrayItem{ key: 'exclude_sale_items', val: rt.create_array([
					rt.ArrayItem{ key: 'type', val: iife_result_26 },
					rt.ArrayItem{ key: 'description', val: rt.call_function('__', [
						rt.new_string('Whether the coupon excludes items on sale.'),
						rt.new_string('woocommerce'),
					]) },
				]) },
				rt.ArrayItem{ key: 'minimum_amount', val: rt.create_array([
					rt.ArrayItem{ key: 'type', val: iife_result_27 },
					rt.ArrayItem{ key: 'description', val: rt.call_function('__', [
						rt.new_string('Minimum order amount required to use the coupon.'),
						rt.new_string('woocommerce'),
					]) },
				]) },
				rt.ArrayItem{ key: 'maximum_amount', val: rt.create_array([
					rt.ArrayItem{ key: 'type', val: iife_result_28 },
					rt.ArrayItem{ key: 'description', val: rt.call_function('__', [
						rt.new_string('Maximum order amount allowed to use the coupon.'),
						rt.new_string('woocommerce'),
					]) },
				]) },
				rt.ArrayItem{ key: 'email_restrictions', val: rt.create_array([
					rt.ArrayItem{ key: 'type', val: iife_result_31 },
					rt.ArrayItem{ key: 'description', val: rt.call_function('__', [
						rt.new_string('Email addresses that can use this coupon.'),
						rt.new_string('woocommerce'),
					]) },
				]) },
			])
		}
		rt.set_static_prop('Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Input_UpdateCoupon',
			'instance', rt.new_object('Automattic_WooCommerce_Internal_Api_Schema_InputObjectType',
			[]string{}, create_automattic_woocommerce_internal_api_schema_inputobjecttype(rt.create_array([
			rt.ArrayItem{ key: 'name', val: 'UpdateCouponInput' },
			rt.ArrayItem{ key: 'description', val: rt.call_function('__', [
				rt.new_string('Data for updating an existing coupon. All fields are optional.'),
				rt.new_string('woocommerce'),
			]) },
			rt.ArrayItem{ key: 'fields', val: rt.new_closure(closure_32_fn) },
		]))))
	}
	return rt.get_static_prop('Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Input_UpdateCoupon',
		'instance')
}

struct Class_Automattic_WooCommerce_Internal_Api_Schema_InputObjectType {
	rt.PhpObjectBase
}

struct Class_Automattic_WooCommerce_Internal_Api_Schema_Type {
	rt.PhpObjectBase
}

struct Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Enums_DiscountType {
	rt.PhpObjectBase
}

struct Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Enums_CouponStatus {
	rt.PhpObjectBase
}

fn create_automattic_woocommerce_internal_api_autogenerated_graphqltypes_input_updatecoupon(_args ...rt.PhpVal) &Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Input_UpdateCoupon {
	mut obj := &Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Input_UpdateCoupon{
		PhpObjectBase: rt.PhpObjectBase{}
	}
	return obj
}

fn create_automattic_woocommerce_internal_api_schema_inputobjecttype(_args ...rt.PhpVal) &Class_Automattic_WooCommerce_Internal_Api_Schema_InputObjectType {
	mut obj := &Class_Automattic_WooCommerce_Internal_Api_Schema_InputObjectType{
		PhpObjectBase: rt.PhpObjectBase{}
	}
	return obj
}

fn create_automattic_woocommerce_internal_api_schema_type(_args ...rt.PhpVal) &Class_Automattic_WooCommerce_Internal_Api_Schema_Type {
	mut obj := &Class_Automattic_WooCommerce_Internal_Api_Schema_Type{
		PhpObjectBase: rt.PhpObjectBase{}
	}
	return obj
}

fn create_automattic_woocommerce_internal_api_autogenerated_graphqltypes_enums_discounttype(_args ...rt.PhpVal) &Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Enums_DiscountType {
	mut obj := &Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Enums_DiscountType{
		PhpObjectBase: rt.PhpObjectBase{}
	}
	return obj
}

fn create_automattic_woocommerce_internal_api_autogenerated_graphqltypes_enums_couponstatus(_args ...rt.PhpVal) &Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Enums_CouponStatus {
	mut obj := &Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Enums_CouponStatus{
		PhpObjectBase: rt.PhpObjectBase{}
	}
	return obj
}

fn (mut this Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Input_UpdateCoupon) dispatch_method(method_name string, args []rt.PhpVal) ?rt.PhpVal {
	match method_name {
		'get' {
			return Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Input_UpdateCoupon.get()
		}
		else {
			return none
		}
	}
}

fn (this &Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Input_UpdateCoupon) dispatch_get_prop(prop_name string) ?rt.PhpVal {
	return this.PhpObjectBase.dispatch_get_prop(prop_name)
}

fn (mut this Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Input_UpdateCoupon) dispatch_set_prop(prop_name string, val rt.PhpVal) bool {
	return this.PhpObjectBase.dispatch_set_prop(prop_name, val)
}

fn (mut this Class_Automattic_WooCommerce_Internal_Api_Schema_InputObjectType) dispatch_method(method_name string, args []rt.PhpVal) ?rt.PhpVal {
	return none
}

fn (this &Class_Automattic_WooCommerce_Internal_Api_Schema_InputObjectType) dispatch_get_prop(prop_name string) ?rt.PhpVal {
	return this.PhpObjectBase.dispatch_get_prop(prop_name)
}

fn (mut this Class_Automattic_WooCommerce_Internal_Api_Schema_InputObjectType) dispatch_set_prop(prop_name string, val rt.PhpVal) bool {
	return this.PhpObjectBase.dispatch_set_prop(prop_name, val)
}

fn (mut this Class_Automattic_WooCommerce_Internal_Api_Schema_Type) dispatch_method(method_name string, args []rt.PhpVal) ?rt.PhpVal {
	return none
}

fn (this &Class_Automattic_WooCommerce_Internal_Api_Schema_Type) dispatch_get_prop(prop_name string) ?rt.PhpVal {
	return this.PhpObjectBase.dispatch_get_prop(prop_name)
}

fn (mut this Class_Automattic_WooCommerce_Internal_Api_Schema_Type) dispatch_set_prop(prop_name string, val rt.PhpVal) bool {
	return this.PhpObjectBase.dispatch_set_prop(prop_name, val)
}

fn (mut this Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Enums_DiscountType) dispatch_method(method_name string, args []rt.PhpVal) ?rt.PhpVal {
	return none
}

fn (this &Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Enums_DiscountType) dispatch_get_prop(prop_name string) ?rt.PhpVal {
	return this.PhpObjectBase.dispatch_get_prop(prop_name)
}

fn (mut this Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Enums_DiscountType) dispatch_set_prop(prop_name string, val rt.PhpVal) bool {
	return this.PhpObjectBase.dispatch_set_prop(prop_name, val)
}

fn (mut this Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Enums_CouponStatus) dispatch_method(method_name string, args []rt.PhpVal) ?rt.PhpVal {
	return none
}

fn (this &Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Enums_CouponStatus) dispatch_get_prop(prop_name string) ?rt.PhpVal {
	return this.PhpObjectBase.dispatch_get_prop(prop_name)
}

fn (mut this Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Enums_CouponStatus) dispatch_set_prop(prop_name string, val rt.PhpVal) bool {
	return this.PhpObjectBase.dispatch_set_prop(prop_name, val)
}

fn main() {
	defer {
		rt.shutdown()
	}
}
