import rt

struct Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Pagination_ProductConnection {
	rt.PhpObjectBase
}

fn init_static_automattic_woocommerce_internal_api_autogenerated_graphqltypes_pagination_productconnection() {
	rt.init_static_prop('Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Pagination_ProductConnection',
		'instance', rt.new_null())
}

fn Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Pagination_ProductConnection.get() rt.PhpVal {
	if rt.is_true(rt.identical(rt.new_null(), rt.get_static_prop('Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Pagination_ProductConnection',
		'instance')))
	{
		closure_13_fn := fn (this_ptr rt.PhpVal, args []rt.PhpVal) rt.PhpVal {
			mut iife_temp_1 :=
				Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Pagination_ProductEdge{}
			mut iife_result_1 := iife_temp_1.get()
			mut iife_temp_2 := Class_Automattic_WooCommerce_Internal_Api_Schema_Type{}
			mut iife_result_2 := iife_temp_2.nonnull(iife_result_1)
			mut iife_temp_3 := Class_Automattic_WooCommerce_Internal_Api_Schema_Type{}
			mut iife_result_3 := iife_temp_3.listof(iife_result_2)
			mut iife_temp_4 := Class_Automattic_WooCommerce_Internal_Api_Schema_Type{}
			mut iife_result_4 := iife_temp_4.nonnull(iife_result_3)
			mut iife_temp_5 :=
				Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Interfaces_Product{}
			mut iife_result_5 := iife_temp_5.get()
			mut iife_temp_6 := Class_Automattic_WooCommerce_Internal_Api_Schema_Type{}
			mut iife_result_6 := iife_temp_6.nonnull(iife_result_5)
			mut iife_temp_7 := Class_Automattic_WooCommerce_Internal_Api_Schema_Type{}
			mut iife_result_7 := iife_temp_7.listof(iife_result_6)
			mut iife_temp_8 := Class_Automattic_WooCommerce_Internal_Api_Schema_Type{}
			mut iife_result_8 := iife_temp_8.nonnull(iife_result_7)
			mut iife_temp_9 :=
				Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Pagination_PageInfo{}
			mut iife_result_9 := iife_temp_9.get()
			mut iife_temp_10 := Class_Automattic_WooCommerce_Internal_Api_Schema_Type{}
			mut iife_result_10 := iife_temp_10.nonnull(iife_result_9)
			mut iife_temp_11 := Class_Automattic_WooCommerce_Internal_Api_Schema_Type{}
			mut iife_result_11 := iife_temp_11.int()
			mut iife_temp_12 := Class_Automattic_WooCommerce_Internal_Api_Schema_Type{}
			mut iife_result_12 := iife_temp_12.nonnull(iife_result_11)
			return rt.create_array([
				rt.ArrayItem{ key: 'edges', val: rt.create_array([
					rt.ArrayItem{ key: 'type', val: iife_result_4 },
				]) },
				rt.ArrayItem{ key: 'nodes', val: rt.create_array([
					rt.ArrayItem{ key: 'type', val: iife_result_8 },
				]) },
				rt.ArrayItem{ key: 'page_info', val: rt.create_array([
					rt.ArrayItem{ key: 'type', val: iife_result_10 },
				]) },
				rt.ArrayItem{ key: 'total_count', val: rt.create_array([
					rt.ArrayItem{ key: 'type', val: iife_result_12 },
				]) },
			])
		}
		rt.set_static_prop('Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Pagination_ProductConnection',
			'instance', rt.new_object('Automattic_WooCommerce_Internal_Api_Schema_ObjectType',
			[]string{}, create_automattic_woocommerce_internal_api_schema_objecttype(rt.create_array([
			rt.ArrayItem{ key: 'name', val: 'ProductConnection' },
			rt.ArrayItem{ key: 'description', val: rt.call_function('__', [
				rt.new_string('A connection to a list of Product items.'),
				rt.new_string('woocommerce'),
			]) },
			rt.ArrayItem{ key: 'fields', val: rt.new_closure(closure_13_fn) },
		]))))
	}
	return rt.get_static_prop('Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Pagination_ProductConnection',
		'instance')
}

struct Class_Automattic_WooCommerce_Internal_Api_Schema_ObjectType {
	rt.PhpObjectBase
}

struct Class_Automattic_WooCommerce_Internal_Api_Schema_Type {
	rt.PhpObjectBase
}

struct Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Pagination_ProductEdge {
	rt.PhpObjectBase
}

struct Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Interfaces_Product {
	rt.PhpObjectBase
}

struct Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Pagination_PageInfo {
	rt.PhpObjectBase
}

fn create_automattic_woocommerce_internal_api_autogenerated_graphqltypes_pagination_productconnection(_args ...rt.PhpVal) &Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Pagination_ProductConnection {
	mut obj := &Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Pagination_ProductConnection{
		PhpObjectBase: rt.PhpObjectBase{}
	}
	return obj
}

fn create_automattic_woocommerce_internal_api_schema_objecttype(_args ...rt.PhpVal) &Class_Automattic_WooCommerce_Internal_Api_Schema_ObjectType {
	mut obj := &Class_Automattic_WooCommerce_Internal_Api_Schema_ObjectType{
		PhpObjectBase: rt.PhpObjectBase{}
	}
	return obj
}

fn create_automattic_woocommerce_internal_api_schema_type(_args ...rt.PhpVal) &Class_Automattic_WooCommerce_Internal_Api_Schema_Type {
	mut obj := &Class_Automattic_WooCommerce_Internal_Api_Schema_Type{
		PhpObjectBase: rt.PhpObjectBase{}
	}
	return obj
}

fn create_automattic_woocommerce_internal_api_autogenerated_graphqltypes_pagination_productedge(_args ...rt.PhpVal) &Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Pagination_ProductEdge {
	mut obj := &Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Pagination_ProductEdge{
		PhpObjectBase: rt.PhpObjectBase{}
	}
	return obj
}

fn create_automattic_woocommerce_internal_api_autogenerated_graphqltypes_interfaces_product(_args ...rt.PhpVal) &Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Interfaces_Product {
	mut obj := &Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Interfaces_Product{
		PhpObjectBase: rt.PhpObjectBase{}
	}
	return obj
}

fn create_automattic_woocommerce_internal_api_autogenerated_graphqltypes_pagination_pageinfo(_args ...rt.PhpVal) &Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Pagination_PageInfo {
	mut obj := &Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Pagination_PageInfo{
		PhpObjectBase: rt.PhpObjectBase{}
	}
	return obj
}

fn (mut this Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Pagination_ProductConnection) dispatch_method(method_name string, args []rt.PhpVal) ?rt.PhpVal {
	match method_name {
		'get' {
			return Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Pagination_ProductConnection.get()
		}
		else {
			return none
		}
	}
}

fn (this &Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Pagination_ProductConnection) dispatch_get_prop(prop_name string) ?rt.PhpVal {
	return this.PhpObjectBase.dispatch_get_prop(prop_name)
}

fn (mut this Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Pagination_ProductConnection) dispatch_set_prop(prop_name string, val rt.PhpVal) bool {
	return this.PhpObjectBase.dispatch_set_prop(prop_name, val)
}

fn (mut this Class_Automattic_WooCommerce_Internal_Api_Schema_ObjectType) dispatch_method(method_name string, args []rt.PhpVal) ?rt.PhpVal {
	return none
}

fn (this &Class_Automattic_WooCommerce_Internal_Api_Schema_ObjectType) dispatch_get_prop(prop_name string) ?rt.PhpVal {
	return this.PhpObjectBase.dispatch_get_prop(prop_name)
}

fn (mut this Class_Automattic_WooCommerce_Internal_Api_Schema_ObjectType) dispatch_set_prop(prop_name string, val rt.PhpVal) bool {
	return this.PhpObjectBase.dispatch_set_prop(prop_name, val)
}

fn (mut this Class_Automattic_WooCommerce_Internal_Api_Schema_Type) dispatch_method(method_name string, args []rt.PhpVal) ?rt.PhpVal {
	return none
}

fn (this &Class_Automattic_WooCommerce_Internal_Api_Schema_Type) dispatch_get_prop(prop_name string) ?rt.PhpVal {
	return this.PhpObjectBase.dispatch_get_prop(prop_name)
}

fn (mut this Class_Automattic_WooCommerce_Internal_Api_Schema_Type) dispatch_set_prop(prop_name string, val rt.PhpVal) bool {
	return this.PhpObjectBase.dispatch_set_prop(prop_name, val)
}

fn (mut this Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Pagination_ProductEdge) dispatch_method(method_name string, args []rt.PhpVal) ?rt.PhpVal {
	return none
}

fn (this &Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Pagination_ProductEdge) dispatch_get_prop(prop_name string) ?rt.PhpVal {
	return this.PhpObjectBase.dispatch_get_prop(prop_name)
}

fn (mut this Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Pagination_ProductEdge) dispatch_set_prop(prop_name string, val rt.PhpVal) bool {
	return this.PhpObjectBase.dispatch_set_prop(prop_name, val)
}

fn (mut this Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Interfaces_Product) dispatch_method(method_name string, args []rt.PhpVal) ?rt.PhpVal {
	return none
}

fn (this &Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Interfaces_Product) dispatch_get_prop(prop_name string) ?rt.PhpVal {
	return this.PhpObjectBase.dispatch_get_prop(prop_name)
}

fn (mut this Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Interfaces_Product) dispatch_set_prop(prop_name string, val rt.PhpVal) bool {
	return this.PhpObjectBase.dispatch_set_prop(prop_name, val)
}

fn (mut this Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Pagination_PageInfo) dispatch_method(method_name string, args []rt.PhpVal) ?rt.PhpVal {
	return none
}

fn (this &Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Pagination_PageInfo) dispatch_get_prop(prop_name string) ?rt.PhpVal {
	return this.PhpObjectBase.dispatch_get_prop(prop_name)
}

fn (mut this Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Pagination_PageInfo) dispatch_set_prop(prop_name string, val rt.PhpVal) bool {
	return this.PhpObjectBase.dispatch_set_prop(prop_name, val)
}

fn main() {
	defer {
		rt.shutdown()
	}
}
