import rt

struct Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Pagination_ProductReviewEdge {
	rt.PhpObjectBase
}

fn init_static_automattic_woocommerce_internal_api_autogenerated_graphqltypes_pagination_productreviewedge() {
	rt.init_static_prop('Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Pagination_ProductReviewEdge',
		'instance', rt.new_null())
}

fn Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Pagination_ProductReviewEdge.get() rt.PhpVal {
	if rt.is_true(rt.identical(rt.new_null(), rt.get_static_prop('Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Pagination_ProductReviewEdge',
		'instance')))
	{
		closure_5_fn := fn (this_ptr rt.PhpVal, args []rt.PhpVal) rt.PhpVal {
			mut iife_temp_1 := Class_Automattic_WooCommerce_Internal_Api_Schema_Type{}
			mut iife_result_1 := iife_temp_1.string()
			mut iife_temp_2 := Class_Automattic_WooCommerce_Internal_Api_Schema_Type{}
			mut iife_result_2 := iife_temp_2.nonnull(iife_result_1)
			mut iife_temp_3 :=
				Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Output_ProductReview{}
			mut iife_result_3 := iife_temp_3.get()
			mut iife_temp_4 := Class_Automattic_WooCommerce_Internal_Api_Schema_Type{}
			mut iife_result_4 := iife_temp_4.nonnull(iife_result_3)
			return rt.create_array([
				rt.ArrayItem{ key: 'cursor', val: rt.create_array([
					rt.ArrayItem{ key: 'type', val: iife_result_2 },
				]) },
				rt.ArrayItem{ key: 'node', val: rt.create_array([
					rt.ArrayItem{ key: 'type', val: iife_result_4 },
				]) },
			])
		}
		rt.set_static_prop('Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Pagination_ProductReviewEdge',
			'instance', rt.new_object('Automattic_WooCommerce_Internal_Api_Schema_ObjectType',
			[]string{}, create_automattic_woocommerce_internal_api_schema_objecttype(rt.create_array([
			rt.ArrayItem{ key: 'name', val: 'ProductReviewEdge' },
			rt.ArrayItem{ key: 'fields', val: rt.new_closure(closure_5_fn) },
		]))))
	}
	return rt.get_static_prop('Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Pagination_ProductReviewEdge',
		'instance')
}

struct Class_Automattic_WooCommerce_Internal_Api_Schema_ObjectType {
	rt.PhpObjectBase
}

struct Class_Automattic_WooCommerce_Internal_Api_Schema_Type {
	rt.PhpObjectBase
}

struct Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Output_ProductReview {
	rt.PhpObjectBase
}

fn create_automattic_woocommerce_internal_api_autogenerated_graphqltypes_pagination_productreviewedge(_args ...rt.PhpVal) &Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Pagination_ProductReviewEdge {
	mut obj := &Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Pagination_ProductReviewEdge{
		PhpObjectBase: rt.PhpObjectBase{}
	}
	return obj
}

fn create_automattic_woocommerce_internal_api_schema_objecttype(_args ...rt.PhpVal) &Class_Automattic_WooCommerce_Internal_Api_Schema_ObjectType {
	mut obj := &Class_Automattic_WooCommerce_Internal_Api_Schema_ObjectType{
		PhpObjectBase: rt.PhpObjectBase{}
	}
	return obj
}

fn create_automattic_woocommerce_internal_api_schema_type(_args ...rt.PhpVal) &Class_Automattic_WooCommerce_Internal_Api_Schema_Type {
	mut obj := &Class_Automattic_WooCommerce_Internal_Api_Schema_Type{
		PhpObjectBase: rt.PhpObjectBase{}
	}
	return obj
}

fn create_automattic_woocommerce_internal_api_autogenerated_graphqltypes_output_productreview(_args ...rt.PhpVal) &Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Output_ProductReview {
	mut obj := &Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Output_ProductReview{
		PhpObjectBase: rt.PhpObjectBase{}
	}
	return obj
}

fn (mut this Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Pagination_ProductReviewEdge) dispatch_method(method_name string, args []rt.PhpVal) ?rt.PhpVal {
	match method_name {
		'get' {
			return Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Pagination_ProductReviewEdge.get()
		}
		else {
			return none
		}
	}
}

fn (this &Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Pagination_ProductReviewEdge) dispatch_get_prop(prop_name string) ?rt.PhpVal {
	return this.PhpObjectBase.dispatch_get_prop(prop_name)
}

fn (mut this Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Pagination_ProductReviewEdge) dispatch_set_prop(prop_name string, val rt.PhpVal) bool {
	return this.PhpObjectBase.dispatch_set_prop(prop_name, val)
}

fn (mut this Class_Automattic_WooCommerce_Internal_Api_Schema_ObjectType) dispatch_method(method_name string, args []rt.PhpVal) ?rt.PhpVal {
	return none
}

fn (this &Class_Automattic_WooCommerce_Internal_Api_Schema_ObjectType) dispatch_get_prop(prop_name string) ?rt.PhpVal {
	return this.PhpObjectBase.dispatch_get_prop(prop_name)
}

fn (mut this Class_Automattic_WooCommerce_Internal_Api_Schema_ObjectType) dispatch_set_prop(prop_name string, val rt.PhpVal) bool {
	return this.PhpObjectBase.dispatch_set_prop(prop_name, val)
}

fn (mut this Class_Automattic_WooCommerce_Internal_Api_Schema_Type) dispatch_method(method_name string, args []rt.PhpVal) ?rt.PhpVal {
	return none
}

fn (this &Class_Automattic_WooCommerce_Internal_Api_Schema_Type) dispatch_get_prop(prop_name string) ?rt.PhpVal {
	return this.PhpObjectBase.dispatch_get_prop(prop_name)
}

fn (mut this Class_Automattic_WooCommerce_Internal_Api_Schema_Type) dispatch_set_prop(prop_name string, val rt.PhpVal) bool {
	return this.PhpObjectBase.dispatch_set_prop(prop_name, val)
}

fn (mut this Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Output_ProductReview) dispatch_method(method_name string, args []rt.PhpVal) ?rt.PhpVal {
	return none
}

fn (this &Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Output_ProductReview) dispatch_get_prop(prop_name string) ?rt.PhpVal {
	return this.PhpObjectBase.dispatch_get_prop(prop_name)
}

fn (mut this Class_Automattic_WooCommerce_Internal_Api_Autogenerated_GraphQLTypes_Output_ProductReview) dispatch_set_prop(prop_name string, val rt.PhpVal) bool {
	return this.PhpObjectBase.dispatch_set_prop(prop_name, val)
}

fn main() {
	defer {
		rt.shutdown()
	}
}
