--TEST--
VSlim stub generator emits IDE-friendly stubs from extension reflection
--SKIPIF--
<?php
if (!extension_loaded('vslim')) {
    echo "skip vslim extension missing";
    return;
}
?>
--FILE--
<?php
$stubPath = sys_get_temp_dir() . '/vslim-stub-' . getmypid() . '.php';
@unlink($stubPath);

$command = sprintf(
    '%s %s --extension=%s --output=%s',
    escapeshellarg(PHP_BINARY),
    escapeshellarg(dirname(__DIR__) . '/scripts/generate_stubs.php'),
    escapeshellarg(dirname(__DIR__) . '/vslim.so'),
    escapeshellarg($stubPath),
);

passthru($command, $code);
var_dump($code);

$stub = file_get_contents($stubPath);
var_dump($stub !== false);
var_dump(str_contains($stub, 'Generated by `php vslim/scripts/generate_stubs.php`.'));
var_dump(!str_contains($stub, 'function vslim_handle_request('));
var_dump(!str_contains($stub, 'function vslim_demo_dispatch('));
var_dump(!str_contains($stub, 'function vslim_probe_object('));
var_dump(!str_contains($stub, 'function vslim_response_headers('));
var_dump(!str_contains($stub, 'namespace VPhp\\VSlim'));
var_dump(str_contains($stub, 'namespace VSlim {'));
var_dump(str_contains($stub, 'class Psr7Adapter'));
var_dump(!str_contains($stub, 'public static function dispatch('));
var_dump(str_contains($stub, 'public static function toVSlimRequest(mixed $request): \VSlim\Vhttpd\Request {}'));
var_dump(str_contains($stub, 'public static function toVSlimResponse(\Psr\Http\Message\ResponseInterface $response): \VSlim\Vhttpd\Response {}'));
var_dump(str_contains($stub, 'class ObjectProbe'));
var_dump(str_contains($stub, 'public static function probe(mixed $obj, string $className, string $methodName): mixed {}'));
var_dump(str_contains($stub, 'class App'));
var_dump(str_contains($stub, 'public function get(string $pattern, mixed $handler): \VSlim\App {}'));
var_dump(str_contains($stub, 'public function dispatchRequest($req): \VSlim\Vhttpd\Response {}'));
var_dump(!str_contains($stub, 'public function dispatch_request('));
var_dump(str_contains($stub, 'public function setBasePath(string $basePath): \VSlim\App {}'));
var_dump(!str_contains($stub, 'public function set_base_path('));
var_dump(str_contains($stub, 'public function dispatchEnvelopeMap(mixed $envelope): array {}'));
var_dump(str_contains($stub, 'public function loadConfigText(string $text): \VSlim\App {}'));
var_dump(str_contains($stub, 'public function getString(string $key, string $defaultValue = \'\'): string {}'));
var_dump(str_contains($stub, 'class Config'));
var_dump(str_contains($stub, 'public function setDriver(string $driver): \VSlim\Database\Config {}'));
var_dump(!str_contains($stub, 'public function set_driver('));
var_dump(str_contains($stub, 'public function setHeader(string $name, string $value): \VSlim\Vhttpd\Response {}'));
var_dump(str_contains($stub, 'public function cookieHeader(): string {}'));
var_dump(str_contains($stub, 'public $rawPath;'));
var_dump(!str_contains($stub, 'public $raw_path;'));
var_dump(!str_contains($stub, 'public $path;'));
var_dump(!str_contains($stub, 'public $queryString;'));
var_dump(str_contains($stub, 'public function path(): string {}'));
var_dump(str_contains($stub, 'public function queryString(): string {}'));
var_dump(str_contains($stub, 'public $protocolVersion;'));
var_dump(!str_contains($stub, 'public $protocol_version;'));
var_dump(str_contains($stub, 'public $contentType;'));
var_dump(!str_contains($stub, 'public $content_type;'));
var_dump(str_contains($stub, 'public $streamType;'));
var_dump(!str_contains($stub, 'public $stream_type;'));
var_dump(str_contains($stub, 'public function withUri(\Psr\Http\Message\UriInterface $uri, bool $preserveHost = false): \Psr\Http\Message\RequestInterface {}'));
var_dump(str_contains($stub, 'public function withUri(\Psr\Http\Message\UriInterface $uri, bool $preserveHost = false): \Psr\Http\Message\ServerRequestInterface {}'));
var_dump(!str_contains($stub, '$default_preserve_host'));
var_dump(str_contains($stub, 'public function withHeader(mixed $name, mixed $value): \Psr\Http\Message\ResponseInterface {}'));
var_dump(str_contains($stub, 'public function createResponse(mixed $defaultStatus = 200, mixed $defaultReasonPhrase = \'\'): \Psr\Http\Message\ResponseInterface {}'));
var_dump(str_contains($stub, "public const DEBUG = 'debug';"));

@unlink($stubPath);
?>
--EXPECTF--
Generated %svslim-stub-%d.php
int(0)
bool(true)
bool(true)
bool(true)
bool(true)
bool(true)
bool(true)
bool(true)
bool(true)
bool(true)
bool(true)
bool(true)
bool(true)
bool(true)
bool(true)
bool(true)
bool(true)
bool(true)
bool(true)
bool(true)
bool(true)
bool(true)
bool(true)
bool(true)
bool(true)
bool(true)
bool(true)
bool(true)
bool(true)
bool(true)
bool(true)
bool(true)
bool(true)
bool(true)
bool(true)
bool(true)
bool(true)
bool(true)
bool(true)
bool(true)
bool(true)
bool(true)
bool(true)
bool(true)
bool(true)
bool(true)
bool(true)
