--TEST--
VSlim stub generator emits IDE-friendly stubs from extension reflection
--SKIPIF--
<?php
if (!extension_loaded('vslim')) {
    echo "skip vslim extension missing";
    return;
}
?>
--FILE--
<?php
$stubPath = sys_get_temp_dir() . '/vslim-stub-' . getmypid() . '.php';
@unlink($stubPath);

$command = sprintf(
    '%s %s --output=%s',
    escapeshellarg(PHP_BINARY),
    escapeshellarg(dirname(__DIR__) . '/scripts/generate_stubs.php'),
    escapeshellarg($stubPath),
);

passthru($command, $code);
var_dump($code);

$stub = file_get_contents($stubPath);
var_dump($stub !== false);
var_dump(str_contains($stub, 'Generated by `php vslim/scripts/generate_stubs.php`.'));
var_dump(str_contains($stub, 'function vslim_handle_request(mixed $method_or_envelope, string $raw_path = \'\', string $body = \'\'): mixed {}'));
var_dump(str_contains($stub, 'class App'));
var_dump(str_contains($stub, 'public function get(string $pattern, mixed $handler): \VSlim\App {}'));
var_dump(str_contains($stub, 'public function withHeader(mixed $name, mixed $value): \Psr\Http\Message\ResponseInterface {}'));
var_dump(str_contains($stub, 'public function createResponse(mixed $default_status = 200, mixed $default_reason_phrase = \'\'): \Psr\Http\Message\ResponseInterface {}'));
var_dump(str_contains($stub, "public const DEBUG = 'debug';"));

@unlink($stubPath);
?>
--EXPECTF--
Generated %svslim-stub-%d.php
int(0)
bool(true)
bool(true)
bool(true)
bool(true)
bool(true)
bool(true)
bool(true)
bool(true)
